#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/13 00:52:34 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/13 00:52:34  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	sk_tax_upd
SRCS	=	sk_tax_upd.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
