#
# makefile for so_cf_dsp.
#
#	Generated - on : 06/05/91
#	          - at : 11:28:46 AM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = so_cf_dsp.o

TARGET = $(DESTDIR)/so_cf_dsp

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
