#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.0 2002/05/08 01:22:27 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.0  2002/05/08 01:22:27  scott
#	CVS administration
#	
#	Revision 1.2  2001/08/06 23:31:23  scott
#	RELEASE 5.0
#	
#	Revision 1.1  2001/06/21 05:23:02  scott
#	First release - program re-creates gl transactions for automatic production issue
#	
#
#

APP		=	pc_autoissGlFix
SRCS	=	pc_autoissGlFix.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
