#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/11/28 04:09:46 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/11/28 04:09:46  scott
#	SC0053 - Platinum Logistics - LS10.5.2 2002-11-28
#	Updated for changes in pricing - See S/C for Details
#	
#
#

APP		=	so_pri_dsp
SRCS	=	so_pri_dsp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
