#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/02/22 05:12:45 kaarlo Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/02/22 05:12:45  kaarlo
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	so_miss_inv
SRCS	=	miss_inv.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
