#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/22 08:22:22 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/22 08:22:22  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_ho_prn
SRCS	=	db_ho_prn.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
