#
#	Standard application Makefile template
#
APP		=	format-p

SRCS	=	format-p.C \
			GenericFilter.C \
			LayoutMgr.C LineReader.C \
			Options.C OutputRecvr.C \
			PFormatter.C \
			ValueRegister.C

include ${BASE_PATH}/${VERSION}/CONFIG/Make.Base
