#
#	Standard application Makefile template
#
############################################
#
#		$Id: Makefile,v 5.1 2001/08/06 23:27:23 scott Exp $
#		$Log: Makefile,v $
#		Revision 5.1  2001/08/06 23:27:23  scott
#		RELEASE 5.0
#		
#		Revision 5.0  2001/06/19 08:07:13  robert
#		LS10-5.0 New Release as of 19 JUNE 2001
#		
#		Revision 4.0  2001/03/09 02:28:18  scott
#		LS10-4.0 New Release as at 10th March 2001
#		
#		Revision 3.0  2000/10/10 12:15:21  gerry
#		Revision No. 3 Start
#		<after Rel-10102000>
#		
#		Revision 2.0  2000/07/15 08:58:33  gerry
#		Forced Revision No. Start 2.0 Rel-15072000
#		
#		Revision 1.3  2000/06/13 05:29:03  scott
#		S/C LSANZ 16400
#		Updated to allow for demand type '6' related to production issues.
#		NOTE : Please see release notes on new search.
#		sk_mrmaint, sk_delete, psl_sr_gen and sch.srsk must be installed/rebuilt.
#		
#
#

APP		=	lrp_demand.i
SRCS	=	_demand.i.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
