#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:25:55 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:25:55  scott
#	RELEASE 5.0
#	
#
#

APP		=	fa_mend
SRCS	=	fa_mend.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
