#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:43 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:43  scott
#	Update - LS10.5
#	
#
#

APP		=	sk_act_rep
SRCS	=	sk_act_rep.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
