#
# makefile for cm_req_prt.
#
#	Generated - on : 15/04/93
#	          - at : 12:00:08 PM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = cm_req_prt.o

TARGET = $(DESTDIR)/cm_req_prt

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
