#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.1 2001/08/06 23:01:26 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:01:26  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:03:12  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:23:42  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:12:49  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 08:40:50  gerry
#	Forced Revision No. Start 2.0 Rel-15072000
#	
#	Revision 1.2  1999/11/10 08:45:29  scott
#	Updated to add app.schema
#	
#	
#	
#	
APP		=	cr_ictogl
SRCS	=	cr_ictogl.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
