#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:12 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:12  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:28:59  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/01/30 03:43:22  scott
#	Updated to add app.schema
#	
#
#

APP		=	lrp_whrepl
SRCS	=	lrp_whrepl.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
