#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:17:58 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:17:58  scott
#	Update - LS10.5
#	
#
#

APP		=	gl_reccode_mnt
SRCS	=	reccode_mnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
