#
#	Standard application Makefile template
#
############################################
#
#		$Id: Makefile,v 5.1 2001/08/06 23:45:18 scott Exp $
#		$Log: Makefile,v $
#		Revision 5.1  2001/08/06 23:45:18  scott
#		RELEASE 5.0
#		
#		Revision 5.0  2001/06/19 08:16:25  robert
#		LS10-5.0 New Release as of 19 JUNE 2001
#		
#		Revision 4.0  2001/03/09 02:37:41  scott
#		LS10-4.0 New Release as at 10th March 2001
#		
#		Revision 3.0  2000/10/10 12:20:27  gerry
#		Revision No. 3 Start
#		<after Rel-10102000>
#		
#		Revision 2.0  2000/07/15 09:11:08  gerry
#		Forced Revision No Start 2.0 Rel-15072000
#		
#		Revision 1.3  2000/06/13 05:03:02  scott
#		New Search routine that allow multi level searches using
#		Item number, description, Alpha code, alternate no, maker number, selling group,
#		buying group using AND or OR searches.
#		New search beings routines into the library to speed up GVision.
#		See seperate release notes.
#		
#
#

APP		=	sk_lot_expiry
SRCS	=	lot_expiry.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
