#
# makefile for psl_grp_mnt.
#
#	Generated - on : 25/11/92
#	          - at : 08:58:25 AM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = _grp_mnt.o

TARGET = $(DESTDIR)/psl_grp_mnt

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
