#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/12 06:35:04 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/12 06:35:04  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	sk_tax_mnt
SRCS	=	sk_tax_mnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
