#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/20 03:45:42 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/20 03:45:42  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	so_usr_rel
SRCS	=	so_usr_rel.c
ALTS	=	so_usr_trel

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
