#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/03/05 02:49:38 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/03/05 02:49:38  scott
#	S/C 00825 - BOMMT10 - Maintain Handling Class. The header title of the program should be  'Handling Class Maintenance'.
#	
#
#

APP		=	bm_haz_inp
SRCS	=	bm_haz_inp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
