#
# makefile for sk_sprint.
#
#	Generated - on : 26/09/89
#	          - at : 09:32:48 AM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = sk_sprint.o

TARGET = $(DESTDIR)/sk_sprint

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
