#
# makefile for sa_dfcat.
#
#	Generated - on : 04/06/91
#	          - at : 02:36:37 PM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = sa_dfcat.o

TARGET = $(DESTDIR)/sa_dfcat

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
