#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/01/11 02:07:29 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/01/11 02:07:29  scott
#	Updated as first phase of contract management cleanup on it's way to becoming
#	useable for 3PL.
#	
#
#

APP		=	cm_cnt_set
SRCS	=	cm_cnt_set.c
ALTS	=	cm_cnt_rel cm_close

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
