#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.1 2001/07/25 02:18:56 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:56  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:36:42  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:19:54  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 09:10:30  gerry
#	Forced Revision No Start 2.0 Rel-15072000
#	
#	Revision 1.2  1999/11/23 02:43:07  scott
#	Updated to remove ffex and update ffdm. Updated as inmu not being opened.
#	
#	Revision 1.1  1999/11/16 09:52:40  scott
#	Added to so would not come up on cvs update all the time.
#	
#	
#	
#	
APP		=	sk_close
SRCS	=	sk_close.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
