#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:27:26 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:27:26  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:07:18  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:28:25  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/01/30 05:32:01  scott
#	Update to add app.schema
#	
#
#

APP		=	lrp_envinp
SRCS	=	lrp_envinp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
