#
#	Standard application Makefile template
#
#############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 22:56:15 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 22:56:15  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:02:08  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:21:36  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:12:11  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 08:38:30  gerry
#	Forced Revsions No Start to 2.0 Rel-15072000
#	
#	Revision 1.3  2000/02/29 06:07:29  gerry
#	Inserted id and log keywords in makefile
#	
#
#
APP		=	cm_emp_time
SRCS	=	emp_time.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
