#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:44:42 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:44:42  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:15:10  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:36:35  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/02/06 10:07:40  scott
#	Updated to deal with length change in the following fields
#	intr_ref1 from 10 to 15 characters
#	intr_ref2 from 10 to 15 characters
#	inaf_ref1 from 10 to 15 characters
#	inaf_ref2 from 10 to 15 characters
#	
#	Revision 3.0  2000/10/10 12:19:49  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/08/10 09:30:49  scott
#	Updated to add operator, time and date stamp to audit file inaf.
#	
#
#

APPSFLAGS	=	"-nBG"

APP		=	sk_bgmove
SRCS	=	sk_bgmove.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
