#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:34:52 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:34:52  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:10:02  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 1.1  2001/04/20 07:28:46  scott
#	New program for XML automatic delete of works order.
#	
#
#

APP		=	pc_autoWoDel
SRCS	=	pc_autoWoDel.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
