#
#	Standard application Makefile template
#
################################################################################
# 	$Id: Makefile,v 5.1 2001/07/25 02:18:58 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:58  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:36:45  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:19:56  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 09:10:32  gerry
#	Forced Revision No Start 2.0 Rel-15072000
#	
#	Revision 1.3  2000/02/09 05:44:27  scott
#	Updated stock valuations to use new common Stock valuation routine. In addition all costing methods are supported. F(ifo) L(I)fo L(ast) S(T)andard P(revious) S(erial) A(verage). All report balance to the absolute cent, what a treat.
#	
#
APP		=	sk_covalue
SRCS	=	sk_covalue.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
