#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:50:49 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:50:49  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:18:36  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 1.1  2001/04/24 06:37:32  scott
#	New automatic Dispatch confirmation (PIPE/XML) version.
#	
#

APP		=	so_autoDesConf
SRCS	=	so_autoDesConf.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
