#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:19:28 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:19:28  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:38:44  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/02/16 07:25:40  scott
#	Updated to convert to app.schema
#	
#
#

APP		=	sk_rollup
SRCS	=	sk_rollup.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
