#
# makefile for mh_purge.
#
#	Generated - on : 23/08/89
#	          - at : 11:17:12 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = mh_purge.o

TARGET = $(DESTDIR)/mh_purge

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
