#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:27:34 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:27:34  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:07:25  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:28:34  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/01/24 08:37:20  scott
#	Updated to add app.schema
#	
#
#

APP		=	lrp_inws_inp
SRCS	=	_inws_inp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
