#
# makefile for run_extern.
#
#	Generated - on : 25/08/89
#	          - at : 01:53:59 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = run_extern.o

TARGET = $(DESTDIR)/run_extern

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
