#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:28:01 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:28:01  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:07:48  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:29:00  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/01/29 08:54:31  scott
#	Updated to add app.schema
#	
#
#

APP		=	lrp_wk_del
SRCS	=	lrp_wk_del.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
