#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:20:04 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:20:04  scott
#	Update - LS10.5
#	
#	Revision 4.1  2001/03/16 06:37:58  scott
#	Updated to fix display prompts for LS10-GUI
#	Updated to clean program and convert to use app.schema
#	
#
#

APP		=	so_sales
SRCS	=	so_sales.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
