#
# makefile for log_error.
#
#	Generated - on : 23/08/89
#	          - at : 10:46:30 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = log_error.o

TARGET = $(DESTDIR)/log_error

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
