#
# makefile for batch_dsp.
#
#	Generated - on : 23/08/89
#	          - at : 11:08:29 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = batch_dsp.o

TARGET = $(DESTDIR)/batch_dsp

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
