#
# makefile for chk_secure.
#
#	Generated - on : 23/08/89
#	          - at : 10:38:55 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = chk_secure.o

TARGET = $(DESTDIR)/chk_secure

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
