#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:45:11 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:45:11  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:16:14  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:37:33  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 1.1  2000/11/22 00:25:43  scott
#	Added new program
#	
#
#

APP		=	sk_llst_mnt
SRCS	=	sk_llst_mnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
