#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:51:30 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:51:30  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:20:02  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/03/16 04:34:28  scott
#	Updated to clean code and add app.schema
#	Updated to ensure selection screen displays correctly with LS10-GUI
#	
#
#

APP		=	so_lsaleprt
SRCS	=	lsaleprt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
