#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.2 2001/12/07 03:59:09 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2001/12/07 03:59:09  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#	Revision 5.1  2001/08/06 23:22:21  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:05:18  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:25:44  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:14:11  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 08:52:56  gerry
#	Forced Revision No. Start 2.0 Rel-15072000
#	
#	Revision 1.2  1999/12/16 05:17:59  scott
#	Updated to add app.schema
#	
#	
#	
APP		=	db_period_up
SRCS	=	db_period_up.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
