#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:53:48 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:53:48  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:21:36  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:42:49  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2000/12/11 05:59:00  scott
#	Updated to fix core dump and clean code including addition of app.schema
#	
#
#

APP		=	tr_delivery
SRCS	=	delivery.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
