#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/14 03:34:01 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/14 03:34:01  scott
#	Updated to use app.schema
#	Updated to clean code.
#	
#
#

APP		=	tm_canalysis
SRCS	=	canalysis.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
