#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:19:02 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:19:02  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:36:58  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:20:03  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 09:10:39  gerry
#	Forced Revision No Start 2.0 Rel-15072000
#	
#	Revision 1.2  2000/07/14 04:07:20  scott
#	Updated to add app.schema as part of general maintenance
#	Updated to use correct search.
#	
#
#

APP		=	sk_del_inp
SRCS	=	sk_del_inp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
