#
#	Standard application Makefile template
#
############################################
#
#		$Id: Makefile,v 5.1 2001/07/25 02:17:51 scott Exp $
#		$Log: Makefile,v $
#		Revision 5.1  2001/07/25 02:17:51  scott
#		Update - LS10.5
#		
#		Revision 5.0  2001/06/19 08:06:43  robert
#		LS10-5.0 New Release as of 19 JUNE 2001
#		
#		Revision 4.0  2001/03/09 02:27:16  scott
#		LS10-4.0 New Release as at 10th March 2001
#		
#		Revision 3.0  2000/10/10 12:15:04  gerry
#		Revision No. 3 Start
#		<after Rel-10102000>
#		
#		Revision 2.0  2000/07/15 08:57:20  gerry
#		Forced Revision No Start 2.0 Rel-15072000
#		
#		Revision 1.3  2000/02/29 05:52:42  gerry
#		New makefile format, app schema changes
#		
#
#

APP		=	gl_jnlpage
SRCS	=	gl_jnlpage.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
