#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/07/09 08:39:23 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/07/09 08:39:23  scott
#	Converted to app.schema
#	
#
#

APP		=	ca_bk_tran
SRCS	=	ca_bk_tran.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
