#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/07 04:52:11 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/07 04:52:11  scott
#	Updated to convert to app.schema
#	Updated to replace fgets with scanf
#	Updated to clean code and remove disk write with memory sort.
#	
#
#

APP		=	pc_chk_iss
SRCS	=	pc_chk_iss.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
