#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/04/30 07:56:49 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/04/30 07:56:49  scott
#	Update for new Archive modifications;
#	
#
#

APP		=	so_man_rel
SRCS	=	so_man_rel.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
