#
# makefile for ts_lbl_prt.
#
#	Generated - on : 22/06/92
#	          - at : 11:12:39 AM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = ts_lbl_prt.o

TARGET = $(DESTDIR)/ts_lbl_prt

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
