#
# makefile for pc_woprint.
#
#	Generated - on : 10/03/92
#	          - at : 02:42:31 PM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = pc_woprint.o

TARGET = $(DESTDIR)/pc_woprint

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
