#
# makefile for po_inis_prd.
#
#	Generated - on : 23/08/89
#	          - at : 11:27:14 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = inis_prd.o

TARGET = $(DESTDIR)/po_inis_prd

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
