#
# makefile for mn_acdprint.
#
#	Generated - on : 18/10/91
#	          - at : 12:12:22 PM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = acdprint.o

TARGET = $(DESTDIR)/mn_acdprint

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
