#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:01:39 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:01:39  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:03:32  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:24:01  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/01/22 08:16:20  scott
#	Updated to modify way program works so unique mask as not required for LS10-GUI
#	
#
#

APP		=	cr_para_inp
SRCS	=	para_inp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
