#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/03/06 08:47:57 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/03/06 08:47:57  scott
#	S/C 00883 - BOMMT8-Maintain Exclusion File. When pressed <F1> then <F4>, the 'Code' column displays different data. When steps are repeated, code column displays an additional data which is the exclusion data. All data should be displayed on the first querry.
#	
#
#

APP		=	bm_excl_inp
SRCS	=	bm_excl_inp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
