#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:17:44 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:17:44  scott
#	Update - LS10.5
#	
#
#

APP		=	gl_del_ccomp
SRCS	=	del_ccomp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
