#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.1 2001/08/06 23:01:18 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:01:18  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:02:57  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:23:26  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:12:40  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 08:40:41  gerry
#	Forced Revision No. Start 2.0 Rel-15072000
#	
#	Revision 1.2  2000/01/27 01:37:53  scott
#	Updated to check reports to verify if detailed and summary balance.
#	Updated to use app.schema and changed reports headings.
#	Service Request ASL Issue 253
#	
#	Revision 1.2  1999/12/16 04:22:30  scott
#	Updated to remove pre-defined log
#	
#	
#	
#	
APP		=	cr_comrep1
SRCS	=	cr_comrep1.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
