#
# makefile for psl_labels.
#
#	Generated - on : 22/02/93
#	          - at : 03:25:18 PM
#	          - by : simon
#

SHELL   = /bin/sh

OBJS = psl_labels.o

TARGET = $(DESTDIR)/psl_labels

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
