#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/01/22 06:39:50 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/01/22 06:39:50  scott
#	Updated as first phase of contract management cleanup on it's way to becoming
#	useable for 3PL.
#	
#
#

APP		=	cm_inv_prep
SRCS	=	cm_inv_prep.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
