#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.1 2001/07/25 02:20:05 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:20:05  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:41:59  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:23:04  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 09:13:56  gerry
#	Forced Revision No Start 2.0 Rel-15072000
#	
#	Revision 1.2  1999/12/16 04:21:48  scott
#	General cleanup while looking at ASL issue.
#	
#	
#	
#	
#	
APP		=	so_stkup
SRCS	=	so_stkup.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
