#
# makefile for so_invmhup.
#
#	Generated - on : 23/08/89
#	          - at : 11:46:10 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = so_invmhup.o

TARGET = $(DESTDIR)/so_invmhup

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
