#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/12 07:34:33 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/12 07:34:33  scott
#	Updated to add app.schema
#	Updated to clean code.
#	
#
#

APP		=	tm_operator
SRCS	=	operator.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
