#
# makefile for bg_maint.
#
#	Generated - on : 23/08/89
#	          - at : 11:08:04 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = bg_maint.o

TARGET = $(DESTDIR)/bg_maint

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
