#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/07/09 09:09:04 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/07/09 09:09:04  scott
#	Converted to app.schema
#	
#
#

APP		=	ca_recon_rep
SRCS	=	ca_recon_rep.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
