HMARGIN   .B5
QUOTE              QUOTATION
DATE               DATE : ^DD/DD/DDDD^
MARGIN1   .B1
QUOTE_NO           QUOTATION NO : ^AAAAAAAA^
MARGIN2   .B2
CUST               CUSTOMER :                                 YOUR REF : ^AAAAAAAAAAAAAAAAAAAA^
CUST_NAME          ^AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA^
CUST_ADR1          ^AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA^
CUST_ADR2          ^AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA^
CUST_ADR3          ^AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA^
CUST_ADR4          ^AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA^
MARGIN3   .B1
PLEASURE           WE HAVE PLEASURE IN SUBMITTING OUR QUOTATION AS FOLLOWS
MARGIN4   .B1
HEADER       PRODUCT                 DESCRIPTION                                QUANTITY      UNIT PRICE     
MARGIN5   .B2
QT_LINE      ^AAAAAAAAAAAAAAAA^        ^AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA^   ^FFFFFFF.FF^    ^FFFFFFFFF.FF^
MARGIN6   .B3
TERMS        TERMS OF SUPPLY  : 
CURRENCY     CURRENCY QUOTED  : ^AAA^
SELL_TERM    SELLING TERMS    : ^AAA^                                            ---------------------------------
PAY_TERM     PAYMENT TERMS    : ^AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA^   
COMMENTS     GENERAL COMMENTS :    
COMM1        ^AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA^
COMM2        ^AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA^
COMM3        ^AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA^   SALES CONTACT : ^AA^
VBLE_BLK  .B^I^
