#
# makefile for so_disprn.
#
#	Generated - on : 11/04/90
#	          - at : 10:13:25 AM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = so_disprn.o

TARGET = $(DESTDIR)/so_disprn

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
