#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:37:12 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:37:12  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:11:58  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:33:14  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:18:00  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/08/22 05:32:44  scott
#	Updated to add number plate logging of Goods Receipts.
#	See Environment SK_GRIN_NOPLATE
#	
#
#

APP		=	po_receipt
SRCS	=	po_receipt.c
ALTS	=	po_issue

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
