#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:45:51 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:45:51  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:17:40  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 1.1  2001/03/14 01:40:58  scott
#	New program to copy containers.
#	
#
#

APP		=	sk_skcm_cp
SRCS	=	sk_skcm_cp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
