#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:45:49 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:45:49  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:17:37  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:38:53  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2000/11/20 07:40:32  scott
#	New features related to 3PL environment
#	New features related to Number Plates
#	All covered in release 3 notes
#	
#
#

APP		=	sk_seradj
SRCS	=	sk_seradj.c
ALTS	=	sk_dseradj

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
