#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:17:39 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:17:39  scott
#	Update - LS10.5
#	
#
#

APP		=	gl_chartdsp
SRCS	=	chartdsp.c
ALTS	=	gl_chartprt

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
