#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/26 04:44:44 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/26 04:44:44  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_led_chk
SRCS	=	db_led_chk.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
