#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/01/10 09:25:00 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/01/10 09:25:00  scott
#	Updated as first phase of contract management cleanup on it's way to becoming
#	useable for 3PL.
#	
#
#

APP		=	cm_cnt_desc
SRCS	=	cm_cnt_desc.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
