#
# makefile for batch_post.
#
#	Generated - on : 23/08/89
#	          - at : 10:43:06 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = batch_post.o

TARGET = $(DESTDIR)/batch_post

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
