#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/12 05:37:34 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/12 05:37:34  scott
#	Updated to convert to app.schema
#	Updated to clean up code
#	
#
#

APP		=	tm_convert
SRCS	=	tm_convert.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
