#
# makefile for pc_wodisp.
#
#	Generated - on : 05/10/93
#	          - at : 08:50:37 AM
#	          - by : aroha
#

SHELL   = /bin/sh

OBJS = pc_wodisp.o

TARGET = $(DESTDIR)/pc_wodisp

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
