#
#	Standard application Makefile template
#
############################################
#
#		$Id: Makefile,v 5.1 2001/08/06 22:51:38 scott Exp $
#		$Log: Makefile,v $
#		Revision 5.1  2001/08/06 22:51:38  scott
#		RELEASE 5.0
#		
#		Revision 5.0  2001/06/19 07:17:27  robert
#		LS10-5.0 New Release as of 19 JUNE 2001
#		
#		Revision 4.0  2001/03/09 01:07:06  scott
#		LS10-4.0 New Release as at 10th March 2001
#		
#		Revision 3.0  2000/10/10 12:11:02  gerry
#		Revision No. 3 Start
#		<after Rel-10102000>
#		
#		Revision 2.0  2000/07/15 08:21:15  gerry
#		Forced Revision No. Start to 2.0 Rel-15072000
#		
#		Revision 1.2  2000/03/06 05:48:59  gerry
#		New makefile, app.schema changes
#		
#
#

APP		=	as_acq_prn
SRCS	=	as_acq_prn.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
