#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:39:44 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:39:44  scott
#	RELEASE 5.0
#	
#
#

APP		=	rg_resmnt
SRCS	=	rg_resmnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
