#
#	Standard application Makefile template
#
############################################
#
#		$Id: Makefile,v 5.1 2001/08/06 22:55:57 scott Exp $
#		$Log: Makefile,v $
#		Revision 5.1  2001/08/06 22:55:57  scott
#		RELEASE 5.0
#		
#		Revision 5.0  2001/06/19 08:01:47  robert
#		LS10-5.0 New Release as of 19 JUNE 2001
#		
#		Revision 4.0  2001/03/09 01:07:26  scott
#		LS10-4.0 New Release as at 10th March 2001
#		
#		Revision 3.0  2000/10/10 12:11:56  gerry
#		Revision No. 3 Start
#		<after Rel-10102000>
#		
#		Revision 2.0  2000/07/15 08:38:17  gerry
#		Forced Revsions No Start to 2.0 Rel-15072000
#		
#		Revision 1.2  2000/02/29 08:57:33  gerry
#		New make and app.schema
#		
#
#

APP		=	cm_adj_jnl
SRCS	=	cm_adj_jnl.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
