#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.0 2002/05/07 10:03:04 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.0  2002/05/07 10:03:04  scott
#	Updated to ensure version numbers on new programs are correct.
#	
#	Revision 1.1  2001/08/14 02:49:56  scott
#	Updated for new delete wizard
#	
#

APP		=	MenuDeleteControl
SRCS	=	MenuDeleteControl.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
