#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/12 01:22:26 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/12 01:22:26  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	sk_mend
SRCS	=	sk_mend.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
