#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/14 04:08:19 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/14 04:08:19  scott
#	Updated to convert to app.schema
#	
#
#

APP		=	tm_clbk_dsp
SRCS	=	clbk_dsp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
