#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/07 03:26:34 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/07 03:26:34  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_stmtprn.i
SRCS	=	db_stmtprn.i.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
