#
#	Standard application Makefile template
#
############################################
#
#		$Id: Makefile,v 5.1 2001/08/06 22:51:40 scott Exp $
#		$Log: Makefile,v $
#		Revision 5.1  2001/08/06 22:51:40  scott
#		RELEASE 5.0
#		
#		Revision 5.0  2001/06/19 08:00:45  robert
#		LS10-5.0 New Release as of 19 JUNE 2001
#		
#		Revision 4.0  2001/03/09 01:10:50  scott
#		LS10-4.0 New Release as at 10th March 2001
#		
#		Revision 3.0  2000/10/10 12:11:03  gerry
#		Revision No. 3 Start
#		<after Rel-10102000>
#		
#		Revision 2.0  2000/07/15 08:27:54  gerry
#		Forced Revsion No. Start to 2.0 - Rel-15072000
#		
#		Revision 1.2  2000/03/06 11:49:37  gerry
#		New makefile and appschema changes.  Also removed PNAME.
#		
#
#

APP		=	as_brnd_inp
SRCS	=	brnd_inp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
