#
# makefile for co_page.
#
#	Generated - on : 26/09/89
#	          - at : 09:29:58 AM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = co_page.o

TARGET = $(DESTDIR)/co_page

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
