#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 22:56:21 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 22:56:21  scott
#	RELEASE 5.0
#	
#
#

APP		=	cm_jtmaint
SRCS	=	cm_jtmaint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
