#
# makefile for dp_select.
#
#	Generated - on : 23/08/89
#	          - at : 10:44:50 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = dp_select.o

TARGET = $(DESTDIR)/dp_select

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
