#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/07/16 02:43:03 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/07/16 02:43:03  scott
#	Updated from service calls and general maintenance.
#	
#
#

APP		=	rg_rateupd
SRCS	=	rg_rateupd.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
