#
# makefile for mh_cfmaint.
#
#	Generated - on : 23/08/89
#	          - at : 11:06:20 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = mh_cfmaint.o

TARGET = $(DESTDIR)/mh_cfmaint

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
