#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:19:38 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:19:38  scott
#	Update - LS10.5
#	
#	Revision 4.1  2001/04/23 10:41:20  scott
#	Updated to add app.schema - removes code related to tables from program as it
#	allows for better quality contol.
#	Updated to perform routine maintenance to ensure standards are maintained.
#	Updated to remove usage of old include files.
#	
#
#

APP		=	sk_svalf_prn
SRCS	=	svalf_prn.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
