#
# makefile for so_inprint.
#
#	Generated - on : 23/08/89
#	          - at : 11:41:08 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = so_inprint.o

TARGET = $(DESTDIR)/so_inprint

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
