#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/26 05:11:43 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/26 05:11:43  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_mr_delinp
SRCS	=	db_mr_delinp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
