#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:45:29 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:45:29  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:16:55  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:38:13  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:20:48  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/07/28 08:34:50  scott
#	S/C 3101 - Change related to extra description.
#	Updated to add environment variable SK_ST_DESC_SHOW to print extra description
#	if required, simply  taking it out was not ideal.
#	Also fixes problem with stock take sheets related to printing multiple lines
#	when SAME locations exists for SAME item with different UOM.
#	
#
#

APP		=	sk_nst_prt
SRCS	=	sk_nst_prt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
