#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:17:32 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:17:32  scott
#	Update - LS10.5
#	
#
#

APP		=	gl_batch_del
SRCS	=	batch_del.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
