#
#	Standard application Makefile template
#
############################################
#
#	$Id
#	$Log
#

APP		=	gl_gltrCheck
SRCS	=	gl_gltrCheck.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
