#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:32:47 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:32:47  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:09:57  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/04/06 06:42:35  scott
#	Updated to add app.schema - removes code related to tables from program as it
#	allows for better quality contol.
#	Updated to perform routine maintenance to ensure standards are maintained.
#	
#
#

APP		=	srcheck
SRCS	=	srcheck.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
