#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:38:15 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:38:15  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:12:42  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/05/02 08:57:11  scott
#	Updated to add app.schema - removes code related to tables from program as it
#	allows for better quality contol.
#	Updated to perform routine maintenance to ensure standards are maintained.
#	
#
#

APP		=	qt_del_quote
SRCS	=	del_quote.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
