#
# makefile for psl_s_pad.
#
#	Generated - on : 13/06/91
#	          - at : 10:50:22 AM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = psl_s_pad.o

TARGET = $(DESTDIR)/psl_s_pad

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
