#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:21 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:21  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/04/02 00:00:57  scott
#	Updated new program to release 4.(x)
#	
#	Revision 1.1  2001/03/30 07:34:02  scott
#	New program - first clean compile.
#	
#
#

APP		=	pc_autorec
SRCS	=	pc_autorec.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
