#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:17:33 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:17:33  scott
#	Update - LS10.5
#	
#	Revision 5.0  2001/06/19 08:06:17  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/05/06 09:48:24  scott
#	Updated to add app.schema - removes code related to tables from program as it
#	allows for better quality contol.
#	Updated to perform routine maintenance to ensure standards are maintained.
#	Updated as MAXLINES has been commented out causing an error with journals > 50 lines
#	
#
#

APP		=	gl_batch_disp
SRCS	=	batch_disp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
