#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/23 04:28:53 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/23 04:28:53  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	sk_top_fif
SRCS	=	sk_top_fif.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
