#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:17:08 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:17:08  scott
#	Update - LS10.5
#	
#	Revision 5.0  2001/06/19 08:04:22  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:24:50  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:13:41  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/09/06 01:56:43  scott
#	This is checked in before modifications required
#	
#
#

APP		=	db_crctogl
SRCS	=	db_crctogl.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
