#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.0 2002/05/08 01:24:38 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.0  2002/05/08 01:24:38  scott
#	CVS administration
#	
#	Revision 1.1  2001/12/03 00:32:06  scott
#	New program to display shipments.
#	
#

APP		=	po_ship_disp
SRCS	=	po_ship_disp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
