#
# makefile for mh_sdmaint.
#
#	Generated - on : 23/08/89
#	          - at : 11:20:02 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = mh_sdmaint.o

TARGET = $(DESTDIR)/mh_sdmaint

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
