#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/07 07:42:55 kaarlo Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/07 07:42:55  kaarlo
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	cr_uainvrep
SRCS	=	uainvrep.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
