#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:19:00 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:19:00  scott
#	Update - LS10.5
#	
#
#

APP		=	sk_cuqbrep
SRCS	=	sk_cuqbrep.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
