#
# makefile for sa_dfadj.
#
#	Generated - on : 07/06/91
#	          - at : 10:43:17 AM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = sa_dfadj.o

TARGET = $(DESTDIR)/sa_dfadj

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
