#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2001/12/07 03:53:54 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2001/12/07 03:53:54  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#	Revision 5.1  2001/08/06 23:22:11  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:04:57  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:25:23  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/01/23 03:07:50  scott
#	Updated to ensure program compiles without change with LS10-GUI
#	
#
#

APP		=	db_lett_prn
SRCS	=	db_lett_prn.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
