#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:19:36 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:19:36  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:39:12  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/01/30 09:47:51  scott
#	Updated to use app.schema
#	
#
#

APP		=	sk_sumaint
SRCS	=	sk_sumaint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
