#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/06 09:22:11 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/06 09:22:11  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_sa_cust
SRCS	=	db_sa_cust.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
