#
# makefile for dberror.
#
#	Generated - on : 23/08/89
#	          - at : 11:13:45 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = dberror.o

TARGET = $(DESTDIR)/dberror

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
