#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:51:10 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:51:10  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:19:27  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:40:46  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/01/31 07:59:06  scott
#	Updated to fix display problem on Linux (RED FLAG) and to convert to use
#	app.schema
#	
#
#

APP		=	so_cusdisp
SRCS	=	so_cusdisp.c
ALTS	=	so_stkdisp

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
