#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/11 02:29:03 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/11 02:29:03  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	ar_invprnt.i
SRCS	=	ar_invprnt.i.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
