#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2002/05/09 07:38:45 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2002/05/09 07:38:45  scott
#	.
#	
#	Revision 5.1  2002/05/09 07:30:52  scott
#	.
#	
#
#

APP		=	sk_conv_outer
SRCS	=	sk_conv_outer.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
