#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/04 00:47:44 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/04 00:47:44  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_lists
SRCS	=	db_lists.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
