#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/02/28 09:23:40 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/02/28 09:23:40  scott
#	Added app.schema
#	Clean code and make it look better.
#	
#
#

APP		=	sk_inis_mup
SRCS	=	sk_inis_mup.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
