#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:52:07 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:52:07  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:20:46  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:42:02  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/03/06 01:13:56  scott
#	Updated to allow works order backorder line
#	
#
#

APP		=	so_sts_disp
SRCS	=	sts_disp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
