#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2002/03/08 04:01:06 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2002/03/08 04:01:06  scott
#	Updated to use memory based sorting.
#	
#	Revision 5.1  2001/08/06 23:45:30  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:16:57  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:38:17  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:20:50  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/08/01 02:50:01  scott
#	General Maintenance - Added app.schema
#	
#
#

APP		=	sk_nst_sort
SRCS	=	sk_nst_sort.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
