#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:22 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:22  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:31:24  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:17:00  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 09:03:09  gerry
#	forced Revision no start 2.0 Rel-15072000
#	
#	Revision 1.4  2000/07/10 09:29:49  scott
#	S/C SEL-16434 / LSDI-3039
#	(1) Updated to deal with non stock items correctly.
#	(2) Added app.schema and clean up code.
#	
#
#

APP		=	pc_issue
SRCS	=	pc_issue.c
ALTS	=	pc_return

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
