#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:51:55 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:51:55  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:20:30  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:41:47  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:22:56  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 09:13:45  gerry
#	Forced Revision No Start 2.0 Rel-15072000
#	
#	Revision 1.2  2000/07/13 23:36:14  scott
#	Updated to add app.schema as part of general maintenance.
#	Updated to delete from lineNumber -1 instead of 0 as some lines could start
#	at -1 due to sorting.
#	
#
#

APP		=	so_rt_del
SRCS	=	so_rt_del.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
