#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.1 2001/08/07 00:08:01 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/07 00:08:01  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 07:05:53  cha
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 00:54:38  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 2.0  2000/07/15 07:28:43  gerry
#	Forced Revision no. start to 2.0 - Rel-15072000
#	
#	Revision 1.1  1999/11/15 23:20:34  scott
#	Updated Licence
#	
#	
#	
#	
APP		=	lc_create
SRCS	=	lc_create.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
