#
# makefile for caret.
#
#	Generated - on : 10/01/91
#	          - at : 05:51:39 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = caret.o

TARGET = $(DESTDIR)/caret

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
