#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2002/02/26 03:41:18 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2002/02/26 03:41:18  scott
#	First pass
#	
#	Revision 5.1  2001/07/25 02:18:44  scott
#	Update - LS10.5
#	
#
#

APP		=	sk_adel_inp
SRCS	=	sk_adel_inp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
