#
# makefile for sk_gl_eom.
#
#	Generated - on : 23/08/89
#	          - at : 11:30:34 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = sk_gl_eom.o

TARGET = $(DESTDIR)/sk_gl_eom

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
