#
# makefile for ml_sumrpt.
#
#	Generated - on : 22/11/91
#	          - at : 10:56:43 AM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = ml_sumrpt.o

TARGET = $(DESTDIR)/ml_sumrpt

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
