#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:32:34 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:32:34  scott
#	RELEASE 5.0
#	
#
#

APP		=	psl_default
SRCS	=	_default.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
