#
# makefile for sk_pricreat.
#
#	Generated - on : 16/11/89
#	          - at : 10:10:15 AM
#	          - by : rog
#

SHELL   = /bin/sh

OBJS = pricreat.o

TARGET = $(DESTDIR)/sk_pricreat

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
