#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:16 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:16  scott
#	Update - LS10.5
#	
#	Revision 4.1  2001/04/23 10:44:26  scott
#	Updated to add app.schema - removes code related to tables from program as it
#	allows for better quality contol.
#	Updated to perform routine maintenance to ensure standards are maintained.
#	Updated to remove usage of old include files
#	
#
#

APP		=	ol_audit
SRCS	=	ol_audit.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
