#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/07 07:21:54 kaarlo Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/07 07:21:54  kaarlo
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	cr_remtprn.t
SRCS	=	remtprn.i.c
ALTS	=	cr_remtprn.i

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
