#
# makefile for sk_marg.
#
#	Generated - on : 23/08/89
#	          - at : 11:34:52 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = sk_marg.o

TARGET = $(DESTDIR)/sk_marg

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
