#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/01/21 04:57:36 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/01/21 04:57:36  scott
#	Updated as first phase of contract management cleanup on it's way to becoming
#	useable for 3PL.
#	
#
#

APP		=	cm_wip_upd
SRCS	=	cm_wip_upd.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
