#
# makefile for sa_smancat.
#
#	Generated - on : 24/08/89
#	          - at : 11:58:56 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = sa_smancat.o

TARGET = $(DESTDIR)/sa_smancat

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
