#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 22:56:22 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 22:56:22  scott
#	RELEASE 5.0
#	
#
#

APP		=	cm_jtype_lst
SRCS	=	jtype_lst.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
