#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/06 08:06:19 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/06 08:06:19  scott
#	Updated for S/C 00037
#	
#
#

APP		=	db_lc_inp
ALTS	=	db_lc_dsp
SRCS	=	db_lc_inp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
