#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/15 03:12:20 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/15 03:12:20  scott
#	Cleaned up and added PID to arguments.
#	
#
#

APP		=	run_report
SRCS	=	run_report.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
