#
# makefile for so_roy_up.
#
#	Generated - on : 23/08/89
#	          - at : 11:55:27 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = so_roy_up.o

TARGET = $(DESTDIR)/so_roy_up

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
