#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:17:24 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:17:24  scott
#	Update - LS10.5
#	
#
#

APP		=	gl_allrept
SRCS	=	gl_allrept.c
ALTS	=	gl_allprnt gl_allrept.i

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
