#
# makefile for ol_upd.
#
#	Generated - on : 26/09/89
#	          - at : 09:32:01 AM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = ol_upd.o

TARGET = $(DESTDIR)/ol_upd

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
