#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2002/07/16 01:01:13 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2002/07/16 01:01:13  scott
#	Updated from service calls and general maintenance.
#	
#	Revision 5.1  2001/12/06 06:10:52  kaarlo
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP	=	cr_mr_delinp
SRCS	=	cr_mr_delinp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
