#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/06/26 06:32:33 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/06/26 06:32:33  scott
#	Updated to add SetSortArray () for new LS10-GUI screen features
#	
#
#

APP		=	ts_comp_mnt
SRCS	=	ts_comp_mnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
