#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/08/01 01:46:43 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/08/01 01:46:43  scott
#	.
#	
#
#

APP		=	tr_delmani
SRCS	=	tr_delmani.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
