#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2001/12/07 04:05:15 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2001/12/07 04:05:15  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#	Revision 5.1  2001/11/21 02:56:43  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_sk_maint
SRCS	=	db_sk_maint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
