#
# makefile for help_fn.
#
#	Generated - on : 23/08/89
#	          - at : 10:39:29 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = help_fn.o

TARGET = $(DESTDIR)/help_fn

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
