#
# makefile for cm_csthd_lst.
#
#	Generated - on : 15/04/93
#	          - at : 12:08:54 PM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = csthd_lst.o

TARGET = $(DESTDIR)/cm_csthd_lst

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
