#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/27 08:54:24 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/27 08:54:24  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	tot_db_cr
SRCS	=	tot_db_cr.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
