#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.1 2001/08/06 23:50:51 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:50:51  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:18:41  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:40:07  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:21:49  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 09:12:32  gerry
#	Forced Revision No Start 2.0 Rel-15072000
#	
#	Revision 1.2  2000/04/14 05:45:22  scott
#	S/C USL-16027 / LSDI-2559
#	Updated to improve performance. Phase one only, if further speed changes are to be made then internal sort routines would be required as well as index changes on files.
#	
#	
#	
APP		=	so_autorel
SRCS	=	so_autorel.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
