#
# makefile for tcap_test.
#
#	Generated - on : 18/01/91
#	          - at : 03:53:27 PM
#	          - by : camp
#

SHELL   = /bin/sh

OBJS = tcap_test.o

TARGET = $(DESTDIR)/tcap_test

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
