#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:32:19 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:32:19  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:08:16  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 1.1  2001/05/14 05:45:46  scott
#	New program to display XML errors.
#	
#
#

APP		=	dsp_xml_err
SRCS	=	dsp_xml_err.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
