#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:46:07 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:46:07  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:18:11  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:39:29  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/02/06 10:07:49  scott
#	Updated to deal with length change in the following fields
#	intr_ref1 from 10 to 15 characters
#	intr_ref2 from 10 to 15 characters
#	inaf_ref1 from 10 to 15 characters
#	inaf_ref2 from 10 to 15 characters
#	
#
#

APP		=	sk_trandel
SRCS	=	sk_trandel.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
