#
#	Standard application Makefile template
#
############################################
#
#		$Id: Makefile,v 5.0 2002/05/08 01:29:27 scott Exp $
#		$Log: Makefile,v $
#		Revision 5.0  2002/05/08 01:29:27  scott
#		CVS administration
#		
#		Revision 1.1  2001/08/14 03:03:48  scott
#		Updated for new delete wizard
#		
#		Revision 5.1  2001/08/06 23:21:58  scott
#		RELEASE 5.0
#		
#		Revision 5.0  2001/06/19 08:04:28  robert
#		LS10-5.0 New Release as of 19 JUNE 2001
#		
#		Revision 4.0  2001/03/09 02:24:55  scott
#		LS10-4.0 New Release as at 10th March 2001
#		
#		Revision 3.0  2000/10/10 12:13:44  gerry
#		Revision No. 3 Start
#		<after Rel-10102000>
#		
#		Revision 2.0  2000/07/15 08:52:27  gerry
#		Forced Revision No. Start 2.0 Rel-15072000
#		
#		Revision 1.2  2000/06/09 05:03:04  scott
#		S/C LSANZ 16397
#		Updated to add group purge option that existed in the LS/10 version before the
#		merger Pinnacle version.
#		Basically B/F and non-group purging is the same.
#		Transactions that are > 1st of month - number of days are not purged.
#		
#
#

APP		=	db_dpurge
SRCS	=	db_dpurge.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
