#
# makefile for cm_ytd_anal.
#
#	Generated - on : 23/04/93
#	          - at : 10:06:10 AM
#	          - by : jonc
#

SHELL   = /bin/sh

OBJS = ytd_anal.o

TARGET = $(DESTDIR)/cm_ytd_anal

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
