#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/05 01:40:42 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/05 01:40:42  scott
#	Updated from Testing.
#	
#
#

APP		=	sk_globmnt
SRCS	=	sk_globmnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
