#
# makefile for sa_catdisp.
#
#	Generated - on : 23/08/89
#	          - at : 11:17:13 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = sa_catdisp.o

TARGET = $(DESTDIR)/sa_catdisp

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
