#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:19:37 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:19:37  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:39:15  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2000/11/20 07:40:35  scott
#	New features related to 3PL environment
#	New features related to Number Plates
#	All covered in release 3 notes
#	
#
#

APP		=	sk_sup
SRCS	=	sk_sup.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
