#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.1 2001/07/25 02:18:50 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:50  scott
#	Update - LS10.5
#	
#	Revision 5.0  2001/06/19 08:15:04  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:36:32  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:19:47  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 09:10:23  gerry
#	Forced Revision No Start 2.0 Rel-15072000
#	
#	Revision 1.4  2000/06/13 05:02:45  scott
#	New Search routine that allow multi level searches using
#	Item number, description, Alpha code, alternate no, maker number, selling group,
#	buying group using AND or OR searches.
#	New search beings routines into the library to speed up GVision.
#	See seperate release notes.
#	
#	
OBJS = sk_alt_inp.o

APP		=	sk_alt_inp
ALTS	=	sk_alt_prn sk_alt_chk sk_syn_inp
SRCS	=	sk_alt_inp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
