#
# makefile for add_user.
#
#	Generated - on : 23/08/89
#	          - at : 10:42:35 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = add_user.o

TARGET = $(DESTDIR)/add_user

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
