#
# makefile for get_environ.
#
#	Generated - on : 23/08/89
#	          - at : 10:46:23 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = _environ.o

TARGET	= $(DESTDIR)/get_environ

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
