#
# makefile for run_format.
#
#	Generated - on : 23/08/89
#	          - at : 10:40:15 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = run_format.o

TARGET = $(DESTDIR)/run_format

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
