#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:17:29 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:17:29  scott
#	Update - LS10.5
#	
#
#

APP		=	gl_autoinp
SRCS	=	gl_autoinp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
