#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:32:35 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:32:35  scott
#	RELEASE 5.0
#	
#
#

APP		=	psl_gst_aud
SRCS	=	_gst_aud.c
ALTS	=	psl_gst_ret

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
