#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.0 2002/05/07 10:18:34 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.0  2002/05/07 10:18:34  scott
#	Updated to bring version number to 5.0
#	
#	Revision 1.1  2002/05/02 01:31:00  scott
#	New program for archiving
#	
#
#

APP		=	po_ar_disp
SRCS	=	po_ar_disp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
