#
# makefile for ms_lists.
#
#	Generated - on : 23/08/89
#	          - at : 10:47:05 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = ms_lists.o

TARGET = $(DESTDIR)/ms_lists

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
