#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:51 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:51  scott
#	Update - LS10.5
#	
#	Revision 5.0  2001/06/19 08:15:06  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:36:33  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:19:48  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/08/01 02:17:30  scott
#	General Maintenance - added app.schema
#	
#
#

APP		=	sk_bal_fix
SRCS	=	sk_bal_fix.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
