#
# makefile for ON.
#
#	Generated - on : 23/08/89
#	          - at : 10:38:17 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = ON.o

TARGET = $(DESTDIR)/ON

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
