#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.1 2001/07/25 02:19:50 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:19:50  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:40:13  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:21:52  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 09:12:36  gerry
#	Forced Revision No Start 2.0 Rel-15072000
#	
#	Revision 1.3  2000/02/09 04:20:27  scott
#	Updated to add app.schema code to make program easier to maintain.
#	Performed general cleanup that included additional costings.
#	
#	
APP		=	so_bgstkup
SRCS	=	so_bgstkup.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
