#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/08 00:59:29 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/08 00:59:29  scott
#	Updated to use app.schema
#	Updated to clean code and remove some VERY non standard database stuff.
#	
#
#

APP		=	rg_copy
SRCS	=	rg_copy.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
