#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:07 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:07  scott
#	Update - LS10.5
#	
#	Revision 5.0  2001/06/19 08:07:03  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/03/23 04:46:01  scott
#	Updated to add app.schema - removes code related to tables from program as it
#	allows for better quality contol.
#	Updated to add MoneyZero check before records (suspense ones) are added.
#	
#
#

APP		=	gl_wupdate
ALTS	= 	gl_eom_update gl_wupd_cr
SRCS	=	gl_wupdate.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
