#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:32:51 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:32:51  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:09:15  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/05/29 06:02:28  scott
#	Updated to add app.schema
#	Updated to include new validations for picking locations
#	
#
#

APP		=	wh_maint
SRCS	=	wh_maint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
