#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:45:14 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:45:14  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:16:17  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:37:36  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2000/11/20 07:40:09  scott
#	New features related to 3PL environment
#	New features related to Number Plates
#	All covered in release 3 notes
#	
#
#

APP		=	sk_locprn
ALTS	=	sk_locmprn sk_loc_dsp sk_loc_del
SRCS	=	sk_locprn.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
