#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2002/01/10 07:07:55 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2002/01/10 07:07:55  scott
#	Updated as first phase of contract management cleanup on it's way to becoming
#	useable for 3PL.
#	
#	Revision 5.1  2001/10/09 22:34:23  scott
#	Updated from Scotts machine.
#	
#
#

APP		=	cm_emp_inpt
SRCS	=	cm_emp_inpt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
