#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:45:25 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:45:25  scott
#	RELEASE 5.0
#	
#
#

APP		=	sk_note_pad
SRCS	=	note_pad.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
