#
# makefile for dsp_environ.
#
#	Generated - on : 23/08/89
#	          - at : 10:44:58 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = _environ.o

TARGET = $(DESTDIR)/dsp_environ

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
