#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:35:05 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:35:05  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:10:25  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:31:34  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:17:07  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 09:03:14  gerry
#	forced Revision no start 2.0 Rel-15072000
#	
#	Revision 1.2  2000/07/14 02:35:53  scott
#	Updated as general maintenance to add app.schema and correct item search.
#	
#
#

APP		=	pc_stdprt
SRCS	=	pc_stdprt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
