#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/14 07:53:18 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/14 07:53:18  scott
#	Updated to convert to app.schema
#	
#
#

APP		=	tm_lett_prt
SRCS	=	lett_prt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
