#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/06 02:38:49 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/06 02:38:49  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	cr_mend
SRCS	=	cr_mend.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
