#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:50:50 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:50:50  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:18:38  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 1.1  2001/04/21 03:50:53  scott
#	New Program for XML delete of sales orders
#	
#
#

APP		=	so_autoSoDel
SRCS	=	so_autoSoDel.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
