#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:01:38 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:01:38  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:03:31  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:23:59  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/01/23 01:12:53  scott
#	Update to ensure these programs will work without change with LS10-GUI.
#	
#
#

APP		=	cr_para_asm
SRCS	=	para_asm.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
