#
# makefile for sa_sadf_prt.
#
#	Generated - on : 28/05/91
#	          - at : 02:30:30 PM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = sadf_prt.o

TARGET = $(DESTDIR)/sa_sadf_prt

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
