#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2001/12/07 03:29:12 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2001/12/07 03:29:12  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#	Revision 5.1  2001/07/25 02:17:01  scott
#	Update - LS10.5
#	
#
#

APP		=	db_bill_rev
SRCS	=	db_bill_rev.c
ALTS	=	db_fwd_rev

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
