#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:17:03 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:17:03  scott
#	Update - LS10.5
#	
#
#

APP		=	db_crc2rep
SRCS	=	db_crc2rep.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
