#
# makefile for so_fwd_rel.
#
#	Generated - on : 23/08/89
#	          - at : 11:39:13 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = so_fwd_rel.o

TARGET = $(DESTDIR)/so_fwd_rel

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
