#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/03/01 01:48:45 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/03/01 01:48:45  scott
#	Added app.schema + general clean of code.
#	
#
#

APP		=	ca_tran_enq
SRCS	=	ca_tran_enq.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
