#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:51:00 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:51:00  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:19:02  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:40:24  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:21:58  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 09:12:42  gerry
#	Forced Revision No Start 2.0 Rel-15072000
#	
#	Revision 1.2  2000/07/14 04:53:55  scott
#	General maintenance to use app.schema and standard item search.
#	
#
#

APP		=	so_byitemprt
SRCS	=	byitemprt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
