#
# makefile for bg_ctrl.
#
#	Generated - on : 23/08/89
#	          - at : 11:06:42 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = bg_ctrl.o

TARGET = $(DESTDIR)/bg_ctrl

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
