#
# makefile for bm_wuse_prt.
#
#	Generated - on : 03/02/92
#	          - at : 03:32:05 PM
#	          - by : trev
#

SHELL   = /bin/sh

OBJS = wuse_prt.o

TARGET = $(DESTDIR)/bm_wuse_prt

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
