#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/22 02:52:07 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/22 02:52:07  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_cn_prt
SRCS	=	db_cn_prt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
