#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/06/03 08:22:10 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/06/03 08:22:10  scott
#	Updated to remove sort functions
#	Updated to convert to app.schema
#	
#
#

APP		=	bm_undefprt
SRCS	=	bm_undefprt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
