#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/26 06:35:14 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/26 06:35:14  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_rtype_inp
SRCS	=	db_rtype_inp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
