#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/03/07 07:27:32 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/03/07 07:27:32  scott
#	S/C 830
#	
#
#

APP		=	rg_print
SRCS	=	rg_print.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
