#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:53:45 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:53:45  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:21:29  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:42:47  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 1.1  2000/12/11 06:24:57  scott
#	New Program taken from Ben Foods (once cleaned and make to shine)
#	
#
#

APP		=	tr_adel_conf
SRCS	=	tr_adel_conf.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
