#
# makefile for setmode.
#
#	Generated - on : 05/03/92
#	          - at : 08:35:34 AM
#	          - by : trev
#

SHELL   = /bin/sh

OBJS = setmode.o

TARGET = $(DESTDIR)/setmode

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
