#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:25:54 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:25:54  scott
#	RELEASE 5.0
#	
#
#

APP		=	fa_maint
SRCS	=	fa_maint.c
ALTS	=	fa_display

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
