#
# makefile for bm_muse_prt.
#
#	Generated - on : 03/02/92
#	          - at : 03:08:30 PM
#	          - by : trev
#

SHELL   = /bin/sh

OBJS = muse_prt.o

TARGET = $(DESTDIR)/bm_muse_prt

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
