#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:45:26 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:45:26  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:16:49  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:38:10  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:20:45  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/08/15 07:56:06  scott
#	Updated to add app.schema and perform general cleanup.
#	Program will form base for sk_st_rfinp.c (RF stock take input)
#	
#
#

APP		=	sk_nst_fix
SRCS	=	sk_nst_fix.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
