#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:06 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:06  scott
#	Update - LS10.5
#	
#
#

APP		=	gl_wjnlprnt
SRCS	=	wjnlprnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
