#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:45:57 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:45:57  scott
#	RELEASE 5.0
#	
#
#

APP		=	sk_st_sprt
SRCS	=	sk_st_sprt.c
ALTS	=	sk_st_ssprt

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
