#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:19:08 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:19:08  scott
#	Update - LS10.5
#	
#
#

APP		=	sk_inoi_inp
ALTS	=	sk_inoi_dsp sk_inoi_stk
SRCS	=	inoi_inp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
