#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/10/23 08:18:07 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/10/23 08:18:07  scott
#	Updated to check and correct rounding.
#	Changes to ensure ALL inputs and reports round the same way.
#	
#
#

APP		=	so_sal_log
SRCS	=	so_sal_log.c
ALTS	=	so_ssal_log

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
