#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/02/26 04:57:11 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/02/26 04:57:11  scott
#	S/C-00736
#	SKPI10-3-Supplier Buying Group Assignment; the Start Date is truncated.
#	
#
#

APP		=	sk_supreass
SRCS	=	sk_supreass.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
