#
# makefile for gen_lineno.
#
#	Generated - on : 24/04/2000
#	          - at : 10:46:23 PM
#	          - by : jinno
#

SHELL   = /bin/sh

OBJS = gen_lineno.o

TARGET	= $(DESTDIR)/gen_lineno

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
