#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:51:34 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:51:34  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:20:10  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:41:27  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/03/06 09:26:08  scott
#	Updated to allow -ve discounts to be processed.
#	Problem with this was test on inmr_disc_pc should have been applied
#	only when inmr_disc_pc had a value.
#	
#
#

APP		=	so_overide
SRCS	=	so_overide.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
