#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2001/12/07 04:06:43 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2001/12/07 04:06:43  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#	Revision 5.1  2001/07/25 02:17:18  scott
#	Update - LS10.5
#	
#	Revision 5.0  2001/06/19 08:05:37  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/06/04 07:00:55  scott
#	Updated to use  app.schema
#	Updated to ensure defaults are correct
#	General clean up
#	Updated to fix mask for sort file as was %.2f and should have been %f
#	
#
#

APP		=	db_winvtogl
SRCS	=	db_winvtogl.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
