#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/14 07:13:31 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/14 07:13:31  scott
#	Updated to convert to app.schema
#	
#
#

APP		=	tm_lett_mnt
SRCS	=	lett_mnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
