#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/06 08:17:06 kaarlo Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/06 08:17:06  kaarlo
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	cr_dpurge
SRCS	=	cr_dpurge.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
