#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2002/03/11 08:39:54 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2002/03/11 08:39:54  scott
#	Updated to remove disk based sort.
#	
#	Revision 5.1  2001/08/07 00:06:41  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:13:43  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/03/21 07:41:15  scott
#	Updated to remove dsp_process and dsp_screen as goes mad with LS10-GUI.
#	Updated to add app.schema and some clean up.
#	
#
#

APP		=	sa_sadf_dsp
SRCS	=	sa_sadf_dsp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
