#
# makefile for pc_wcmaint.
#
#	Generated - on : 24/08/89
#	          - at : 10:16:37 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = pc_wcmaint.o

TARGET = $(DESTDIR)/pc_wcmaint

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
