#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:35:22 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:35:22  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:10:41  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:31:46  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/01/25 00:46:20  scott
#	Updated to remove changed made by NZ regarding names pipe stuff.
#	Does not work with LS10-GUI and is very non standard.
#	
#
#

APP		=	pc_womaint
SRCS	=	pc_womaint.c
ALTS	=	pc_relmaint

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
