#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/10/19 03:11:58 francis Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/10/19 03:11:58  francis
#	Made use of the new makefile.
#	
#
#

APP		=	tr_trcm_inp
SRCS	=	trcm_inp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
