#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:32:09 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:32:09  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:07:58  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:29:16  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/03/01 23:56:02  scott
#	Updated to place sleep on error message that company is not on file.
#	Updated to add app.schema and clean code.
#	
#
#

APP		=	br_maint
SRCS	=	br_maint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
