/*=====================================================================
|  Copyright (C) 1999 - 2000 LogisticSoftware                         |
|=====================================================================|
| $Id: CountryInfo.h,v 5.0 2001/06/19 06:51:15 cha Exp $
-----------------------------------------------------------------------
| $Log: CountryInfo.h,v $
| Revision 5.0  2001/06/19 06:51:15  cha
| LS10-5.0 New Release as of 19 JUNE 2001
|
| Revision 4.0  2001/03/09 00:59:19  scott
| LS10-4.0 New Release as at 10th March 2001
|
| Revision 3.3  2001/01/11 04:39:24  scott
| Final changes to CountryInfo.h
|
| Revision 3.2  2001/01/10 03:54:40  scott
| Updated after QA
|
|
*/
#ifndef	_countryInfo_h
#define	_countryInfo_h

	struct
	{
		char	*countryCode;
		char	*countryDesc;
	}	countryInfo []	=	
		{
			{"AF", "Afghanistan"},
			{"AL", "Albania"},
			{"DZ", "Algeria"},
			{"AS", "American Samoa"},
			{"AD", "Andorra"},
			{"AO", "Angola"},
			{"AI", "Anguilla"},
			{"AQ", "Antarctica"},
			{"AG", "Antigua and Barbuda"},
			{"AR", "Argentina"},
			{"AM", "Armenia"},
			{"AW", "Aruba"},
			{"AU", "Australia"},
			{"AT", "Austria"},
			{"AZ", "Azerbaijan"},
			{"BS", "Bahamas"},
			{"BH", "Bahrain"},
			{"BD", "Bangladesh"},
			{"BB", "Barbados"},
			{"BY", "Belarus (formerly known as Byelorussia)"},
			{"BE", "Belgium"},
			{"BZ", "Belize"},
			{"BJ", "Benin"},
			{"BM", "Bermuda"},
			{"BT", "Bhutan"},
			{"BO", "Bolivia"},
			{"BA", "Bosnia & Herzegowina"},
			{"BW", "Botswana"},
			{"BV", "Bouvet Island"},
			{"BR", "Brazil"},
			{"IO", "British Indian Ocean Territory"},
			{"BN", "Brunei Darussalam"},
			{"BG", "Bulgaria"},
			{"BF", "Burkina Faso"},
			{"BI", "Burundi"},
			{"KH", "Cambodia (formerly Kampuchea)"},
			{"CM", "Cameroon"},
			{"CA", "Canada"},
			{"CV", "Cape Verde"},
			{"KY", "Cayman Islands"},
			{"CF", "Central African Republic"},
			{"TD", "Chad"},
			{"CL", "Chili"},
			{"CN", "China"},
			{"CX", "Christmas Island"},
			{"CC", "Cocos (Keeling) Islands"},
			{"CO", "Colombia"},
			{"KM", "Comoros"},
			{"CG", "Congo"},
			{"CK", "Cook Islands"},
			{"CR", "Costa Rica"},
			{"HR", "Croatia"},
			{"CU", "Cuba"},
			{"CY", "Cyprus"},
			{"CZ", "Czech Republic"},
			{"DK", "Denmark"},
			{"DJ", "Djibouti"},
			{"DM", "Dominica"},
			{"DO", "Dominican Republic"},
			{"TP", "East Timor"},
			{"EC", "Ecuador"},
			{"EG", "Egypt"},
			{"SV", "El Salvador"},
			{"GQ", "Equatorial Guinea"},
			{"ER", "Eritrea"},
			{"EE", "Estonia"},
			{"ET", "Ethiopia"},
			{"EU", "European Community"},
			{"FK", "Falkland Islands (Malvinas)"},
			{"FO", "Faroe Islands"},
			{"FJ", "Fiji Islands"},
			{"FI", "Finland"},
			{"FR", "France"},
			{"FX", "France, Metropolitan"},
			{"GF", "French Guiana"},
			{"PF", "French Polynesia"},
			{"TF", "French Southern and Antarctic Territorie"},
			{"GA", "Gabon"},
			{"GM", "Gambia"},
			{"GE", "Georgia"},
			{"DE", "Germany (West and East)"},
			{"GH", "Ghana"},
			{"GI", "Gibraltar"},
			{"GR", "Greece"},
			{"GL", "Greenland"},
			{"GD", "Grenada"},
			{"GP", "Guadeloupe"},
			{"GU", "Guam"},
			{"GT", "Guatemala"},
			{"GN", "Guinea"},
			{"GW", "Guinea-Bissau"},
			{"GY", "Guyana"},
			{"HT", "Haiti"},
			{"HM", "Heard and McDonald Islands"},
			{"VA", "Vatican City State"},
			{"HN", "Honduras"},
			{"HK", "Hong Kong"},
			{"HU", "Hungary"},
			{"IS", "Iceland"},
			{"IN", "India"},
			{"ID", "Indonesia"},
			{"IR", "Iran, Islamic Republic of"},
			{"IQ", "Iraq"},
			{"IE", "Ireland"},
			{"IL", "Israel"},
			{"IT", "Italy"},
			{"CI", "Ivory Coast"},
			{"JM", "Jamaica"},
			{"JP", "Japan"},
			{"JO", "Jordan"},
			{"KZ", "Kazakhstan"},
			{"KE", "Kenya"},
			{"KI", "Kiribati"},
			{"KP", "Korea, Democratic People's Republic of"},
			{"KR", "Korea, Republic of (South Korea)"},
			{"KW", "Kuwait"},
			{"KG", "Kyrgyzstan"},
			{"LA", "Lao People's Democratic Republic"},
			{"LAT","Latvia"},
			{"LB", "Lebanon"},
			{"LS", "Lesotho"},
			{"LR", "Liberia"},
			{"LY", "Libyan Arab Jamahiriya"},
			{"LI", "Liechtenstein"},
			{"LT", "Lithuania"},
			{"LU", "Luxembourg"},
			{"MO", "Macao (also spelled Macau)"},
			{"MK", "Macedonia, the Former Yugoslav Republic"},
			{"MG", "Madagascar"},
			{"MW", "Malawi"},
			{"MY", "Malaysia"},
			{"MV", "Maldives"},
			{"ML", "Mali"},
			{"MT", "Malta"},
			{"Se", "Malvinas"},
			{"MH", "Marshall Islands"},
			{"MQ", "Martinique"},
			{"MR", "Mauritania"},
			{"MU", "Mauritius"},
			{"YT", "Mayotte"},
			{"MX", "Mexico"},
			{"FM", "Micronesia, Federated States of"},
			{"MD", "Moldova, Republic of"},
			{"MC", "Monaco"},
			{"MN", "Mongolia"},
			{"MS", "Montserrat"},
			{"MA", "Morocco"},
			{"MZ", "Mozambique"},
			{"MM", "Myanmar (formerly Burma)"},
			{"NA", "Namibia"},
			{"NR", "Nauru"},
			{"NP", "Nepal"},
			{"NL", "Netherlands"},
			{"AN", "Netherlands Antilles"},
			{"NC", "New Caledonia"},
			{"NZ", "New Zealand"},
			{"NI", "Nicaragua"},
			{"NE", "Niger"},
			{"NG", "Nigeria"},
			{"NU", "Niue"},
			{"NF", "Norfolk Island"},
			{"MP", "Northern Mariana Islands"},
			{"NO", "Norway"},
			{"OM", "Oman"},
			{"PK", "Pakistan"},
			{"PW", "Palau"},
			{"PA", "Panama"},
			{"PG", "Papua New Guinea"},
			{"PY", "Paraguay"},
			{"PE", "Peru"},
			{"PH", "Philippines"},
			{"PN", "Pitcairn Island"},
			{"PL", "Poland"},
			{"PT", "Portugal"},
			{"PR", "Puerto Rico"},
			{"QA", "Qatar"},
			{"RE", "Runion"},
			{"RO", "Romania"},
			{"RU", "Russian Federation"},
			{"RW", "Rwanda"},
			{"KN", "Saint Kitts (Christopher) and Nevis"},
			{"LC", "Saint Lucia"},
			{"VC", "Saint Vincent and the Grenadines"},
			{"WS", "Samoa"},
			{"SM", "San Marino"},
			{"SA", "Saudi Arabia"},
			{"SN", "Senegal"},
			{"SC", "Seychelles"},
			{"SL", "Sierra Leone"},
			{"SG", "Singapore"},
			{"SK", "Slovakia (Slovak Republic)"},
			{"SI", "Slovenia"},
			{"SB", "Solomon Islands"},
			{"SO", "Somalia"},
			{"ZA", "South Africa"},
			{"GS", "South Georgia and the South Sandwich Isl"},
			{"ES", "Spain"},
			{"LK", "Sri Lanka"},
			{"SH", "St Helena"},
			{"PM", "St Pierre and Miquelon"},
			{"SD", "Sudan"},
			{"SR", "Suriname"},
			{"SJ", "Svalbard and Jan Mayen Islands"},
			{"SZ", "Swaziland"},
			{"SE", "Sweden"},
			{"CH", "Switzerland"},
			{"SY", "Syrian Arab Republic"},
			{"TW", "Taiwan, Province of China"},
			{"TJ", "Tajikistan"},
			{"TZ", "Tanzania, United Republic of"},
			{"TH", "Thailand"},
			{"TG", "Togo"},
			{"TK", "Tokelau"},
			{"TO", "Tonga"},
			{"TT", "Trinidad and Tobago"},
			{"TN", "Tunisia"},
			{"TR", "Turkey"},
			{"TM", "Turkmenistan"},
			{"TC", "Turks and Caicos Islands"},
			{"TV", "Tuvalu"},
			{"UG", "Uganda"},
			{"UA", "Ukraine"},
			{"SU", "Union of Soviet Socialist Republics"},
			{"AE", "United Arab Emirates"},
			{"GB", "United Kingdom"},
			{"US", "United States of America"},
			{"UM", "United States Minor Outlying Islands"},
			{"UY", "Uruguay"},
			{"UZ", "Uzbekistan"},
			{"VU", "Vanautu"},
			{"VE", "Venezuela"},
			{"VN", "Viet Nam"},
			{"VG", "Virgin Islands (British)"},
			{"VI", "Virgin Islands (US)"},
			{"WF", "Wallis and Futuna Islands"},
			{"XO", "West Africa"},
			{"EH", "Western Sahara"},
			{"YE", "Yemen"},
			{"YU", "Yugoslavia"},
			{"ZM", "Zambia"},
			{"ZW", "Zimbabwe"},
			{"", ""}
		};
#endif	/*	_countryInfo_h */
