/*
 *	error codes and message text for INFORMIX
 *
*/

struct  {
	int	code;
	char	*msg;
} error_codes[] ={
	{-1,	"internal error"},
	{100,	"ISAM duplicate add to index"},
	{101,	"ISAM file not previously opened"},
	{102,	"ISAM call arguments not within acceptable range."},
	{103,	"ISAM key element(s) not within acceptable range."},
	{104,	"ISAM maximum number of files reached"},
	{105,	"ISAM format of file corrupted"},
	{106,	"ISAM add/delete index without exclusive access"},
	{107,	"ISAM record locked by another process"},
	{108,	"ISAM attempt to add index previously defined"},
	{109,	"ISAM attempt to delete primary key value"},
	{110,	"ISAM begining or end of file reached"},
	{111,	"ISAM no match for requested value"},
	{112,	"ISAM no current record to Update/Delete."},
	{113,	"ISAM file locked by another process"},
	{114,	"ISAM file name is to long."},
	{115,	"ISAM The lock file cannot be created."},
	{116,	"ISAM adequate memory cannot be Allocated."},
	{117,	"ISAM Bad custom collating."},
	{118,	"ISAM cannot read log file record."},
	{119,	"ISAM cannot recognise log file format."},
	{120,	"ISAM cannot open transaction log file."},
	{121,	"ISAM cannot write to transaction log file."},
	{122,	"ISAM Not in Transaction."},
	{123,	"ISAM No Shared Memory."},
	{124,	"ISAM Beginning of transaction not found."},
	{125,	"ISAM Cannot use network file server."},
	{126,	"ISAM Bad record number."},
	{127,	"ISAM No Primary Key."},
	{128,	"ISAM No Logging."},
	{129,	"ISAM Too Many users."},
	{130,	"ISAM Dbspace not found."},
	{131,	"ISAM No Free Disk space."},
	{132,	"ISAM Record to long."},
	{133,	"ISAM Audit trail exists."},
	{134,	"ISAM No More Locks."},
	{6000,	"tried to close an unopened file or database"},
	{6001,	"the database or file does not exist"},
	{6002,	"tried to open more than one database"},
	{6003,	"tried to open more than five files"},
	{6004,	"tried to open a file when no database was open"},
	{6005,	"a field cannot be found"},
	{6006,	"filename has not been opened"},
	{6007,	"field name cannot be found in current file"},
	{6008,	"file has not been opened (DBSELFIELD)"},
	{6009,	"no data in the file"},
	{6010,	"value cannot be found"},
	{6011,	"end of file"},
	{6012,	"beginning of file"},
	{6014,	"no such flag value"},
	{6015,	"filename has not be opened (DBFIND)"},
	{6016,	"no view has been set (DBFIND)"},
	{6017,	"can't add a duplicate value (no dups option) (DBADD)"},
	{6018,	"filename has not been opened (DBADD)"},
	{6019,	"no view has been set (DBADD)"},
	{6020,	"no current record (DBUPDATE,DBDELETE)"},
	{6021,	"filename has not been opened (DBDELETE)"},
	{6022,	"lock denied - deadlock avoidance"},
	{6023,	"filename has not been opened (DBLOCK)"},
	{6024,	"the number of fields may not exceed 100"},
	{6025,	"tried to open a file more than once"},
	{6026,	"field must be keyed or chronological is to be selected"},
	{6027,	"filename has not been locked"},
	{6028,	"filename has not been opened (DBUPDATE)"},
	{6029,	"no view has been set"},
	{6030,	"can't add a duplicate value (no dups option) (DBUPATE)"},
	{6031,	"no field has been selected"},
	{6032,	"User Does Not Have INFORMIX permission to add records"},
	{6035,	"no current record (DBFIND)"},
	{6036,	"newname already exists (DBALIAS)"},
	{6037,	"newname already used as alias (DBALIAS)"},
	{6038,	"cannot alias an alias (DBALIAS)"},
	{6040,	"cannot find oldname in database (DBALIAS)"},
	{6041,	"field_no > number of fields in file (DBNFIELD)"},
	{6043,	"field is not composite (DBNCOMPOSITE)"},
	{6044,	"ncomp > number of composites parts to field (DBNCOMPOSITE)"},
	{6045,	"Access permission denied"},
	{6046,	"File not opened exclusively"},
	{6047,	"Index Already exists"},
	{6048,	"Duplicate found when adding no dups index"},
	{6049,	"User does not have control access"},
	{6050,	"Bad Key description"},
	{6051,	"Composite field names are not allowed in DBVIEW"},
	{6052,	"Not all of the composite is in the current view"},
	{0,	"command excecuted successfully"}
};
