/*=====================================================================
|  Copyright (C) 1999 - 2000 LogisticSoftware                         |
|=====================================================================|
| $Id: ml_cr_mess.h,v 5.1 2001/08/06 22:49:52 scott Exp $
|----------------------------------------------------------------------
| $Log: ml_cr_mess.h,v $
| Revision 5.1  2001/08/06 22:49:52  scott
| RELEASE 5.0
|
| Revision 5.0  2001/06/19 06:51:31  cha
| LS10-5.0 New Release as of 19 JUNE 2001
|
| Revision 4.0  2001/03/09 00:59:25  scott
| LS10-4.0 New Release as at 10th March 2001
|
| Revision 3.1  2000/12/12 04:50:02  scott
| Updated to place strings back into include file so plook and other utils work
|
=====================================================================*/
#ifndef	ML_CR_MESS_H
#define	ML_CR_MESS_H

char	*mlCrMess001 = "No cheques found for Supplier.",
		*mlCrMess002 = "Usage: %s <lpno> [optional-PID]",
		*mlCrMess003 = "Usage: %s <lpno> <C(mpny),B(rnch)> <L(cal),O(vrseas)> <AZZ,CUR(rency)> ",
		*mlCrMess004 = "Letter %s is not on file",
		*mlCrMess005 = "Usage: %s <Letter Code> <Start Supplier> <End Supplier> <lpno> ",
		*mlCrMess006 = "There are only %d printers in this system.",
		*mlCrMess007 = "Updating cheque history with presented cheques.",
		*mlCrMess008 = "No unpresented cheques exist.",
		*mlCrMess009 = "Suppliers presented cheque flagging",
		*mlCrMess010 = "Deleting suppliers transactions.",
		*mlCrMess011 = "Usage: %s <lpno> <C(mpny),B(rnch)> <L(cal),O(vrseas)> <AZZ,CUR(rency)> <D(et),S(um)> <I(nv Age),P(ayment Age)> ",
		*mlCrMess012 = "Processing suppliers ageing schedule.",
		*mlCrMess013 = "Unable to find journal control record.",
		*mlCrMess014 = "Usage: %s <lpno> <pid> <ic_type=I/C>",
		*mlCrMess015 = "Usage: %s <pid> <lpno>",
		*mlCrMess016 = "Error processing cr_suwk workfile",
		*mlCrMess017 = "Cheque Stationery Loaded [Y/N]?",
		*mlCrMess018 = "Remittance Stationery Loaded [Y/N]?",
		*mlCrMess019 = "Reprint Document for Lineup [Y/N]?",
		*mlCrMess020 = "********** PRINT RUN STARTED **********",
		*mlCrMess021 = "********** DOCUMENTS ARE LINED UP **********",
		*mlCrMess022 = "Supplier %s has payments held set.",
		*mlCrMess023 = "Cannot select.  Invoice payment amount equals 0.00.",
		*mlCrMess024 = "Total payment selected: %.2f ",
		*mlCrMess025 = "Last Supplier: %s",
		*mlCrMess026 = "Supplier Document Payment Selection",
		*mlCrMess027 = "Closing Supplier Ledgers for %s",
		*mlCrMess028 = "Print Cash Commitments by Currency",
		*mlCrMess029 = "Supplier %s has already been entered for deletion.",
		*mlCrMess030 = "Supplier Master File Deletion",
		*mlCrMess031 = "List Unapproved Invoices by Supplier",
		*mlCrMess032 = "Document %s is not on file for Supplier.",
		*mlCrMess033 = "Document currency %s is not the same as for Supplier.",
		*mlCrMess034 = "To Date cannot precede From Date.",
		*mlCrMess035 = "Invoice/Credit Note Exchange Rate Amendment",
		*mlCrMess036 = "Supplier Cheque Number Input",
		*mlCrMess037 = "Account: %-66.66s",
		*mlCrMess038 = "Sundry Cheques Input",
		*mlCrMess039 = "Batch Total = %8.2f",
		*mlCrMess040 = "Account %s is Not in General Ledger Master File.",
		*mlCrMess041 = "G/L Alloc Total of %-8.2f Must Equal Cheq Amount %-8.2f.",
		*mlCrMess042 = "Balance to allocate: %.2f",
		*mlCrMess043 = "Last Inv/Cn: %s",
		*mlCrMess044 = "Nett Amount Outstanding: (%s) %.2f (%s) %.2f",
		*mlCrMess045 = "Nett Amount Outstanding: %.2f (%s)",
		*mlCrMess046 = "Payments to suppliers are being held.",
		*mlCrMess047 = "Supplier is not selected for payment.",
		*mlCrMess048 = "Existing cheque has date less than current month.",
		*mlCrMess049 = "Re-selecting invoices for payment.",
		*mlCrMess050 = "Invoice/Credit not found. Add [Y/N]?",
		*mlCrMess051 = "Invoice date exceeds supplier's cutoff date.",
		*mlCrMess052 = "Invoice has not been approved for payment.",
		*mlCrMess053 = "Bank does not exist for cheque.",
		*mlCrMess054 = "Cheque on file for gross %.2f.",
		*mlCrMess055 = "Total Amount Unallocated:  %8.2f.",
		*mlCrMess056 = "Total Cheque Amount %8.2f.",
		*mlCrMess057 = "%8.2f will remain unallocated.  Is this correct [Y/N]?.",
		*mlCrMess058 = "Total cheque amount (%s) %8.2f must equal allocation amount. %8.2f.",
		*mlCrMess059 = "Local cheque amount %8.2f must equal local allocation amount. %8.2f.",
		*mlCrMess060 = "Suppliers Payments",
		*mlCrMess061 = "Suppliers Payments (Journal Only)",
		*mlCrMess062 = "Last Cheque: %s/%s",
		*mlCrMess063 = "Allocate Unallocated Cheque",
		*mlCrMess064 = "Supplier has balance owing.",
		*mlCrMess065 = "Supplier has invoices on file",
		*mlCrMess066 = "Name:   %s %s",
		*mlCrMess067 = "Invoice ratio incorrect, Invoice = %d",
		*mlCrMess068 = "This will be a forward cheque. Are you sure [Y/N]?",
		*mlCrMess069 = "Do you want to cancel further forward cheque messages [Y/N]?",
		*mlCrMess070 = "Input I(nvoice) C(redit)?",
		*mlCrMess071 = "Usage: %s lpno <F/S> <B/C> <A/N> <start> <end> <A/C/D/T>",
		*mlCrMess072 = "Suppliers Transactions Display",
		*mlCrMess073 = "Paragraph Input",
		*mlCrMess074 = "Usage: %s <ic_type=I/C> <pid>",
		*mlCrMess075 = "Invoice/Credit is already approved.",
		*mlCrMess076 = "Credit with same number is already on file.",
		*mlCrMess077 = "Invoice with same number is already on file.",
		*mlCrMess078 = "Transaction is not an invoice/credit.",
		*mlCrMess079 = "Purchase order must be approved first.",
		*mlCrMess080 = "Purchase order cannot be receipted as it does not have correct status.",
		*mlCrMess081 = "Invoice/Credit may not be entered for quick purchase order.",
		*mlCrMess082 = "Invoice/Credit may not be entered for proforma purchase order.",
		*mlCrMess083 = "Shipment for purchase order has not yet been despatch confirmed. Confirm now [Y/N]?",
		*mlCrMess084 = "No goods have been receipted for the purchase order.",
		*mlCrMess085 = "Direct Delivery Goods Receipt must be matched via the Direct Delivery Shipment option.",
		*mlCrMess086 = "Direct Delivery Purchase Orders must be matched via the Direct Delivery Shipment option.",
		*mlCrMess087 = "Direct Delivery Shipments must be matched via the Direct Delivery Shipment option.",
		*mlCrMess088 = "This document has been partially costed. Remaining balance is %9.2f.",
		*mlCrMess089 = "This document has already been costed. Continue [Y/N]?",
		*mlCrMess090 = "%-3.3s amount [%-.2f] is not [%-.2f] of total.",
		*mlCrMess091 = "Proof Total %-8.2f unequal to invoice total %-8.2f.",
		*mlCrMess092 = "Invoice/Credit may not be entered for direct delivery purchase order.",
		*mlCrMess093 = "Invoice/Credit may not be entered for quick purchase order.",
		*mlCrMess094 = "Invoice/Credit may not be entered for direct delivery GRN.",
		*mlCrMess095 = "G/L total of %-8.2f must equal nett inv/crd total %-8.2f.",
		*mlCrMess096 = "Shipment has not yet been despatch confirmed.",
		*mlCrMess097 = "Invoice is on file for gross %-8.2f.",
		*mlCrMess098 = "Credit is on file for gross %-8.2f.",
		*mlCrMess099 = "Supplier Invoice Input",
		*mlCrMess100 = "Supplier Credit Note Input",
		*mlCrMess101 = "Document is not an invoice or credit.",
		*mlCrMess102 = "Payment %-14.2f exceeds balance due.",
		*mlCrMess103 = "Invoice Payment Amendment",
		*mlCrMess104 = "Invoice Due Date Amendment",
		*mlCrMess105 = "Last Invoice: %s",
		*mlCrMess106 = "Supplier Inv/Crd Setup Option",
		*mlCrMess107 = "Nett Amount Outstanding: (%s) %.2f   (%s) %.2f",
		*mlCrMess108 = "Multiple Tax Details",
		*mlCrMess109 = "Amount may not exceed Nett Amount less any previous allocations.",
		*mlCrMess110 = "Tax may not exceed amount.",
		*mlCrMess111 = "Tax total (%12.2f) is not within %5.2f %% of theoretical total (%12.2f).",
		*mlCrMess112 = "Journal with same number is already on file.",
		*mlCrMess113 = "Applied to number not found.",
		*mlCrMess114 = "Applied to number is on file but not approved.",
		*mlCrMess115 = "Journal Total must equal zero.",
		*mlCrMess116 = "Updating Journals ....",
		*mlCrMess117 = "Journal Total = %.2f",
		*mlCrMess118 = "Suppliers Journal Input",
		*mlCrMess119 = "Print Cash Commitments By Supplier",
		*mlCrMess120 = "Supplier Quality Assurance Report",
		*mlCrMess121 = "Usage: %s <Start Supplier> <End Supplier> <Start Status> <End Status> <lpno>",
		*mlCrMess122 = "Print Aged Balance Supplier's Report",
		*mlCrMess123 = "Duplicate Cheque Number",
		*mlCrMess124 = "Supplier Listing Selection",
		*mlCrMess125 = "You may not decrease the next lodgement number.",
		*mlCrMess126 = "Bank Control File Maintenance",
		*mlCrMess127 = "%R Bank Details",
		*mlCrMess128 = "Updating bank transfers.... ",
		*mlCrMess129 = "Bank Transfer Journal Input",
		*mlCrMess130 = "Program terminated : This option is only used for MULTI CURRENCY CREDITORS.",
		*mlCrMess131 = "Debug version.",
		*mlCrMess132 = "Now deleting paragraph record",
		*mlCrMess133 = "Assemble Supplier Letters",
		*mlCrMess134 = "Direct Credit Schedule",
		*mlCrMess135 = "Cheque Date less than Suppliers Date.",
		*mlCrMess136 = "Cheque Date greater than Cut-off Date.",
		*mlCrMess137 = "Reference Number already used.",
		*mlCrMess138 = "Usage: %s <lpno> <pid>",
		*mlCrMess139 = "Usage: %s <lpno> <Supplier Hash> <Voucher No>",
		*mlCrMess140 = "Remittance Print Selection",
		*mlCrMess141 = "Direct Delivery Purchase Orders must be processed through the Direct Delivery Shipment option.",
		*mlCrMess142 = "Normal Purchase Orders must be processed through the Purchase Order option.",
		*mlCrMess143 = "Invoice not approved.",
		*mlCrMess144 = "Proof Total incorrect.",
		*mlCrMess145 = "Cheque already exists.",
		*mlCrMess146 = "Deposit not found for this cheque.",
		*mlCrMess147 = "Deposit has been fully allocated.",
		*mlCrMess148 = "Program will only allow 800 invoices to be paid at once. Continuing.",
		*mlCrMess149 = "Any unallocated cash will be left against the initial deposit.",
		*mlCrMess150 = "Cheque does not exist.",
		*mlCrMess151 = "Cheque has been fully allocated.",
		*mlCrMess152 = "Program will only allow 500 invoices to be paid at once. Continuing.",
		*mlCrMess153 = "Do you wish to round local cheque amount by %4.2f to %8.2f [Y/N]?",
		*mlCrMess154 = "No goods have been receipted.",
		*mlCrMess155 = "Supplier Cheque Reprint Selection",
		*mlCrMess156 = "Letter  Display / Print",
		*mlCrMess157 = "Supplier Payment Selection",
		*mlCrMess158 = "Flagging Supplier %s cheques as unprinted.",
		*mlCrMess159 = "%R General Ledger Accounts",
		*mlCrMess160 = "%R Bank Currency Sell Rates",
		*mlCrMess161 = "Bank Code : %s (%s)",
		*mlCrMess162 = "********** REPRINTING **********",
		*mlCrMess163 = "Accounts Payable control account is not set up.",
		*mlCrMess164 = "Branch cannot be 0 as Suppliers are branch owned.",
		*mlCrMess165 = "Suppliers acronym must be input.",
		*mlCrMess166 = "Invalid day of month.",
		*mlCrMess167 = "Supplier Master Maintenance",
		*mlCrMess168 = "Account %s currency not equal to Supplier currency.",
		*mlCrMess169 = "GLWK file trans type does not equal journal type.",
		*mlCrMess170 = "Create and Print Supplier Cheques",
		*mlCrMess171 = "Cheque date greater than Supplier's date.",
		*mlCrMess172 = "General Ledger Journal about to be printed.",
		*mlCrMess173 = "Please select printer with lineflow paper loaded.",
		*mlCrMess174 = "Normal Purchase Orders must be processed through the Purchase Order receipt type.",
		*mlCrMess175 = "Shipment for purchase order has not yet been confirmed.",
		*mlCrMess176 = "No unapproved invoices could be found.",
		*mlCrMess177 = "A)uthorise all invoices / Q)uit",
		*mlCrMess178 = "A)uthorise all invoices / C)hange receipt type to normal / S)anction all invoices changing receipt type to normal / Q)uit",
		*mlCrMess179 = "Manual Invoice Approval Entry",
		*mlCrMess180 = "Option %s is not available with estimated costing.",
		*mlCrMess181 = "Are you sure you want to authorize all invoices [Y/N]?",
		*mlCrMess182 = "Are you sure you want to change receipt type to normal [Y/N]?",
		*mlCrMess183 = "Are you sure you want to sanction all invoices changing receipt type to normal [Y/N]?",
		*mlCrMess184 = "Processing Account Summary: %s",
		*mlCrMess185 = "Supplier has purchase orders on file.",
		*mlCrMess186 = "Supplier has cheque payments on file.",
		*mlCrMess187 = "Supplier has Inventory records on file.",
		*mlCrMess188 = "Sundry Disbursement %13.13s",
		*mlCrMess189 = "Supplier Quality Assurance Print",
		*mlCrMess190 = "Print Suppliers Ageing Schedule",
		*mlCrMess191 = "Supplier's Listings ",

		*mlCrMess700 = "Usage: %s <lpno> <pid> <xferdate> < refno> {A|N} <bankid> <rate>",
		*mlCrMess701 = "Usage: %s <pid> <C(heque | D(raft | T(ransfer> <History type 1-6>",
		*mlCrMess702 = "Usage: %s <lpno> <sort by, S(upplier No | C(heque No> < Reprint, Y | N> <start_cheq_no> <end_cheq_no> <cheque date>",
		*mlCrMess703 = "Usage: %s <lpno> <C(heque Listing | U(npresented Cheques | P(resented Cheques>",
		*mlCrMess704 = "Usage: %s <lpno> <pid>",
		*mlCrMess705 = "Supplier Cheque Listing Delete",
		*mlCrMess706 = "Cheque.";
#endif	
