/*=====================================================================
|  Copyright (C) 1999 - 2000 LogisticSoftware                         |
|=====================================================================|
| $Id: ml_cm_mess.h,v 5.1 2002/01/23 06:25:00 scott Exp $
|----------------------------------------------------------------------
| $Log: ml_cm_mess.h,v $
| Revision 5.1  2002/01/23 06:25:00  scott
| Updated as first phase of contract management cleanup on it's way to becoming
| useable for 3PL.
|
| Revision 5.0  2001/06/19 06:51:31  cha
| LS10-5.0 New Release as of 19 JUNE 2001
|
| Revision 4.0  2001/03/09 00:59:25  scott
| LS10-4.0 New Release as at 10th March 2001
|
| Revision 3.1  2000/12/12 04:50:02  scott
| Updated to place strings back into include file so plook and other utils work
|
=====================================================================*/
#ifndef	ML_CM_MESS_H
#define	ML_CM_MESS_H

char	*mlCmMess001 = "Equipment code not found.",
		*mlCmMess002 = "Employee name not found.",
		*mlCmMess003 = "Please re-select Range of Contracts as no valid invoices has been loaded.",
		*mlCmMess004 = "Invoice amount may not be greater than quoted value.",
		*mlCmMess005 = "Invoice amount may not be greater than remaining value.",
		*mlCmMess006 = "Start Contract Number should be less than last Contract Number.",
		*mlCmMess007 = "Contract not available for invoicing.",
		*mlCmMess008 = "Last Contract Number should be greater than first Contract Number.",
		*mlCmMess009 = "No invoices have been loaded.",
		*mlCmMess010 = "Contract Adjustment Journals",
		*mlCmMess011 = "Job type not found.",
		*mlCmMess012 = "Error occured in update of invoice.  Press any key.",
		*mlCmMess013 = "Invoice has not been previously printed.",
		*mlCmMess014 = "Issue To code not found.",
		*mlCmMess015 = "Requisition Number not found.",
		*mlCmMess016 = "Costhead not found.  Do you wish to add [Y/N]?",
		*mlCmMess017 = "Adjustment Journals may only be posted to a Fully Consolidated Costhead",
		*mlCmMess018 = "Contract is not OPEN.",
		*mlCmMess019 = "It is illegal to mix and match G/L A/C types on one journal.",
		*mlCmMess020 = "Contract description not found.",
		*mlCmMess021 = "Equipment description not found.",
		*mlCmMess022 = "Materials description not found.",
		*mlCmMess023 = "Contract may not be set to Status 'B' as requisitions are outstanding.",
		*mlCmMess024 = "Usage: %s <lpno> [day, 0-Sun, 1-Mon,...]",
		*mlCmMess025 = "WIP Status not found.",
		*mlCmMess026 = "Requisition number must be input as system is not set up for Automatic Numbering.",
		*mlCmMess027 = "Forward Requisition, Delay Release [Y/N]?",
		*mlCmMess028 = "No such serial number for item.",
		*mlCmMess029 = "Duplicate serial numbers.",
		*mlCmMess030 = "Requisition not created as no lines are present.",
		*mlCmMess031 = "Requisition not found.",
		*mlCmMess032 = "Requisition is not a forward order.",
		*mlCmMess033 = "No lines to release.",
		*mlCmMess034 = "Requisition has already been entered.",
		*mlCmMess035 = "Choice may only be E)mployee or C)ontract",
		*mlCmMess036 = "Labor Analysis Report",
		*mlCmMess037 = "Employee Maintenance",
		*mlCmMess038 = "Cost",
		*mlCmMess039 = "Charge Out",
		*mlCmMess040 = "Employees Master Listing",
		*mlCmMess041 = "Please confirm that date is older than two weeks [Y/N].",
		*mlCmMess042 = "Employee Timesheet Entry",
		*mlCmMess043 = "Proof Totals do not match",
		*mlCmMess044 = "Negative rate not allowed.",
		*mlCmMess045 = "Negative cost not allowed.",
		*mlCmMess046 = "Plant Rate Master File Maintenance",
		*mlCmMess047 = "%R Fixed Quote   ",
		*mlCmMess048 = "%R Progressive Billing",
		*mlCmMess049 = "%R Internal Contract",
		*mlCmMess050 = "%R External Contract",
		*mlCmMess051 = "%R Variable Quote",
		*mlCmMess052 = "%R Normal Billing     ",
		*mlCmMess053 = "%R Invoice Summary Report",
		*mlCmMess054 = "Invoice does not belong to a contract.",
		*mlCmMess055 = "Start %s",
		*mlCmMess056 = "End %s",
		*mlCmMess057 = "Index on file CUWK is bad, please run BCHECK.",
		*mlCmMess058 = "No %s account set up in the Control Accounts.",
		*mlCmMess059 = "Contracts WIP Status Update",
		*mlCmMess060 = "Journal Total = %-12.12f, must equal zero to update.",
		*mlCmMess061 = "Contract Status Enquiry",
		*mlCmMess062 = "Enter Print Details",
		*mlCmMess063 = "Values must be between 0 and 31.",
		*mlCmMess064 = "Anniversary Day Report",
		*mlCmMess065 = "%R Maintenance of Ongoing Contract Description",
		*mlCmMess066 = "Only status X contracts can be deleted.",
		*mlCmMess067 = "Customer     : %-6.6s %-40.40s   Order Reference: %-20.20s",
		*mlCmMess068 = "Plant Numbers Master Listing",
		*mlCmMess069 = "Contract Due Date  : %-10.10s",
		*mlCmMess070 = "Quote Type : %-8.8s",
		*mlCmMess071 = "Quote Value: %14.14s",
		*mlCmMess072 = "Selection of Contracts for Status Change",
		*mlCmMess073 = "%R Open Contracts Ready for Update",
		*mlCmMess074 = "No lines found for requisition.",
		*mlCmMess075 = "Warehouse not setup with correct picking information.",
		*mlCmMess076 = "Non-stock items cannot be requested.",
		*mlCmMess077 = "Requisition has been completed.",
		*mlCmMess078 = "Requisition Number (%06ld) created.",
		*mlCmMess079 = "Adding order detail lines.",
		*mlCmMess080 = "Deleting complete order.",
		*mlCmMess081 = "All lines are backordered.",
		*mlCmMess082 = "Requisition is on forward order.",
		*mlCmMess083 = "Requisition Entry",
		*mlCmMess084 = "%06ld is a full-supply requisition.",
		*mlCmMess085 = "Unable to supply %8.2f X %-16.16s.",
		*mlCmMess086 = "Confirm partial supply [Y/N]?",
		*mlCmMess087 = "Requisition %s Release",
		*mlCmMess088 = "Last Req.#: %s",
		*mlCmMess089 = "Requisition No. : NEW REQUISITION",
		*mlCmMess090 = "Requisition No. : %06ld",
		*mlCmMess091 = "Contract Number : %-6.6s",
		*mlCmMess092 = "CostHead Desc.  : ",
		*mlCmMess093 = "Item Description: ",
		*mlCmMess094 = "%R Printing Cost Sheet...",
		*mlCmMess095 = "Charge To      : %-6.6s %-30.30s",
		*mlCmMess096 = "Contact Name   : %-20.20s %-30.30s",
		*mlCmMess097 = "Job Type       : %-10.10s %-40.40s",
		*mlCmMess098 = "Issue To       : %-10.10s %-40.40s",
		*mlCmMess099 = "WIP Status     : %-10.10s %-40.40s",
		*mlCmMess100 = "WIP Date       : %-10.10s %-40.40s",
		*mlCmMess101 = "Analysis Codes : %s",
		*mlCmMess102 = "Contract Description",
		*mlCmMess103 = "Overriden Number already exists.",
		*mlCmMess104 = "Charge Address : %-40.40s  %-2.2s",
		*mlCmMess105 = "Employee Rates Master Listing",
		*mlCmMess106 = "%R Selection Of Contracts For Invoicing",
		*mlCmMess107 = "%R Prepare Invoices For Contracts",
		*mlCmMess108 = "%R [RESTART] [NEXT SCN]-Next Invoice [PREV SCN]-Previous Invoice [INPUT/END]-Process [CTRL-W]-Edit Charge Details",

		*mlCmMess109 = "%R Charge Details",
		*mlCmMess110 = "Do you wish to load existing charge details [Y/N]?",
		*mlCmMess111 = "%s No %s > %s (Maximum)",
		*mlCmMess112 = "%s Reprint Input",
		*mlCmMess113 = "%s Print Input",
		*mlCmMess114 = "Outstanding Contract Requisitions",
		*mlCmMess115 = "%R [END]",
		*mlCmMess116 = "Contract NLA",
		*mlCmMess117 = "Are you sure that you wish to abort [Y/N]?",

		*mlCmMess118 = "Issue To type has changed. Pleasecheck employee/Supplier Code.",
		*mlCmMess119 = "Issue To Maintenance",
		*mlCmMess120 = "Issue To Type",
		*mlCmMess121 = "Issue To Codes Master Listing",
		*mlCmMess122 = "Cost Head has already been entered.",
		*mlCmMess123 = "Job Type Maintenance",
		*mlCmMess124 = "General Ledger Accounts",
		*mlCmMess125 = "Cost Heads Selection",
		*mlCmMess126 = "G/L Accounts by Job Type Master File Listings",
		*mlCmMess127 = "Profit Margin is out of range. Please enter manually or change values.",
		*mlCmMess128 = "Not a valid day of month.",
		*mlCmMess129 = "Job Type may not be changed as transactions already exist.",
		*mlCmMess130 = "Job Type may not be changed as timesheet entries already exist.",
		*mlCmMess131 = "Error in loading of G/L Accounts.",
		*mlCmMess132 = "Master Contract Number may not be the same as current Contract Number.",
		*mlCmMess133 = "Master Contract Number not found.",
		*mlCmMess134 = "Environment set for user-selected Contract Number - Please enter number.",
		*mlCmMess135 = "This contract may not be maintained as it is at invoice stage.",
		*mlCmMess136 = "This contract may not be maintained as it is closed.",
		*mlCmMess137 = "Please note that this contract is held due to credit reasons.",

		*mlCmMess138 = "Existing budget information for costheads will be lost.  Continue [Y/N]?",
		*mlCmMess139 = "Customer not found. Do you wish to add [Y/N]?",
		*mlCmMess140 = "Enter 'Y' if Credit is approved, 'N' if unapproved, 'M' for more details on credit required [Y/N/M]?",
		*mlCmMess141 = "Has credit been approved [Y/N]?",
		*mlCmMess142 = "Contracts Master File Maintenance",
		*mlCmMess143 = "New Contract No. %6s created.",
		*mlCmMess144 = "Add number of days to Start Date.",
		*mlCmMess145 = "Requisition already complete.",
		*mlCmMess146 = "Selective Requisition Delete",
		*mlCmMess147 = "WIP Codes Master File Maintenance",
		*mlCmMess148 = "Requisition Reprint Input",
		*mlCmMess149 = "Start Requisition",
		*mlCmMess150 = "End Requisition",
		*mlCmMess151 = "Journal Total = $%.2f",
		*mlCmMess152 = "%s (O)verride%s  %s (C)ancel%s  %s (R)educe%s  %sDisp (N) (A) %s  ",
		*mlCmMess153 = "General Ledger Account code %s for %s is invalid.",
		*mlCmMess154 = "Contracts Master Listings",
		*mlCmMess155 = "Contracts Costheads And Budgets Setup",
		*mlCmMess156 = "Budget already exists.",
		*mlCmMess157 = "Costhead Maintenance",
		*mlCmMess158 = "Invalid Location on line %d. Please correct.",
		*mlCmMess159 = "Invalid serial item on line %d. Please add serial item.",
		*mlCmMess160 = "Invalid Lot no on line %d. Please correct.",
		*mlCmMess161 = "Qty Ordered was %8.2f and qty to be destpach is %8.2f. Is this correct [Y/N] ?",
		*mlCmMess162 = "Looping Supercession, Check Item %s",
		*mlCmMess163 = "Looping Alternate, Check Item %s",
		*mlCmMess164 = "Corrupt Supercession, Check Item %s",
		*mlCmMess165 = "Corrupt Alternate, Check Item %s",
		*mlCmMess166 = "Confirm complete order [Y/N] ?",
		*mlCmMess167 = "Requisition Despatch Confirmation",
		*mlCmMess168 = "Requisitions can not be despatched as all lines are forward ordered.",
		*mlCmMess169 = "Requisitions can not be despatched as all lines are backordered.",
		*mlCmMess170 = "All lines have been despatched.",
		*mlCmMess171 = "Error in loading requisition.",
		*mlCmMess172 = "Costhead Master File Listings",
		*mlCmMess173 = "Last Ref : %s",
		*mlCmMess174 = "Direct Issues To Contract",
		*mlCmMess175 = "%cOnly %8.2f on hand for Item %s and issue amount is %8.2f. Continue [Y/N] ?",
		*mlCmMess176 = "There is no extra description for this contract number.",
		*mlCmMess177 = "Item %s has master alternate item %s %c.",
		*mlCmMess178 = "Item %s has been superceeded by item %s %c.",
		*mlCmMess179 = "No warehouse record for issuing item %s.",
		*mlCmMess180 = "No branch record for item %s.",
		*mlCmMess181 = "Class Z (desciption items) cannot have a quantity.",
		*mlCmMess182 = "Phantom number is shown for reference only.",
		*mlCmMess183 = "Quantity ordered and quantity supplied are both zero.",
		*mlCmMess184 = "Serial number not yet receipted.",
		*mlCmMess185 = "Costhead %s is not set up on contract %s. Do you wish to add [Y/N]?",
		*mlCmMess186 = "%s(S)ubstitute%s  ",
		*mlCmMess187 = "%s(F)orce b/o%s  ",
		*mlCmMess188 = "%s(B)ackorder bal%s  %s(F)orce b/o%s ",
		*mlCmMess189 = "Tax Invoice Reprint Input",
		*mlCmMess190 = "Tax Invoice Print Input",
		*mlCmMess191 = "Credit Note Reprint Input",
		*mlCmMess192 = "Credit Note Print Input",
		*mlCmMess193 = "Start Tax Invoice",
		*mlCmMess194 = "End Tax Invoice",
		*mlCmMess195 = "Start Credit Note",
		*mlCmMess196 = "End Credit Note",
		*mlCmMess197 = "Costhead Desc.  :",
		*mlCmMess198 = "Requisition No : %4.4s      %s",
		*mlCmMess199 = "Work in Progress",
		*mlCmMess200 = "Labour Recovery ",
		*mlCmMess201 = "Overhead Recovery ",
		*mlCmMess202 = "Sales ",
		*mlCmMess203 = "Cost Of Sales ",
		*mlCmMess204 = "Variance ",
		*mlCmMess205 = "Internal ",

		*mlCmMess700 = "Usage : %s <description>",
		*mlCmMess701 = "   OR : %s <lpno>",
		*mlCmMess702 = "           <Report  Type - C(ontract)>",
		*mlCmMess703 = "                           E(mployee)>",
		*mlCmMess704 = "           <Include Internal (Y/N)>",
		*mlCmMess705 = "           <Start Date>",
		*mlCmMess706 = "           <End Date>",
		*mlCmMess707 = "           <Start Contract>",
		*mlCmMess708 = "           <End Contract>",
		*mlCmMess709 = "           <Start Job Type>",
		*mlCmMess710 = "           <End Job Type>",
		*mlCmMess711 = "           <Start Employee>",
		*mlCmMess712 = "           <End Employee>",
		*mlCmMess713 = "Usage : %s <description>",
		*mlCmMess714 = "   OR : %s <Start Job Type>",
		*mlCmMess715 = "<End Job Type>",
		*mlCmMess716 = "Usage : %s <pid> [C)heque|D)raft|T)ransfer] <History Type 1-6>",

		*mlCmMess717 = "Usage: %s <description>",
		*mlCmMess718 = "OR %s <start plant> <end plant> <lpno>",
		*mlCmMess719 = "OR %s <start employee> <end employee>",
		*mlCmMess720 = "OR %s <lpno> <start date> <end date> ",
		*mlCmMess721 = "             <start contract> <end contract>",
		*mlCmMess722 = "             <start job type> <end job type>",
		*mlCmMess723 = "Usage: %s <lpno> <optional-Branch>",

		*mlCmMess724 = "OR %s <lpno> <S(ummary),D(etailed)>",
		*mlCmMess725 = "      <C(ontract),J(ob Type),I(ssue To)>",
		*mlCmMess726 = "      <Internal (Y/N)> <Lower Bound> <Upper Bound>",
		*mlCmMess727 = "<lpno>",
		*mlCmMess728 = "Usage: %s <M(ultiple Contracts)> OR <S(ingle Contract)>",
		*mlCmMess729 = "Usage: %s <C)ontract|J)ob Type|I)ssue> <start code> <end code> <start anni> <end anni>  <D)etail|S)ummary> <lpno>",

		*mlCmMess730 = "      <S(ummary)> OR D(etail)>",
		*mlCmMess731 = "      <Report  Range - C(ontract)>",
		*mlCmMess732 = "                     - J(ob Type)>",
		*mlCmMess733 = "                     - I(ssue To)>",
		*mlCmMess734 = "                     - W(IP Status)>",
		*mlCmMess735 = "      <Internal (Y/N)>",
		*mlCmMess736 = "      <Lower Bound>",
		*mlCmMess737 = "      <Upper Bound>",
		*mlCmMess738 = "Usage: %s <requisition type (B/F)>",
		*mlCmMess739 = "      <by C)ontract, J)ob Type, I)ssue>",
		*mlCmMess740 = "Usage: %s <lpno> <reprint flag [Y/N]> <type [I/C]>",
		*mlCmMess741 = "OR     <start issue to code> <end issue to code> <lpno>",
		*mlCmMess742 = "OR     <start job type> <end job type> ",
		*mlCmMess743 = "<status> O)pen, C)lose, H)istory, A)ll>",
		*mlCmMess744 = "<sort_by> - C)ontracts or F)inish Dates>",
		*mlCmMess745 = " OR   : %s <start costhead>",
		*mlCmMess746 = "           <end costhead>",
		*mlCmMess747 = " OR    : %s <lpno> <hhrq_hash>",
		*mlCmMess748 = "Usage: %s <lpno>";
#endif	
