/*=====================================================================
|  Copyright (C) 1999 - 2000 LogisticSoftware                         |
|=====================================================================|
| $Id: ml_dd_mess.h,v 5.0 2001/06/19 06:51:32 cha Exp $
-----------------------------------------------------------------------
| $Log: ml_dd_mess.h,v $
| Revision 5.0  2001/06/19 06:51:32  cha
| LS10-5.0 New Release as of 19 JUNE 2001
|
| Revision 4.0  2001/03/09 00:59:25  scott
| LS10-4.0 New Release as at 10th March 2001
|
| Revision 3.1  2000/12/12 04:50:03  scott
| Updated to place strings back into include file so plook and other utils work
|
*/
#ifndef	ML_DD_MESS_H
#define	ML_DD_MESS_H

char	*mlDdMess001 = "Dropshipments require system generated P/O Numbers.",
		*mlDdMess002 = "Supplier Shipping Details",
		*mlDdMess003 = "Purchase order does not relate to a direct delivery.",
		*mlDdMess004 = "Do you wish to balance as a separate shipment [Y/N]?",
		*mlDdMess005 = "Shipment is already confirmed.",
		*mlDdMess006 = "Shipment is already despatched.",
		*mlDdMess007 = "Shipment is already despatched and invoiced.",
		*mlDdMess008 = "Shipment is not yet confirmed.",
		*mlDdMess009 = "Are you sure you wish to transfer line to another shipment [Y/N]?",
		*mlDdMess010 = "Shipment %s will require re-costing. Proceed [Y/N]?",
		*mlDdMess011 = "Forward Exchange Contract amount exceeded.  Amount remaining %.2f. Order cannot be saved.",
		*mlDdMess012 = "Committing existing direct delivery order.",
		*mlDdMess013 = "Do you wish to reprint shipment [Y/N]?",
		*mlDdMess014 = "Do you wish to reprint purchase order %s [Y/N]?",
		*mlDdMess015 = "Printing direct delivery shipment.",
		*mlDdMess016 = "Deleting direct delivery order %s.",
		*mlDdMess017 = "Deleting purchase order %s.",
		*mlDdMess018 = "Deleting complete order.",
		*mlDdMess019 = "Updating direct delivery order.",
		*mlDdMess020 = "Updating direct delivery order lines.",
		*mlDdMess021 = "Printing purchase order %s",
		*mlDdMess022 = "Creating goods receipt number %s.",
		*mlDdMess023 = "Deleting direct delivery shipment %s.",
		*mlDdMess024 = "Creating direct delivery shipment %s.",
		*mlDdMess025 = "Updating direct delivery shipment %s.",
		*mlDdMess026 = "Enter due date for new shipment :",
		*mlDdMess027 = "Direct Delivery Supplier Confirmation",
		*mlDdMess028 = "Direct Delivery Supplier Despatch",
		*mlDdMess029 = "Item %s cannot have purchases as class [%s] and only valid class of %s are allowed.",
		*mlDdMess030 = "Item %s cannot have purchases as class is [%s].",
		*mlDdMess031 = "Purchase order cannot be confirmed as it does not have correct status.",
		*mlDdMess032 = "Purchase order cannot be confirmed as it has not been approved.",
		*mlDdMess033 = "This item has been discontinued.",
		*mlDdMess034 = "Customer Order Reference must be input.",
		*mlDdMess035 = "Due date is past the required date.",
		*mlDdMess036 = "Due date is past the required date. Accept [Y/N]?",
		*mlDdMess037 = "Usage : %s <lpno> <type [Q/O/S]> [hhdd_hash]",
		*mlDdMess038 = "",
		*mlDdMess039 = "",
		*mlDdMess040 = "Order No. %s is not active and cannot be maintained here.",
		*mlDdMess041 = "Customer No : %s(%-40.40s) %4.4s %-3.3s%c %s%3.3s %s%.4f",
		*mlDdMess042 = "Supplier No : %6.6s (%-40.40s) %4.4s %-3.3s%c %s%3.3s %s%.4f",
		*mlDdMess043 = "Order is not created as no lines are present.",
		*mlDdMess044 = "Deleting Redundant Purchase Orders.",
		*mlDdMess045 = "Deleting Associated Shipments.",
		*mlDdMess046 = "Deleting Complete Order.",
		*mlDdMess047 = "Committing existing direct delivery order.",
		*mlDdMess048 = "Committing New Direct Delivery Order.",
		*mlDdMess049 = "Do you wish to print %s direct delivery order [Y/N]?",
		*mlDdMess050 = "Printing Direct Delivery Order %s.",
		*mlDdMess051 = "Do you wish to print %s purchase orders [Y/N]?",
		*mlDdMess052 = "Creating Direct Delivery Order %s.",
		*mlDdMess053 = "Updating Purchase Order No. %s on %s.",
		*mlDdMess054 = "Creating Purhcase Order No. %s on %s.",
		*mlDdMess055 = "Order %s cannot be confirmed as existing Order(s) plus this order exceeds credit terms by %.2f.",
		*mlDdMess056 = "Direct Delivery Order Input/Maintenance",
		*mlDdMess057 = "Discounts are cumulative.",
		*mlDdMess058 = "Line :",
		*mlDdMess059 = "Pricing Unit:",
		*mlDdMess060 = "Conversion Factor:",
		*mlDdMess061 = "Desc :",
		*mlDdMess062 = "Supplier UOM:",
		*mlDdMess063 = "Supplier Lead Time:",
		*mlDdMess064 = "Discounts are absolute.",
		*mlDdMess065 = "Customers Consignment Details",
		*mlDdMess066 = "Enter 'Y' if credit is approved / 'N' if not approved / 'M' if more details on credit required [Y/N/M].",
		*mlDdMess067 = "Has credit been approved [Y/N]?",
		*mlDdMess068 = "Order has an invalid Customer Contract No.",
		*mlDdMess069 = "Order has an invalid Forward Exchange Contract No.",
		*mlDdMess070 = "Purchase order is for a non-existent supplier.",
		*mlDdMess071 = "Minimum margin for category was not obtained.",
		*mlDdMess072 = "Due date is already past.  Accept [Y/N]?",
		*mlDdMess073 = "Enter volume for item %s in cubic meters:",
		*mlDdMess074 = "Enter weight for item %s in kilograms :",
		*mlDdMess075 = "Header Screen",
		*mlDdMess076 = "Order Screen",
		*mlDdMess077 = "On Cost Screen",
		*mlDdMess078 = "Pricing Screen",
		*mlDdMess079 = "Instruction Screen",
		*mlDdMess080 = "Contract Currency does not match customers.",
		*mlDdMess081 = "Forward Exchange Contract is not active.",
		*mlDdMess082 = "Contract is no longer current, expired %s.",
		*mlDdMess083 = "Contract is not yet current, effective %s.",
		*mlDdMess084 = "Order No. %s is on file for a different customer.",
		*mlDdMess085 = "Contract not assigned to this customer.",
		*mlDdMess086 = "Item no %s has no inventory supplier record for %s.",
		*mlDdMess087 = "Shipment Default Screen",
		*mlDdMess088 = "Discount may not exceed 99.99.",
		*mlDdMess089 = "Error adding branch record.",
		*mlDdMess090 = "Start Quotation ",
		*mlDdMess091 = "End Quotation ",
		*mlDdMess092 = "Use purchase order report program to reprint purchase orders.",
		*mlDdMess093 = "<type> must be Q(uotation), O(rder Confirmation), or S(upplier Confirmation .",
		*mlDdMess094 = "Quotation Reprint Input",
		*mlDdMess095 = "Order Confirmation Reprint Input",
		*mlDdMess096 = "Purchase Order Reprint Input",
		*mlDdMess097 = "Start Order Confirmation",
		*mlDdMess098 = "End Order Confirmation",
		*mlDdMess099 = "Start Purchase Order",
		*mlDdMess100 = "End Purchase Order",
		*mlDdMess101 = "FOB (FGN)",
		*mlDdMess102 = "Reg %",
		*mlDdMess103 = "Disc A",
		*mlDdMess104 = "Disc B",
		*mlDdMess105 = "Disc C",
		*mlDdMess106 = "NET FOB(FGN)",
		*mlDdMess700 = "Usage : %s <creat_flag> optional <lpno>",
		*mlDdMess701 = "Usage : %s <upd_flag> <text file> optional <lpno>",
		*mlDdMess702 = "      : <upd_flag> %1.1s - Supplier Confirmation",
		*mlDdMess703 = "      : <upd_flag> %1.1s - Supplier Despatch",
		*mlDdMess704 = "Usage : %s <text file> optional <lpno>";
#endif	
