/*=====================================================================
|  Copyright (C) 1999 - 2000 LogisticSoftware                         |
|=====================================================================|
| $Id: ml_pc_mess.h,v 5.0 2001/06/19 06:51:33 cha Exp $
-----------------------------------------------------------------------
| $Log: ml_pc_mess.h,v $
| Revision 5.0  2001/06/19 06:51:33  cha
| LS10-5.0 New Release as of 19 JUNE 2001
|
| Revision 4.0  2001/03/09 00:59:26  scott
| LS10-4.0 New Release as at 10th March 2001
|
| Revision 3.1  2000/12/12 04:50:04  scott
| Updated to place strings back into include file so plook and other utils work
|
*/
#ifndef	ML_PC_MESS_H
#define	ML_PC_MESS_H

char	*mlPcMess001 = "Calendar will be deleted for this date. Update [Y/N]?",
		*mlPcMess002 = "Calendar Maintenance",
		*mlPcMess003 = "Work Order status is planned.",
		*mlPcMess004 = "Work Order status is deleted.",
		*mlPcMess005 = "Work Order status is closed.",
		*mlPcMess006 = "Item should be BP, BM, MC or MP.",
		*mlPcMess007 = "%cOnly (Avail %f QC %f - STD) %14.6f On Hand and, Trying To Issue %14.6f",
		*mlPcMess008 = "%cOnly (%f STD UOM) %14.6f On Hand - Item %s and, Trying To Issue %14.6f",
		*mlPcMess009 = "%cOnly %14.6f Has been Issued, You Are Trying To Return %14.6f",
		*mlPcMess010 = "Decimal point needs to greater than %d.",
		*mlPcMess011 = "%RDescription : %-40.40s",
		*mlPcMess012 = "Works Order Material Issue",
		*mlPcMess013 = "Works Order Material Returns",
		*mlPcMess014 = "Units Of Measure",
		*mlPcMess015 = "By-product %-16.16s On Page %2d Line %2d is not received by A valid location.",
		*mlPcMess016 = "Production Control Sequence Update",
		*mlPcMess017 = "Batch Sizes",
		*mlPcMess018 = "Std.",
		*mlPcMess019 = "Min.",
		*mlPcMess020 = "Max.",
		*mlPcMess021 = "Failed Yield Calculation",
		*mlPcMess022 = "Close Off Figures For Sequence %2d Work Centre (%-8.8s)",
		*mlPcMess023 = "Estimate",
		*mlPcMess024 = "Actual",
		*mlPcMess025 = "Qty",
		*mlPcMess026 = "Receipt By-Products From Sequence %2d",
		*mlPcMess027 = "%R Mfg Item : %-16.16s   Description : %-40.40s ",
		*mlPcMess028 = "Production Control Resource Time Entry",
		*mlPcMess029 = "Works Order Deletion",
		*mlPcMess030 = "Updating Special Instructions...",
		*mlPcMess031 = "Updating Hazard Warnings...",
		*mlPcMess032 = "Alt. Uom - %4.4s",
		*mlPcMess033 = "Factor    %7.3f  ",
		*mlPcMess034 = "Std. batch %8.2f",
		*mlPcMess035 = "Min. batch %8.2f",
		*mlPcMess036 = "Max. batch %8.2f",
		*mlPcMess037 = "Product Special Instructions",
		*mlPcMess038 = "Product Hazard Warnings",
		*mlPcMess039 = "Product Instruction Detail Maintenance",
		*mlPcMess040 = "Use scheduling since it is enabled.",
		*mlPcMess041 = "Works Order [%s] not updated.",
		*mlPcMess042 = "Current Batch No : %-10.10s ",
		*mlPcMess043 = "Works Order Status Maintenance",
		*mlPcMess044 = "Change Status From (%s) To (%s)",
		*mlPcMess045 = "Company Name : %s",
		*mlPcMess046 = "Start Employee : %s",
		*mlPcMess047 = "End Employee : %s",
		*mlPcMess048 = "Level : %-9.9s",
		*mlPcMess049 = "Sub Totals : %s",
		*mlPcMess050 = "Timesheet Audit Trail",
		*mlPcMess051 = "Display Timesheet Audit Trail",
		*mlPcMess052 = "Please ensure a printer no. has been entered.",
		*mlPcMess053 = "Start Required Date : %s",
		*mlPcMess054 = "End Required Date : %s",
		*mlPcMess055 = "Order Status : %s",
		*mlPcMess056 = "Display/Print Works Order Status",
		*mlPcMess057 = "Display Works Order Status Report",
		*mlPcMess058 = "Times Overlap For Day %1d On Page %2d Line %3d ",
		*mlPcMess059 = "This resource uses the Global Calendar.",
		*mlPcMess060 = "Records exist for the date range. Update [Y/N]?",
		*mlPcMess061 = "Enter date within range for calendar generation.",
		*mlPcMess062 = "Date has been excluded.",
		*mlPcMess063 = "Calendar Generation",
		*mlPcMess064 = "Dates To Exclude",
		*mlPcMess065 = "Display Master Instructions",
		*mlPcMess066 = "Display Instruction Details",
		*mlPcMess067 = "Works Order not found.",
		*mlPcMess068 = "Item in Work Order is not found.",
		*mlPcMess069 = "Works Order Costing Report",
		*mlPcMess070 = "Lot not found.",
		*mlPcMess071 = "Start Item : %-16.16s",
		*mlPcMess072 = "End Item : %-16.16s",
		*mlPcMess073 = "Start Lot No : %-7.7s",
		*mlPcMess074 = "End Lot No : %-7.7s",
		*mlPcMess075 = "Traceability of Lot-Controlled Items",
		*mlPcMess076 = "Display Traceability of Lot-Controlled Items",
		*mlPcMess077 = "Works In Progress Report",
		*mlPcMess078 = "Date must be within inventory module month[%s].",
		*mlPcMess079 = "Do you wish to close this job [Y/N/A] ?",
		*mlPcMess080 = "Work Order must be R(eleased) or C(losing) to receive stock",
		*mlPcMess081 = "Timesheets and works order not updated, can't close work order.",
		*mlPcMess082 = "Reason %s has no G/L account.",
		*mlPcMess083 = "Quantity %14.6f greater than allowed quantity %f",
		*mlPcMess084 = "Production Stock Receipts",
		*mlPcMess085 = "Work Centre Maintenance",
		*mlPcMess086 = "Works Order Print",
		*mlPcMess087 = "Employee Maintenance",
		*mlPcMess088 = "%RManufactured Products Costing Report",
		*mlPcMess089 = "Timesheet Purge",
		*mlPcMess090 = "Released works order not found.",
		*mlPcMess091 = "Works order not released.",
		*mlPcMess092 = "Batch size can not be lowered below the allocated quantity",
		*mlPcMess093 = "Total Qty Required [%f] cannot be issued. BOM Specification has a serial item[%s].",
		*mlPcMess094 = "Works Order not found, number generated by system.",
		*mlPcMess095 = "Batch number should be entered.",
		*mlPcMess096 = "Works Order Number (%s) created.",
		*mlPcMess097 = "Works Order Maintenance",
		*mlPcMess098 = "Released Works Order Maintenance",
		*mlPcMess099 = "Customer/Quantities",
		*mlPcMess100 = "Status : Planned",
		*mlPcMess101 = "Serial number must be entered.",
		*mlPcMess102 = "Serial number already assigned.",
		*mlPcMess103 = "Serial number already exists.",
		*mlPcMess104 = "Resource not found.",
		*mlPcMess105 = "Work Centre not found.",
		*mlPcMess106 = "Instruction not found.",
		*mlPcMess107 = "Quantity is less than minimum batch size.",
		*mlPcMess108 = "Quantity is greater than maximum batch size.",
		*mlPcMess109 = "Allocated is more than produced.",
		*mlPcMess110 = "This is required before today.",
		*mlPcMess111 = "Order has been closed.",
		*mlPcMess112 = "Order has been deleted.",
		*mlPcMess113 = "Work Order Requisition will be printed.",
		*mlPcMess114 = "Status : Firm Planned",
		*mlPcMess115 = "Status : Issuing",
		*mlPcMess116 = "Status : Allocated",
		*mlPcMess117 = "Status : Released",
		*mlPcMess118 = "Status : Closing",
		*mlPcMess119 = "Work order already exists.",
		*mlPcMess120 = "Customer is already allocated.",
		*mlPcMess121 = "Last Ref : %s",
		*mlPcMess122 = "Std. %14.6f",
		*mlPcMess123 = "Min. %14.6f",
		*mlPcMess124 = "Max. %14.6f",
		*mlPcMess125 = "Negative quantity must not be issued.",
		*mlPcMess126 = "Negative quantity must not be returned.",
		*mlPcMess127 = "This is a serial controlled item. Enter valid serial numbers.",
		*mlPcMess128 = "Next sequence must be greater than previous sequence.",
		*mlPcMess129 = "Routing sequence not found.",
		*mlPcMess130 = "Date must not be before work order was raised.",
		*mlPcMess131 = "A serial item by-product must not be receipted.",
		*mlPcMess132 = "Work order is not released.",
		*mlPcMess133 = "You may only choose R(eleased) or C(losing) jobs.",
		*mlPcMess134 = "Enter a work order no. or a batch no..",
		*mlPcMess135 = "Receipting of order has started.",
		*mlPcMess136 = "Work order is closing.",
		*mlPcMess137 = " Standard Working Week",
		*mlPcMess138 = "Work order not found - Batch No.[%s]",
		*mlPcMess139 = "Times Overlap For %s On Page %2d Line %3d ",
		*mlPcMess140 = " Materials Need Issuing Before Sequence %2d Can Start. ",
		*mlPcMess141 = " Therefore Update Will Stop At Sequence %2d. ",
		*mlPcMess142 = " Do You Want A Picking Slip To Be Printed ? ",
		*mlPcMess143 = " Print Lot Details ? ",
		*mlPcMess144 = " Print Bin Details ? ",
		*mlPcMess145 = " Only Print Required Amounts ? ",
		*mlPcMess146 = " Works In Progress Report ",

		*mlPcMess700 = "Usage : %s <lpno> <G(en Ledger)/J(ournal)>",
		*mlPcMess701 = "Usage : %s <lpno> <process_id>",
		*mlPcMess702 = "Usage : %s <lpno> <Seq> <Print> <Lot> <Bin> <Req>",
		*mlPcMess703 = "      <Print> - print ok (Y/N)",
		*mlPcMess704 = "      <Lot>   - print lot details (Y/N)",
		*mlPcMess705 = "      <Bin>   - print bin deatils (Y/N)",
		*mlPcMess706 = "      <Req>   - print lot and bin detials for the",
		*mlPcMess707 = "                required amount (Y/N)",
		*mlPcMess708 = "Usage : %s <lpno> <Current Status>",
		*mlPcMess709 = "                 -  P (lanned)",
		*mlPcMess710 = "                 -  F (irm Planned)",
		*mlPcMess711 = "                 -  A (llocated)",
		*mlPcMess712 = "Usage : %s <description>",
		*mlPcMess713 = " OR   : %s <lpno> <start W/O> <end W/O>",
		*mlPcMess714 = "Usage : %s <M(aster) | D(etail)>",
		*mlPcMess715 = "Usage : %s <start> <end> <extra> <level> <lpno>",
		*mlPcMess716 = "           <start> - start pcwo_hhwo_hash",
		*mlPcMess717 = "           <end>   - end pcwo_hhwo_hash",
		*mlPcMess718 = "           <extra> - Y(es) N(o) printed",
		*mlPcMess719 = "           <level> - C(ompany) B(ranch) W(arehouse)";
#endif	
