/*=====================================================================
|  Copyright (C) 1999 - 2000 LogisticSoftware                         |
|=====================================================================|
| $Id: ml_po_mess.h,v 5.3 2001/12/06 05:29:25 scott Exp $
-----------------------------------------------------------------------
| $Log: ml_po_mess.h,v $
| Revision 5.3  2001/12/06 05:29:25  scott
| Updated to allow purchase returns that are allocated to an original purchase order to select lot information. The lot display will only show those Location/Lot records that belong to the original receipt. This caters for both multiple receipts of the same product on the same purchase order AND Locations/Lots being split after receipt.
|
| Revision 5.2  2001/10/05 02:45:55  cha
| Updated to allow processing of locations and lots for goods returns
|
| Revision 5.0  2001/06/19 06:51:33  cha
| LS10-5.0 New Release as of 19 JUNE 2001
|
| Revision 4.0  2001/03/09 00:59:26  scott
| LS10-4.0 New Release as at 10th March 2001
|
| Revision 3.1  2000/12/12 04:50:04  scott
| Updated to place strings back into include file so plook and other utils work
|
*/
#ifndef	ML_PO_MESS_H
#define	ML_PO_MESS_H

char	*mlPoMess001 = "Order has been closed.",
		*mlPoMess002 = "Serial Numbers cannot be assigned to Direct Delivery Orders.",
		*mlPoMess003 = "Return %s has been closed.",
		*mlPoMess004 = "Purchase Order has no detail lines.",
		*mlPoMess005 = "Could not find the superceeding item.",
		*mlPoMess006 = "Purchase Order Serial Number Allocation",
		*mlPoMess007 = "Last Order : %s/%s",
		*mlPoMess008 = "Confirm Complete Purchase Order [Y/N]?",
		*mlPoMess009 = "System is not set up for automatic numbering.",
		*mlPoMess010 = "Shipment status is not I(nput or R(eceipted.",
		*mlPoMess011 = "Exchange Rate must be greater than 0.00.",
		*mlPoMess012 = "Departure Date <= Arrival Date.",
		*mlPoMess013 = "Quick Purchase Orders cannot be part of a shipment.",
		*mlPoMess014 = "Direct Delivery Orders cannot be part of a shipment.",
		*mlPoMess015 = "Purchase Order has not been approved.",
		*mlPoMess016 = "Outstanding Order Qty = %10.2f",
		*mlPoMess017 = "Purchase Return not found.",
		*mlPoMess018 = "Adding shipment no. %06ld.",
		*mlPoMess019 = "Updating shipment no. %06ld.",
		*mlPoMess020 = "Adding purchase order to shipment.",
		*mlPoMess021 = "Updating exchange rates on P/Order(s) allocated to shipment.",
		*mlPoMess022 = "Shipment Maintenance.",
		*mlPoMess023 = "Adding complete purchase order.",
		*mlPoMess024 = "Line : %3d/Desc : %-40.40s  %-25.25s BASE UOM: %-4.4s",
		*mlPoMess025 = "Line : %3d/Desc : %-37.37s / Ser# %-25.25sa  BASE UOM: %-4.4s",
		*mlPoMess026 = "Now updating order.",
		*mlPoMess027 = "Purchase Order Shipment Assignment",
		*mlPoMess028 = "Order Detail Flag should be Y(es) or N(o)",
		*mlPoMess029 = "Shipping Schedule Report Input",
		*mlPoMess030 = "Shipping Schedule Display",
		*mlPoMess031 = "Display covered period from %s to %s",
		*mlPoMess032 = "Sales Orders cannot be assigned to Direct Delivery Orders.",
		*mlPoMess033 = "Transfers cannot be assigned to Direct Delivery Orders.",
		*mlPoMess034 = "Current item does not exist in sales order no. %s.",
		*mlPoMess035 = "Current item does not exist in transfer no. %06ld.",
		*mlPoMess036 = "Quantity allocated cannot be input as no sales order is selected.",
		*mlPoMess037 = "Quantity allocated cannot be greater than order quantity %.2f.",
		*mlPoMess038 = "Do you want to allocate this line to another sales order [Y/N]?",
		*mlPoMess039 = "Inserting line.",
		*mlPoMess040 = "Purchase Order -> Sales Order Assignment",
		*mlPoMess041 = "Purchase Order -> Transfer Assignment",
		*mlPoMess042 = "Supplier Status Display",
		*mlPoMess043 = "Last Supplier : %s",
		*mlPoMess044 = "INVOICES (CREDIT) APPROVED   %13.2f",
		*mlPoMess045 = "INVOICES (CREDIT) UNAPPROVED %13.2f",
		*mlPoMess046 = "CREDITS  (CREDIT)            %13.2f",
		*mlPoMess047 = "JOURNALS                     %13.2f",
		*mlPoMess048 = "CHEQUES  (DEBIT)             %13.2f",
		*mlPoMess049 = "BALANCE                      %13.2f",
		*mlPoMess050 = "    CURRENT       31 - 60       61 - 90       OVER 90       TOTAL AMOUNT.   ",
		*mlPoMess051 = "  Q U A L I T Y   A S S U R A N C E   S C O P E   T E X T.",
		*mlPoMess052 = "Purchase Orders for Item : %-16.16s (%-40.40s)",
		*mlPoMess053 = "Individual Item P/O Dislay",
		*mlPoMess054 = "Purchase Order History Enquiry by Supplier",
		*mlPoMess055 = "Loading.",
		*mlPoMess056 = "Print Delivery Performance By Supplier",
		*mlPoMess057 = "Item cannot have purchases as class is [%s] and only valid classes are [%s].",
		*mlPoMess058 = "Supplier FOB price for shipment(s) will be changed since order is assigned to a shipment.",
		*mlPoMess059 = "Data cannot be input for goods (FOB).",
		*mlPoMess060 = "Quick purchase orders must be local.",
		*mlPoMess061 = "Direct delivery orders cannot be maintained here.",
		*mlPoMess062 = "Quick purchase orders can be maintained.",
		*mlPoMess063 = "Search cannot be performed unless a supplier number is entered.",
		*mlPoMess064 = "Purchase order # %s  /  Supplier  %s  %s",
		*mlPoMess065 = "Creating purchase order no. %s.",
		*mlPoMess066 = "Updating order detail lines.",
		*mlPoMess067 = "Deleting complete order.",
		*mlPoMess068 = "Deleting P/O from shipment.",
		*mlPoMess069 = "Updating existing order.",
		*mlPoMess070 = "Purchase order no (%s) added.  Press any key to continue.",
		*mlPoMess071 = "Purchase order no (%s) added.  Press 'P' to print, any other key to continue.",
		*mlPoMess072 = "Updating shipment invoice totals.",
		*mlPoMess073 = "Date %s  Currency  %s %s  P/O Header Exchange Rate  %8.4f",
		*mlPoMess074 = "Calculating.",
		*mlPoMess075 = "%R Line ",
		*mlPoMess076 = "%R Ship No ",
		*mlPoMess077 = "%R Exch Rate ",
		*mlPoMess078 = "%R Pricing Unit ",
		*mlPoMess079 = "%R Desc ",
		*mlPoMess080 = "%R Std. UOM ",
		*mlPoMess081 = "%R Serial No ",
		*mlPoMess082 = "Goods (FOB) is always the total of line items and is not spread.",
		*mlPoMess083 = "Freight and insurance will be spread automatically if a value is entered into these fields.",
		*mlPoMess084 = "Interest, Bank & Other 1-4 will be spread into 'Int/Bank/Other' field on item screen if a value is entered into any of these fields.",
		*mlPoMess085 = "Duty will be spread automatically if a value is entered into duty field.",
		*mlPoMess086 = "Purchase Order Maintenance",
		*mlPoMess087 = "Payment Terms",
		*mlPoMess088 = "Standard Instructions",
		*mlPoMess089 = "Supplier Shipping Details",
		*mlPoMess090 = "Do you wish to close and delete purchase order [Y/N]?",
		*mlPoMess091 = "Purchase Order Status Maintenance",
		*mlPoMess092 = "Shipping Details",
		*mlPoMess093 = "Selection type should be A, S, or G.",
		*mlPoMess094 = "Duty not spread.",
		*mlPoMess095 = "Please ensure at least one product is taxable.",
		*mlPoMess096 = "Recalculating purchase order lines.",
		*mlPoMess097 = "Deleting purchase order costing screens.",
		*mlPoMess098 = "Creating shipment costing screen.",
		*mlPoMess099 = "Calculating purchase order(s) on shipment.",
		*mlPoMess100 = "Shipment Costing",
		*mlPoMess101 = "Currency Exchange Maintenance",
		*mlPoMess102 = "No exchange details. Press any key.",
		*mlPoMess103 = "Start P/O # %s  to End P/O # %s  / Start Supplier %s  to End Supplier %s",
		*mlPoMess104 = "Display P/Orders By Supplier",
		*mlPoMess105 = "Purchase return # %s  /  Supplier  %s  %s",
		*mlPoMess106 = "Creating purchase return no. %s.",
		*mlPoMess107 = "Adding return detail lines.",
		*mlPoMess108 = "Updating return detail lines.",
		*mlPoMess109 = "Deleting complete return.",
		*mlPoMess110 = "Updating existing return.",
		*mlPoMess111 = "Purchase return no (%s) added.  Press any key to continue.",
		*mlPoMess112 = "Purchase return no (%s) added.  Press 'P' to print, any other key to continue.",
		*mlPoMess113 = "Purchase Return has no detail lines.",
		*mlPoMess114 = "Do you wish to credit whole purchase order [Y/N]?",
		*mlPoMess115 = "Last Return : %s/%s",
		*mlPoMess116 = "Purchase Return Maintenance",
		*mlPoMess117 = "N/A",
		*mlPoMess118 = "Discounts are %s ",
		*mlPoMess119 = "Return Terms",
		*mlPoMess120 = "Print Goods Receipt",
		*mlPoMess121 = "Invoice no %s is on file but not approved.",
		*mlPoMess122 = "This item has been discontinued.",
		*mlPoMess123 = "This item has no UOM.",
		*mlPoMess124 = "Serial items are limited to 100 per line.  Enter as separate lines.",
		*mlPoMess125 = "I(nput) or P(rint) Only",
		*mlPoMess126 = "Purchase Order/Product Information Maintenance",
		*mlPoMess127 = "Purchase Order Approval Maintenance",
		*mlPoMess128 = "Sales Order And Purchase Order Assignment",
		*mlPoMess129 = "Print Purchase Order By Item No.",
		*mlPoMess130 = "Print Purchase Order By Supplier",
		*mlPoMess131 = "Purchase return no (%s) updated.  Press any key to continue.",
		*mlPoMess132 = "Purchase return no (%s) updated.  Press 'P' to print, any other key to continue.",
		*mlPoMess133 = "Currency %s / Country = %s",
		*mlPoMess134 = "Discount are cumulative.",
		*mlPoMess135 = "Discount are absolute.",
		*mlPoMess136 = "Beginning or End of File",
		*mlPoMess137 = "Inventory Supplier Xref By Supplier",
		*mlPoMess138 = "Pro-Forma Cost of In-Transits Report",
		*mlPoMess139 = "Purchase Order History Enquiry By Item",
		*mlPoMess140 = "Purchase Order is part of shipment %ld",
		*mlPoMess141 = "Classification Type Maintenance",
		*mlPoMess142 = "Country/Freight File Maintenance",
		*mlPoMess143 = "Purchase Order Licence Control Maintenance",
		*mlPoMess144 = "Quality Assurance Maintenance",
		*mlPoMess145 = "Duty Control Maintenance",
		*mlPoMess146 = "Comments",
		*mlPoMess147 = "Control Account : %s",
		*mlPoMess148 = "Variance Account : %s",
		*mlPoMess149 = "Purchase Receipt/Costing Variance Deletion",
		*mlPoMess150 = "Print Single Purchase Order Costing",
		*mlPoMess151 = "Print Single Purchase Order",
		*mlPoMess152 = "Print Single Purchase Return",
		*mlPoMess153 = "Shipment No %07ld",
		*mlPoMess154 = "Purchase Order No %s",
		*mlPoMess155 = "Goods Receipt No %s",
		*mlPoMess156 = "Date %s",
		*mlPoMess157 = "Currency %s : %10.4f",
		*mlPoMess158 = "Customs Ex. Rate :",
		*mlPoMess159 = "Puchase Order Receipt Costing",
		*mlPoMess160 = "Puchase Order Receipt Costing - Invoice Detail",
		*mlPoMess161 = "Use Window-Activate Key#1 to Tag Supplier Invoices.",
		*mlPoMess162 = "Puchase Order Receipt Costing - Item Detail",
		*mlPoMess163 = "Use Window-Activate Key#1 to spread FOB amounts based on Invoice Details.",
		*mlPoMess164 = "%R Land Cost ",
		*mlPoMess165 = "%R Suppliers Part No ",
		*mlPoMess166 = "%R UOM ",
		*mlPoMess167 = "Confirm Complete Shipment [Y/N] ?",
		*mlPoMess168 = "Confirm Complete Purchase Order [Y/N] ?",
		*mlPoMess169 = "Lot No exists for item %s. Overwrite expiry date [Y/N] ?",
		*mlPoMess170 = "Receipt the balance as a separate line [Y/N] ?",
		*mlPoMess171 = "Use Serial No Allocation to change before receipting",
		*mlPoMess172 = "Purchase Return Despatch Confirmation",
		*mlPoMess173 = "Purchase Order Receipt",
		*mlPoMess174 = "Last Order: %s/%s",
		*mlPoMess175 = "Confirming Complete Goods Receipt",
		*mlPoMess176 = "%cNot all QC Centres have been entered.",
		*mlPoMess177 = "Goods Receipt No exists for another supplier.",
		*mlPoMess178 = "Goods Receipt Status must be R(eceipted) or U(pdated).",
		*mlPoMess179 = "Goods Receipt has been previously used for non-shipment order",
		*mlPoMess180 = "Goods Receipt has been previously used for shipment order",
		*mlPoMess181 = "Illegal to mix Quick and Normal P/Orders on one GRN.",
		*mlPoMess182 = "%.2f Outstanding %.2f Supplied",
		*mlPoMess183 = "Maximum value for serial number exceeded on line %3d",
		*mlPoMess184 = "Adding Goods Receipt Header %s.",
		*mlPoMess185 = "Updating Goods Receipt %s.",
		*mlPoMess186 = "Updating Invoice Totals.",
		*mlPoMess187 = "Invalid serial item found on line %d. Please add serial item.",
		*mlPoMess188 = "Invalid location found on line %d. Please correct location.",
		*mlPoMess189 = "Invalid lot no found on line %d. Please correct lot no.",
		*mlPoMess190 = "Please enter QC Centre on line %d.",
		*mlPoMess191 = "Pro-Forma Receipting Report",
		*mlPoMess192 = "Purchase Order by Location Report",
		*mlPoMess193 = "Purchase order no (%s) updated.  Press any key to continue.",
		*mlPoMess194 = "Purchase order no (%s) updated.  Press 'P' to print, any other key to continue.",
		*mlPoMess195 = "Shipment No or Purchase No must be entered.",
		*mlPoMess196 = "Invoiced value of goods is not equal to costed value.",
		*mlPoMess197 = "Invoiced value of duty is not equal to costed value.",
		*mlPoMess198 = "Invoiced value of freight and insurance is not equal to costed value.",
		*mlPoMess199 = "Direct delivery receipts cannot be costed here.",
		*mlPoMess200 = "Shipment cannot be receipted because it has been costed or partially costed.",
		*mlPoMess201 = "Shipment cannot be receipted because it has been costed and closed.",
		*mlPoMess202 = "Shipment has no lines.",
		*mlPoMess203 = "Direct delivery orders cannot be receipted here.",
		*mlPoMess204 = "Purchase order cannot be receipted since it is not yet approved.",
		*mlPoMess205 = "Purchase order cannot be receipted since it does not have the correct status.",
		*mlPoMess206 = "Goods receipt number must be input.",
		*mlPoMess207 = "No numeric component in serial no. Cannot increment.",
		*mlPoMess208 = "Serial no. cannot be input if quantity is 0.00.",
		*mlPoMess209 = "Cannot generate serial no. Enter manually.",
		*mlPoMess210 = "Print Single Purchase Supplier",
		*mlPoMess211 = "Print Single Purchase Order",
		*mlPoMess212 = "Warning : This GST rate is not %4.2f%%.",
		*mlPoMess213 = "Goods receipt no. %s is already costed.",
		*mlPoMess214 = "Goods receipt no. %s is closed.",
		*mlPoMess215 = "Status is %s - not U(pdated to stock) or P(artially costed).",
		*mlPoMess216 = "Goods  : Inv-> %10.10s  Items-> %10.10s  Var-> %10.10s",
		*mlPoMess217 = "Duty   : Inv-> %10.10s  Items-> %10.10s  Var-> %10.10s",
		*mlPoMess218 = "Frt&Ins: Inv-> %10.10s  Items-> %10.10s  Var-> %10.10s",
		*mlPoMess219 = " %s Report",
		*mlPoMess220 = "Print Delivery Performance By Supplier",
		*mlPoMess221 = "Print Purchase Orders By Item No",
		*mlPoMess222 = "Print Purchase Orders By Supplier",
		*mlPoMess223 = "FOB (FGN)",
		*mlPoMess224 = "Reg %",
		*mlPoMess225 = "Disc A",
		*mlPoMess226 = "Disc B",
		*mlPoMess227 = "Disc C",
		*mlPoMess228 = "NET FOB(FGN)",
		*mlPoMess229 = "Print Sales and Purchase Order Assignment",
		*mlPoMess230 = "NOTE : does not exist in inventory supplier file.",
		*mlPoMess231 = "NOTE : are you sure you DO NOT want to apply the purchase return to a Purchase order ? (Y/N) : ",
		*mlPoMess232 = "%.2f Purchased %.2f Returned",
		*mlPoMess233 = "Confirm Complete Purchase Return [Y/N] ?",

		*mlPoMess700 = "Usage : %s <program description>",
		*mlPoMess701 = "   OR : %s <lpno>",
		*mlPoMess702 = "           <start date>",
		*mlPoMess703 = "           <end date>",
		*mlPoMess704 = "           <order detail - [Y/N]>",
		*mlPoMess705 = "           <D(isplay) | P(rinter)>",
		*mlPoMess706 = "Usage : %s <lpno> <purchase status> <posting flag> <direct delivery [Y)es/N)o]>",
		*mlPoMess707 = "Usage : %s <lpno> <purchase status> <direct delivery [Y)es/N)o]>",
		*mlPoMess708 = "Usage : %s <start Supplier> <end Supplier> <start date> <end date> <lpno>",
		*mlPoMess709 = "Usage : %s <lpno> <report_type>",
		*mlPoMess710 = "                  <report_type> - C.O.S eX(ceptions",
		*mlPoMess711 = "                                - V(ariances",
		*mlPoMess712 = "                                - E(stimated / Actual",
		*mlPoMess713 = "Usage : %s <nd_flag>",
		*mlPoMess714 = "<nd_flag> - <license no.>",
		*mlPoMess715 = "          - <license/unit>",
		*mlPoMess716 = "          - <due_date>",
		*mlPoMess717 = "          - <branch/warehouse>",
		*mlPoMess718 = "          - <quick-only>",
		*mlPoMess719 = "Usage : %s <lpno> <[A|S|G]> <[Supplier|Gr. No.]>",
		*mlPoMess720 = "Usage : %s <I)nput|P)rint> [lpno]",
		*mlPoMess721 = "Usage : %s <lpno> <start date>",
		*mlPoMess722 = "Usage : %s <lpno> <lower> <upper>",
		*mlPoMess723 = "Usage : %s <start item> <end item> <lpno>",
		*mlPoMess724 = "Usage : %s <start Supplier> <end Supplier> <lpno>",
		*mlPoMess725 = "Usage : %s <lpno> <ship_no>",
		*mlPoMess726 = " or   : %s <lpno> P <P/O_no>",
		*mlPoMess727 = " or   : %s",
		*mlPoMess728 = "Usage : %s <lpno> <sort by: N(umber) or A(cronym)>",
		*mlPoMess729 = "Usage : %s <L(ocation), I(tem No) or P(urchase Order)>",
		*mlPoMess730 = "Usage : %s <C(urrency) F(reight) L(icence) D(uty) Classification T(ype) Q(A Status)>",
		*mlPoMess731 = "Usage : %s <lpno> <C(urrency) F(reight) L(icence) D(uty)>",
		*mlPoMess732 = "Usage : %s <lpno> <hhpo_hash>",
		*mlPoMess733 = "Usage : %s <lpno> <ship_no>",
		*mlPoMess734 = "Usage : %s <prog_name> <prog_desc> - optional <flag>",
		*mlPoMess735 = "Print Purchase Orders By P/O No",
		*mlPoMess736 = "Quantity exceeds pallet size. Please enter balance on a seperate line",
		*mlPoMess737 = "Order has been transmitted.";
#endif	
