/*=====================================================================
|  Copyright (C) 1999 - 2000 LogisticSoftware                         |
|=====================================================================|
| $Id: ml_sk_mess.h,v 5.4 2002/11/28 04:09:47 scott Exp $
-----------------------------------------------------------------------
| $Log: ml_sk_mess.h,v $
| Revision 5.4  2002/11/28 04:09:47  scott
| SC0053 - Platinum Logistics - LS10.5.2 2002-11-28
| Updated for changes in pricing - See S/C for Details
|
| Revision 5.3  2002/08/01 01:45:27  scott
| .
|
| Revision 5.2  2002/02/28 09:24:41  scott
| Updated for lineup issues.
|
| Revision 5.1  2002/01/23 08:37:25  scott
| Updated to fix prompt. S/C 00478
|
| Revision 5.0  2001/06/19 06:51:34  cha
| LS10-5.0 New Release as of 19 JUNE 2001
|
| Revision 4.5  2001/05/25 08:16:31  scott
| Updated for small lineup.
|
| Revision 4.4  2001/05/25 07:24:30  scott
| Updated to small lineup issue.
|
| Revision 4.3  2001/03/22 09:06:26  scott
| Updated to adjust screen to look better with LS10-GUI
|
| Revision 4.2  2001/03/22 06:49:18  scott
| Changes prompt from "Inventory Trans out & In" to
| "Inventory Transfers In and Out"
|
| Revision 4.1  2001/03/21 00:24:19  scott
| Updated to change message skMess049, last part from (Y/N/A) to [ Y(es / N(o / A(bort ]
|
| Revision 4.0  2001/03/09 00:59:26  scott
| LS10-4.0 New Release as at 10th March 2001
|
| Revision 3.2  2001/03/05 09:36:45  scott
| Updated to correct small lineup problems with LS10-GUI
|
| Revision 3.1  2000/12/12 04:50:04  scott
| Updated to place strings back into include file so plook and other utils work
|
*/
#ifndef	ML_SK_MESS_H
#define	ML_SK_MESS_H

char	*mlSkMess001 = "Usage : %s <report level> <lpno> <action> <period> <sort by> <value movement> <a_break> <b_break> <c_break> <print_ABCD>\n",
		*mlSkMess002 = "Total percentage breaks must = 100%",
		*mlSkMess003 = "Printing ABC codes",
		*mlSkMess004 = "Updating ABC codes",
		*mlSkMess005 = "Printing/Updating ABC codes",
		*mlSkMess006 = "report level : By C(ompany) or B(ranch) or W(arehouse)\n",
		*mlSkMess007 = "Sort By: S(ales Value) or M(argin)\n",
		*mlSkMess008 = "Maintain ABC Codes",
		*mlSkMess009 = "Usage : %s <pid> <M(aster)/B(ranch)/W(arehouse)/A(ll)>\n",
		*mlSkMess010 = "Inventory Master Deletes",
		*mlSkMess011 = "Inventory Branch Deletes",
		*mlSkMess012 = "Inventory Warehouse Deletes",
		*mlSkMess013 = "Inventory Fast Track Deletes",
		*mlSkMess014 = "Alternate Stock Item Display - Company",
		*mlSkMess015 = "Alternate Stock Item Display - Branch",
		*mlSkMess016 = "Alternate Stock Item Display - Warehouse",
		*mlSkMess017 = "Alternate Stock Item Display",
		*mlSkMess018 = "Usage : %s <lpno> <start> <end> <stocktake_mode>",
		*mlSkMess019 = "Usage : so_dismaint [1 or I] Customer By Item",
		*mlSkMess020 = "Customer Discount Maintenance",
		*mlSkMess021 = "By Unknown Selection",
		*mlSkMess022 = "By Customer Number and Category",
		*mlSkMess023 = "By Customer and Item Number",
		*mlSkMess024 = "By Customer and Selling Group",
		*mlSkMess025 = "By Customer Type and Category",
		*mlSkMess026 = "By Customer Type and Item Number",
		*mlSkMess027 = "By Customer Type and Selling Group",
		*mlSkMess028 = "By Price Type and Category",
		*mlSkMess029 = "By Price Type and Item Number",
		*mlSkMess030 = "By Price Type and Selling Group",
		*mlSkMess031 = "%s Report",
		*mlSkMess032 = "Branch Selection for Price List Reports",
		*mlSkMess033 = "Warehouse Selection for Price List Reports",
		*mlSkMess034 = "Display/Print Stock Transfer Issue/Receipts",
		*mlSkMess035 = "Display/Print Multi-Company Stock Transfer Issues/Receipts",
		*mlSkMess036 = "%s All Stock Transfer Receipts",
		*mlSkMess037 = "%s Daily Stock Issue Requests as at %10.10s",
		*mlSkMess038 = "%s Incomplete Transfer Issues/Receipts",
		*mlSkMess039 = "Printing On-Line Unmatched Transfers Report",
		*mlSkMess040 = "%s All Stock Transfer Issues",
		*mlSkMess041 = "Inventory Location Transfers",
		*mlSkMess042 = "Stock take selection [%c] is for serial stocktake.",
		*mlSkMess043 = "Stock Take Update",
		*mlSkMess044 = "Standard Rollup Simulation",
		*mlSkMess045 = "Supplier Rebate Maintenance",
		*mlSkMess046 = "Customer Rebate Maintenance",
		*mlSkMess047 = "Stock take selection [%s] not found for warehouse.",
		*mlSkMess048 = "Stock take selection [%s] is not for serial stock take.",
		*mlSkMess049 = "Supplier Discount Maintenance",
		*mlSkMess050 = "By Supplier and Buying Group",
		*mlSkMess051 = "Last Supplier: %s",
		*mlSkMess052 = "Inventory Tax Maintenance",
		*mlSkMess053 = "Usage : %s <lpno> <Z(ero cost)/N(egative on Hand)/A(vailable negative)/O(n  Order + Available negative>",
		*mlSkMess054 = "Usage : %s <lpno> <start> <end> <print_type> <mode>",
		*mlSkMess055 = "Usage : %s <customer hash> <item hash>",
		*mlSkMess056 = "<Customer Details>",
		*mlSkMess057 = "Contact Name     : %-20.20s%-20.20s",
		*mlSkMess058 = "Customer Address : %-40.40s",
		*mlSkMess059 = "Price Type       : %-16.16s%-24.24s",
		*mlSkMess060 = "Cust. Type/Area  : %-3.3s/%2.2s%34.34s",
		*mlSkMess061 = "Spec. Item Codes : %-40.40s",
		*mlSkMess062 = "Currency         : %-40.40s",
		*mlSkMess063 = "Stock On Hand    : %-10.2f%-19.19s",
		*mlSkMess064 = "Stock Available  : %-10.2f%-19.19s",
		*mlSkMess065 = "Stock Committed  : %-10.2f%-19.19s",
		*mlSkMess066 = "Stock On Order   : %-10.2f%-19.19s",
		*mlSkMess067 = "Stock Forward    : %-10.2f%-19.19s",
		*mlSkMess068 = "Stock Backorder  : %-10.2f%-19.19s",
		*mlSkMess069 = "<Branch Stock Status>",
		*mlSkMess070 = "Press return on highlighted line to display quantity breaks.",
		*mlSkMess071 = "<Item Details>",
		*mlSkMess072 = "Class            : %-40.40s",
		*mlSkMess073 = "Category         : %-40.40s",
		*mlSkMess074 = "Selling Group    : %-40.40s",
		*mlSkMess075 = "Buying Group     : %-40.40s",
		*mlSkMess076 = "Sale Unit        : %-40.40s",
		*mlSkMess077 = "Sale UOM Conv    : %-7.0f%-33.33s",
		*mlSkMess078 = "Price/Cost Conv  : %-7.0f%-33.33s",
		*mlSkMess079 = "Regulatory %%    : %-7.2f%-33.33s",
		*mlSkMess080 = "Last Customer %6.6s:",
		*mlSkMess081 = "QA Purchase Specifications By Buying Group Maintenance",
		*mlSkMess082 = "Stock Royalty Maintenance",
		*mlSkMess083 = "Total Pecentage Allocated Supplier(s) must be 100%%.",
		*mlSkMess084 = "Last Code: %s",
		*mlSkMess085 = "U(pdate), I(gnore Changes), D(elete)?",
		*mlSkMess086 = "Serial Item Costing Display",
		*mlSkMess087 = "Serial Item Adjustments",
		*mlSkMess088 = "Updating Serial# %s",
		*mlSkMess089 = "Last Ref :%s",
		*mlSkMess090 = "Usage : %s <description> <I(tem range)/G(roup range)>",
		*mlSkMess091 = "OR  : %s <I(tem range)/G(roup range)> <start> <end> <By Last Cost Y/N> <percent increase>",
		*mlSkMess092 = "Supplier Quantity Break Update",
		*mlSkMess093 = "Top Items Report Selection",
		*mlSkMess094 = "Usage : %s <lpno> <sale_type> <by_what> <num_items>",
		*mlSkMess095 = "OR : %s <prog_desc> <sale_type [M(TD)/Y(TD)]> <by_what [C(ompany)/B(ranch)>",
		*mlSkMess096 = "Last Item: %s",
		*mlSkMess097 = "Item Number:",
		*mlSkMess098 = "Load Inventory History",
		*mlSkMess099 = "%R Line: %3d  Description: %-40.40s",
		*mlSkMess100 = "The maximum number of warehouses (%d) has been exceeded.",
		*mlSkMess101 = "Alternate chain exceeds the maximum number of items (%d).",
		*mlSkMess102 = "Combined discount total on line exceeds 99.99%%.",
		*mlSkMess103 = "Combined surcharge total on line exceeds 99.99%%.",
		*mlSkMess104 = "Quantity break must be greater than previous break.",
		*mlSkMess105 = "Quantity break must be less than succeeding break.",
		*mlSkMess106 = "Usage : %s <type [(O)ne Step/(T)wo Step/(I)ssues/(R)eceipts/re(Q)uests/(U)nmatched> <period [(D)aily/(A)ll> <output [(D)isplay/(P)rinter> <lpno>",
		*mlSkMess107 = "Warning : Input date is outside current inventory date.",
		*mlSkMess108 = "Usage : <lpno> <start> <end> <by_what> <stk_sel>",
		*mlSkMess109 = "Usage : %s [B/W] <prog_desc> branches[5] <lpno>",
		*mlSkMess110 = "Usage : %s <no. of days offset>",
		*mlSkMess111 = "Usage : %s <lpno> <start> <end>",
		*mlSkMess112 = "Category is already allocated to this tax code.",
		*mlSkMess113 = "Item is already allocated to this tax code.",
		*mlSkMess114 = "Customer currency %3.3s not found.",
		*mlSkMess115 = "Discount breaks do not apply for item discounts.",
		*mlSkMess116 = "Discount breaks do not apply for customer discounts.",
		*mlSkMess117 = "Discount breaks do not apply for maximum category discounts.",
		*mlSkMess118 = "Pricing and Delivery Enquiry",
		*mlSkMess119 = "NOTE : Freight & insurance are in local currency.",
		*mlSkMess120 = "NOTE : Changes cannot be made as serial no. is not receipted.",
		*mlSkMess121 = "First quantity break may not be zero.",
		*mlSkMess122 = "Since the previously entered quantity was zero, this quantity should then be zero.",
		*mlSkMess123 = "Quantity Break %f should be greater than quantity break %f.",
		*mlSkMess124 = "Standard Cost Maintenance.",
		*mlSkMess125 = "%8.2f cannot be issued since there are only %8.2f on hand for item %s.  Continue [Y/N]?.",
		*mlSkMess126 = "Branch record for item not found.",
		*mlSkMess127 = "Write Off Stock.",
		*mlSkMess128 = "Category %s is allocated to tax code %s.",
		*mlSkMess129 = "Item %s is allocated to tax code %s.",
		*mlSkMess130 = "First rebate quantity may not be zero.",
		*mlSkMess131 = "Start date is before today. Accept [Y/N]?",
		*mlSkMess132 = "End date is before the cycle period.  Accept [Y/N]?",
		*mlSkMess133 = "Anticipated rebate % must be between 0 and 100.",
		*mlSkMess134 = "Rebate quantity %d should be less than rebate quantity %d.",
		*mlSkMess135 = "Rebate quantity %d should be greater than rebate quantity %d.",
		*mlSkMess136 = "Rebate value (pc) must be between 0 and 100.",
		*mlSkMess137 = "Usage : %s <program name> <program desc> [W/B].",
		*mlSkMess138 = "                  [2 or C] Customer By Category",
		*mlSkMess139 = "                  [3 or S] Customer By Selling Group",
		*mlSkMess140 = "                  [4 or T] Customer Type By Item",
		*mlSkMess141 = "                  [5 or U] Customer Type By Category",
		*mlSkMess142 = "                  [6 or V] Customer Type By Selling Group",
		*mlSkMess143 = "                  [7 or X] Price Type By Item",
		*mlSkMess144 = "                  [8 or Y] Price Type By Category",
		*mlSkMess145 = "                  [9 or Z] Price Type By Selling Group",
		*mlSkMess146 = "Display Accumulative Lead Time Report",
		*mlSkMess147 = "Accumulative Lead Time Print",
		*mlSkMess148 = "Sort code on warehouse record wrong.",
		*mlSkMess149 = "On order quantity out of balance.",
		*mlSkMess150 = "Committed quantity out of balance.",
		*mlSkMess151 = "Backorder quantity out of balance.",
		*mlSkMess152 = "Forward order quantity out of balance.",
		*mlSkMess153 = "On hand quantity out of balance.",
		*mlSkMess154 = "Location quantity out of balance.",
		*mlSkMess155 = "Serial item quantity out of balance.",
		*mlSkMess156 = "Lot quantity out of balance.",
		*mlSkMess157 = "Customer Rebate Claim Report.",
		*mlSkMess158 = "Customer Rebate Assignment Maintenance",
		*mlSkMess159 = "Rebate not found.",
		*mlSkMess160 = "Inventory Supplier Mass Update",
		*mlSkMess161 = "Update Suppliers from %-s to %-s",
		*mlSkMess162 = "Update items from %-s to %-s",
		*mlSkMess163 = "Update categories from %-s to %-s.",
		*mlSkMess164 = "Set FOB Cost = %s",
		*mlSkMess165 = "Set FOB Cost = FOB Cost %c %s",
		*mlSkMess166 = "Set Mimimum Order Quantity = %s",
		*mlSkMess167 = "Set Minimum Order Quantity = Minimum Order Quantity %c %s",
		*mlSkMess168 = "Set Normal Order Quantity = %s",
		*mlSkMess169 = "Set Normal Order Quantity = Normal Order Quantity %c %s",
		*mlSkMess170 = "Set Lead Time = %s",
		*mlSkMess171 = "Set Lead Time = Lead Time %c %s",
		*mlSkMess172 = "Where Lead Time Method = %s",
		*mlSkMess173 = "Where Suppliers from %-s to %-s",
		*mlSkMess174 = "and items from %-s to %-s",
		*mlSkMess175 = "and categories from %-s to %-s",
		*mlSkMess176 = "Where items from %-s to %-s",
		*mlSkMess177 = "and categories from %-s to %-s",
		*mlSkMess178 = "Where categories from %-s to %-s",
		*mlSkMess179 = "Enter FOB calculation        :",
		*mlSkMess180 = "Enter Min. Ord. calculation  :",
		*mlSkMess181 = "Enter Norm. Ord. calculation :",
		*mlSkMess182 = "Enter lead time calculation  :",
		*mlSkMess183 = "Please enter calculation as  : +,-,*,/,= value",
		*mlSkMess184 = "Update method not yet selected.",
		*mlSkMess185 = "Enter Start Supplier Number : ",
		*mlSkMess186 = "Enter End   Supplier Number : ",
		*mlSkMess187 = "Enter Start Item Number     : ",
		*mlSkMess188 = "Enter End Item Number       : ",
		*mlSkMess189 = "Enter Start Category Code   : ",
		*mlSkMess190 = "Enter End Category Code     : ",
		*mlSkMess191 = "Field calculation(s) not yet entered.",
		*mlSkMess192 = "Inter-Company transfers account for Co %s / Br %s not found.",
		*mlSkMess193 = "Stock transfers account for Co %s / Br %s not found.",
		*mlSkMess194 = "Duty payable control account for Co %s / Br %s not found.",
		*mlSkMess195 = "Freight control account for Co %s / Br %s not found.",
		*mlSkMess196 = "Usage : %s <lpno> <C(ompany)/B(ranch)>",
		*mlSkMess197 = "Usage : %s <pid> <lpno> <C(ompany)/B(ranch)>",
		*mlSkMess198 = "Display/Print Expired Lot/Batch Records",
		*mlSkMess199 = "Display Expired Lot/Batch as at %s",
		*mlSkMess200 = "Print Expired Lot/Batch as at %s",
		*mlSkMess201 = "Item not lot controlled.",
		*mlSkMess202 = "Lot no. %s does not exist for this item %s.",
		*mlSkMess203 = "Lot no. %s already exists for this item %s.",
		*mlSkMess204 = "Lot no. or expiry date already exists.",
		*mlSkMess205 = "Lot No. and Expiry Date Amendments",
		*mlSkMess206 = "Start Item : %-16.16s  End Item : %-16.16s",
		*mlSkMess207 = "BOM No. : %5d      RTG No. :%5d",
		*mlSkMess208 = "Detail/Summary : %-8.8s",
		*mlSkMess209 = "Usage : %s <lpno> <C(heck)/U(pdate)/A(ll Update)>",
		*mlSkMess210 = "Usage : %s <description>",
		*mlSkMess211 = "Stock take not allowed on item %s.",
		*mlSkMess212 = "%s is the stock code of item.",
		*mlSkMess213 = "   Item Number    |Base UOM|Total Qty Input ",
		*mlSkMess214 = "Stock Take Input",
		*mlSkMess215 = "Usage : %s <lpno> <start> <end> <print_type [G(roup)/I(tem No./A(BC Code)/L(ocation)/B(oth (L &I)]> <mode> <pid>",
		*mlSkMess216 = "BOM Alternate No. exceeds 32767.",
		*mlSkMess217 = "RTG Alternate No. exceeds 32767.",
		*mlSkMess218 = "Only %d prices set up.",
		*mlSkMess219 = "Rounding value cannot be entered since 'up to' value was not given.",
		*mlSkMess220 = "Rounding value must be less than 'up to' value.",
		*mlSkMess221 = "Warning : Rounding level is greater than 20%.",
		*mlSkMess222 = "This value must be larger than the previous value entered.",
		*mlSkMess223 = "This value must be lesser than the next value entered.",
		*mlSkMess224 = "Global Price Update",
		*mlSkMess225 = "Usage : %s <lpno> <Delete by [C(ompany)/B(ranch)/W(arehouse)]>",
		*mlSkMess226 = "Total may not exceed original total order quantity.",
		*mlSkMess227 = "Change all lines [Y/N]?",
		*mlSkMess228 = "Delete Transfer B(ackorders) U(nconfirmed Issues)",
		*mlSkMess229 = "Usage : %s <lpno> <reprint_flag [Y/N]> <trans_type> <[C/B/W]> <format_file>",
		*mlSkMess230 = "<reprint_flag> must be Y or N..",
		*mlSkMess231 = "<C/B/W> must be C(ompany)/B(ranch)/W(arehouse).",
		*mlSkMess232 = "Transfer no. %06ld not found.",
		*mlSkMess233 = "Transfer no. %06ld not for current branch.",
		*mlSkMess234 = "Reprint transfer [Y/N]?",
		*mlSkMess235 = "Transfers lineup selection.",
		*mlSkMess236 = "Stock Transfer Reprint Option",
		*mlSkMess237 = "Location Master Selection",
		*mlSkMess238 = "Quantity %14.6f greater than allowed quantity %f.",
		*mlSkMess239 = "Current Selection Code [%s] - %s",
		*mlSkMess240 = "Usage : %s <active_status> <lpno>\n",
		*mlSkMess241 = "Status : P(lanned), F(irmed), I(ssuing), A(llocated), R(eleased) and C(losing)",
		*mlSkMess242 = "Cannot produce company-wide forecast because branches are in different periods.  ",
		*mlSkMess243 = "Focus forecasting is at warehouse level only.",
		*mlSkMess244 = "%d transactions read.  Continue [Y/N]?",
		*mlSkMess245 = "QC options not set up.",
		*mlSkMess246 = " Company Stock Status Display ",
		*mlSkMess247 = "Warehouse Stock Status Display",
		*mlSkMess248 = "Description search can contain wild cards such",
		*mlSkMess249 = "as '*SL*' or 'LAM*' and each search is independent",
		*mlSkMess250 = "of the other so a match from search#1 or #2 will",
		*mlSkMess251 = "be displayed in the tag window.  Note that the",
		*mlSkMess252 = "wild card character is '*'.  Good luck %c%-11.11s",
		*mlSkMess253 = "Item Number:",
		*mlSkMess254 = "%R****<Location/Lot Records Selection>****",
		*mlSkMess255 = "1=Display by location type by location",
		*mlSkMess256 = "2=Display by location type by lot no.",
		*mlSkMess257 = "3=Display by location type by expiry date.",
		*mlSkMess258 = "4=Display by location type by fifo date.",
		*mlSkMess259 = "5=Display by UOM by location",
		*mlSkMess260 = "6=Display by UOM by lot no.",
		*mlSkMess261 = "Class :      %1.1s    Category  :      %-11.11s%15.15s",
		*mlSkMess262 = "Item ABC Code  :     %1.1s      :       Update (%-3.3s)%13.12s",
		*mlSkMess263 = "Costing (%s)          :       %s%8.8s",
		*mlSkMess264 = "Last Cost                   :       %s%8.8s",
		*mlSkMess265 = "Sales Month to Date         :       %12.12s%8.8s",
		*mlSkMess266 = "Sales Year to Date          :       %12.12s%8.8s",
		*mlSkMess267 = "QC Qty (Yes)                :        %14.14s%5.5s",
		*mlSkMess268 = "QC Qty (No )                :        %-14.14s%5.5s",
		*mlSkMess269 = "W/o Anticipated Qty         :        %-14.14s%5.5s",
		*mlSkMess270 = "Usage : %s <lpno> <U(pdate)/N(o update)>",
		*mlSkMess271 = "Average Cost                :       %s%8.8s",
		*mlSkMess272 = "Previous Cost               :       %s%8.8s",
		*mlSkMess273 = "Standard Cost               :       %s%8.8s",
		*mlSkMess274 = "Sale Unit :      %4.4s       Pack Size :      %5.5s%10.10s",
		*mlSkMess275 = "Sale UOM Conversion         :          %7.0f%10.10s",
		*mlSkMess276 = "Forecast Option             :     %12.12s%10.10s",
		*mlSkMess277 = "Forecast Method             :                %1.1s%10.10s",
		*mlSkMess278 = "Safety Stock                :        %11.2f%8.8s",
		*mlSkMess279 = "Weeks Demand                :        %11.2f%8.8s",
		*mlSkMess280 = "Last 12 Months Sales        :       %12.12s%8.8s",
		*mlSkMess281 = "Last 24 Months Sales        :       %12.12s%8.8s",
		*mlSkMess282 = "Item Short Code             :           %8.8s%8.8s",
		*mlSkMess283 = "Extra description code      :                %3.3s%8.8s",
		*mlSkMess284 = "Warehouse location          :         %10.10s%8.8s",
		*mlSkMess285 = "Backorders accepted         :                Yes%8.8s",
		*mlSkMess286 = "Backorders accepted         :      Full b/o only%8.8s",
		*mlSkMess287 = "Backorder release           :          Automatic%8.8s",
		*mlSkMess288 = "Discount %%                  :             %6.2f%8.8s",
		*mlSkMess289 = "Min Stock %8.2f  / Max Stock %8.2f%8.8s",
		*mlSkMess290 = "Tax %%      :   %6.2f%10.10s",
		*mlSkMess291 = "Last Wholesale Price        :          %9.9s%11.11s",
		*mlSkMess292 = "Stock Enquiry Selection Screen",
		*mlSkMess293 = "Stock Enquiry Display",
		*mlSkMess294 = "Buying Group Code Deletion",
		*mlSkMess295 = "Buying Group Code Maintenance",
		*mlSkMess296 = "Selling Group Code Deletion",
		*mlSkMess297 = "Selling Group Code Maintenance",
		*mlSkMess298 = "Usage : %s <description> <I(tem range)/ G(roup range)>",
		*mlSkMess299 = "Usage : %s <I(tem range)/G(roup range)> <start> <end> <BOM No.> <routing no.>",
		*mlSkMess300 = "type_flag : A(bove) B(elow)",
		*mlSkMess301 = "all_branches [Y/N]?",
		*mlSkMess302 = "Usage : %s <lpno> <group_by> <start> <end> <mgn_pc> <type_flag> <start_date> <end_date> <all_branches[Y/N]> <stat_flag>",
		*mlSkMess303 = "Usage : %s <L/F> <lpno>",
		*mlSkMess304 = "Quantity breaks available for this selection.",
		*mlSkMess305 = "Press <ENTER> to retrieve previously entered value.",
		*mlSkMess306 = "No quantity breaks set up.",
		*mlSkMess307 = "No quantity breaks permitted.",
		*mlSkMess308 = "Price By Q(uantity) or V(alue) Only",
		*mlSkMess309 = "Select Quantity Breaks To User For The",
		*mlSkMess310 = "Future Selling Price Adjustment",
		*mlSkMess311 = "Selling Price Maintenance By Customer Type and Item",
		*mlSkMess312 = "Active status not found.",
		*mlSkMess313 = "No base price is set up.",
		*mlSkMess314 = "Cannot enter price greater than 0.00.",
		*mlSkMess315 = "Prices cannot be maintained for a kit item.",
		*mlSkMess316 = "Prices cannot be maintained for a descriptive item.",
		*mlSkMess317 = "No future pricing records available for this file.",
		*mlSkMess318 = "Use Window-Activate Key 1 to alter quantity breaks.",
		*mlSkMess319 = "Active Status Maintenance",
		*mlSkMess320 = "Total material and resource costs [%8.2f] <> to standard cost [%8.2f]",
		*mlSkMess321 = "Must be > 0.00",
		*mlSkMess322 = "Must be >= 0.00",
		*mlSkMess323 = "Must be <= standard batch",
		*mlSkMess324 = "Must be >= standard batch or 0",
		*mlSkMess325 = "Standard cost [%8.2f] <> to total material and resource costs [%8.2f].",
		*mlSkMess326 = "Stock Branch Maintenance",
		*mlSkMess327 = "Standard Resource Breakdown Costs",
		*mlSkMess328 = "Standard batch : %14.6f  Pricing Conversion :%7.1f",
		*mlSkMess329 = "Actual Resource Breakdown Costs",
		*mlSkMess330 = "Inventory Master Delete",
		*mlSkMess331 = "Effective date must not be less than the inventory module date.",
		*mlSkMess332 = "Unable to load file because future pricing records were just created.",
		*mlSkMess333 = "Since the previously entered value was zero, this value should then be zero.",
		*mlSkMess334 = "Inventory Supplier Price Maintenance",
		*mlSkMess335 = "Minimum weight must be <= maximum weight",
		*mlSkMess336 = "Maximum weight must be >= minimum weight",
		*mlSkMess337 = "Minimum volume must be <= maximum volume",
		*mlSkMess338 = "Maximum volume must be >= minimum volume",
		*mlSkMess339 = "Cannot key F16 when a value has been entered.",
		*mlSkMess340 = "Global Price Maintenance",
		*mlSkMess341 = "Location Master File Maintenance",
		*mlSkMess342 = "Location Display",
		*mlSkMess343 = "Serial no. %s is valid but has not been receipted into store.",
		*mlSkMess344 = "Date not within the inventory module month.",
		*mlSkMess345 = "Item screen is not balance to general ledger.",
		*mlSkMess346 = "Stock Receipts",
		*mlSkMess347 = "Stock Purchase",
		*mlSkMess348 = "Stock Purchase (On-line)",
		*mlSkMess349 = "Stock Issues",
		*mlSkMess350 = "Stock Adjustments",
		*mlSkMess351 = "Journal Total - (%3.3s)",
		*mlSkMess352 = "Debit Total - (%3.3s)",
		*mlSkMess353 = "Credit Total - (%3.3s)",
		*mlSkMess354 = "Inventory Note Pad Input",
		*mlSkMess355 = "Misc. stock receipts control account",
		*mlSkMess356 = "Misc. stock issues control account",
		*mlSkMess357 = "Maintain Life to Date Sales",
		*mlSkMess358 = "Cur. Weight : %9.2f",
		*mlSkMess359 = "No Picks    : %9.2f",
		*mlSkMess360 = "Access      : %-30.30s",
		*mlSkMess361 = "Loc. Type   : %-30.30s",
		*mlSkMess362 = "Location    : %s (%40.40s)",
		*mlSkMess363 = "Min. Weight : %9.2f               Max Weight   : %9.2f",
		*mlSkMess364 = "No warehouse record for issuing item.",
		*mlSkMess365 = "Usage : %s <lpno> <start> <end> <print_type [G(roup)/I(tem No.)]> <mode>",
		*mlSkMess366 = "Supercessions Maintenance",
		*mlSkMess367 = "Supplier Rebate Claim Report",
		*mlSkMess368 = "Supplier Rebate Claim Report  - Reprint",
		*mlSkMess369 = "Usage : %s <lpno> <start> <end> <end_of_year_date>",
		*mlSkMess370 = "Stock take is already in user for warehouse %s.",
		*mlSkMess371 = "Stock Take Selection %-s",
		*mlSkMess372 = "As your system is set up to create stock take selection",
		*mlSkMess373 = "at the time of freezing stock this option is invalid for you.",
		*mlSkMess374 = "However if this should not be the case you will need to change",
		*mlSkMess375 = "the environment variable SK_ST_PFRZ.",
		*mlSkMess376 = "Key <return> to continue.",
		*mlSkMess377 = "Your system is set to allow stock take selection to be",
		*mlSkMess378 = "created before stock is frozen.  The only exception to",
		*mlSkMess379 = "this is serial items which must be frozen before any options",
		*mlSkMess380 = "are used.  For additional details refer to your manual.",
		*mlSkMess381 = "Stock take options you can run before stock is frozen:",
		*mlSkMess382 = "a) Stock take sheet print (all options)",
		*mlSkMess383 = "b) Stock take count input (all options)",
		*mlSkMess384 = "The following options cannot be run until stock is frozen:",
		*mlSkMess385 = "a) Stock take valuation reports",
		*mlSkMess386 = "b) Stock take variation reports",
		*mlSkMess387 = "c) Stock take update",
		*mlSkMess388 = "Prices cannot be maintained for a kit item.",
		*mlSkMess389 = "Prices cannot be maintained for a descriptive item.",
		*mlSkMess390 = "Default price not found.",
		*mlSkMess391 = "Prices already specified for this currency.",
		*mlSkMess392 = "Records may overlap.  This will depend on currencies chosen.",
		*mlSkMess393 = "Promotional Pricing Maintenance",
		*mlSkMess394 = "Pricing Customer by Item",
		*mlSkMess395 = "Pricing by Customer Type by Item",
		*mlSkMess396 = "Pricing by Item",
		*mlSkMess397 = "New Inventory Prices",
		*mlSkMess398 = "Confirm complete transfer [Y/N]?",
		*mlSkMess399 = "Transfer number must be input.",
		*mlSkMess400 = "Transfer no. %ld already exists.",
		*mlSkMess401 = "Default must be used for two-step transfers.",
		*mlSkMess402 = "Transfer no. has been completed.",
		*mlSkMess403 = "Confirmed stock being receipted into wrong co/branch/warehouse.",
		*mlSkMess404 = "Confirmed stock being receipted into wrong branch/warehouse.",
		*mlSkMess405 = "Only issuing co/branch can confirm the transfer.",
		*mlSkMess406 = "Only issuing branch can confirm the transfer.",
		*mlSkMess407 = "Full quantity must be supplied or backordered for this item.",
		*mlSkMess408 = "Class 'Z' (descriptive items) cannot have quantity.",
		*mlSkMess409 = "Phantom item is shown for reference only.  Quantity cannot be input.",
		*mlSkMess410 = "Supply order in full to %s [Y/N]?",
		*mlSkMess411 = "Quantity set to zero.  Allocated serial item cleared.",
		*mlSkMess412 = "Receipt quantity %s though %s was issued [Y/N]?",
		*mlSkMess413 = "Quantity ordered must be 0.00 since quantity backordered is 1.00.",
		*mlSkMess414 = "Quantity backordered must be 0.00 since quantity ordered is 1.00.",
		*mlSkMess415 = "Quantity ordered and quantity supplied are both 0.00.",
		*mlSkMess416 = "Serial nos. may be input since order quantity is 0.00.",
		*mlSkMess417 = "NOTE : No docket will be printed because all lines have 0.00 quantity.",
		*mlSkMess418 = "NOTE : No docket will be printed because all lines are backordered. ",
		*mlSkMess419 = "Warehouse record for item not found.",
		*mlSkMess420 = "Iss From BR%s/WH%s",
		*mlSkMess421 = "Rec into BR%s/WH%s",
		*mlSkMess422 = "Duty Pay BR%s/WH%s",
		*mlSkMess423 = "Freight BR%s/WH%s",
		*mlSkMess424 = "Warning : Transfer being receipted into Co/Branch/Warehouse not originally specified.  Continue [Y/N]?",
		*mlSkMess425 = "Looping supercession, check item %s.",
		*mlSkMess426 = "Looping alternate, check item %s.",
		*mlSkMess427 = "Corrupt supercession, check item %s.",
		*mlSkMess428 = "Corrupt alternate, check item %s.",
		*mlSkMess429 = "Item %s is the master alternate of item %s.",
		*mlSkMess430 = "Supply line in full to %s [Y/N]? ",
		*mlSkMess431 = "Line is part of a full supply order.",
		*mlSkMess432 = "Cannot create transfer without line details.",
		*mlSkMess433 = "Item for receiving company not found.",
		*mlSkMess434 = "Warehouse record for item  for issuing branch not found.",
		*mlSkMess435 = "Item not found for receiving warehouse.  Create [Y/N]?",
		*mlSkMess436 = "Receiving branch record for item not found.",
		*mlSkMess437 = "This line is a full supply line.",
		*mlSkMess438 = "Transfer for %s / Line status : %s %s",
		*mlSkMess439 = "Last Tran. No.: %s",
		*mlSkMess440 = "Serial Item Display",
		*mlSkMess441 = "Search by I(tem No.) or A(lpha code)",
		*mlSkMess442 = "Date received :  %10.10s",
		*mlSkMess443 = "Date issued   :  %10.10s",
		*mlSkMess444 = "Estimated Cost : %10.2f",
		*mlSkMess445 = "Actual Cost   : %10.2f",
		*mlSkMess446 = "Status        : %1.1s",
		*mlSkMess447 = "Customer No.  : %-6.6s",
		*mlSkMess448 = "Sales Order No. : %-8.8s",
		*mlSkMess449 = "Invoice No.  : %-8.8s",
		*mlSkMess450 = "Purchase Order No. : %7.7s",
		*mlSkMess451 = "Goods Receipt No. : %7.7s",
		*mlSkMess452 = "Location   : %10.10s",
		*mlSkMess453 = "Last Serial No. : %-25.25s",
		*mlSkMess454 = "Stock code of item is %s.",
		*mlSkMess455 = "Serial item not found.  Include in stock take [Y/N]?",
		*mlSkMess456 = "Cannot edit the cost of an existing stock take record.",
		*mlSkMess457 = "Stock Take Serial Input",
		*mlSkMess458 = "Current Selection Code [%s] - %s",
		*mlSkMess459 = "Cannot supply a branch from itself.",
		*mlSkMess460 = "Warning : UOM could calculate quantity greater than dec_pt %d.  Continue [Y/N]?",
		*mlSkMess461 = "Item for warehouse %s is as priority %s.",
		*mlSkMess462 = "Item for Supplier %s is as priority %s.",
		*mlSkMess463 = "Inventory Supplier Maintenance",
		*mlSkMess464 = "Supplier Rebate Assignment Maintenance",
		*mlSkMess465 = "Valid rebates for selected Supplier not found.",
		*mlSkMess466 = "QC Checking Required : Yes",
		*mlSkMess467 = "QC Checking Required : No",
		*mlSkMess468 = "Maintain Warehouse Items ",
		*mlSkMess469 = "Conflicts with existing record dated from %s to %s.",
		*mlSkMess470 = "Update lower level manufactured component items [ Y(es / N(o / A(bort ]?",
		*mlSkMess471 = "Accumulative Lead Time Calculation",
		*mlSkMess472 = "Corrupt superceded.  Check item.",
		*mlSkMess473 = "Synonym Stocking Item Maintenance",
		*mlSkMess474 = "Controlled drug categories not found.",
		*mlSkMess475 = "Issue of Controlled Drugs Report",
		*mlSkMess476 = "Cannot delete a line that is included for updating.  Untag first.",
		*mlSkMess477 = "Customer Pricing Mass Quantity Break Update",
		*mlSkMess478 = "Environment for quantity breaks not set up. Press any key.",
		*mlSkMess479 = "Usage : %s <lpno> <C(heck)/U(pdate)>",
		*mlSkMess480 = "Category does not allow products to be allocated to it.",
		*mlSkMess481 = "Price is inclusive of GST.  GST percent must be 0.00.",
		*mlSkMess482 = "If ALT UOM %s is desired then set dec_pt greater than %d.",
		*mlSkMess483 = "Stock Indent Master Maintenance",
		*mlSkMess484 = "Last No. %-16.16s",
		*mlSkMess485 = "Inventory Movements Audit Display",
		*mlSkMess486 = "Lot Quantities Discrepancies Report",
		*mlSkMess487 = "Lot & Bin Location Quantities Discrepancies Report",
		*mlSkMess488 = "Cannot delete location since %10.2f %s of items still on hand.",
		*mlSkMess489 = "Stock Bin Location Delete",
		*mlSkMess490 = "Mass Supplier Quantity Breaks/Cost Maintenance",
		*mlSkMess491 = "Qty Break 1: ",
		*mlSkMess492 = "Qty Break 2: ",
		*mlSkMess493 = "Qty Break 3: ",
		*mlSkMess494 = "Qty Break 4: ",
		*mlSkMess495 = "Qty Break 5: ",
		*mlSkMess496 = "Update Stock Transactions...",
		*mlSkMess497 = "Standard Rollup Calculation",
		*mlSkMess498 = "Stock take selection delete",
		*mlSkMess499 = "Update lower level manufactured component items [ Y(es / N(o / A(bort ]?",
		*mlSkMess500 = "Inventory %-3.3s Update",
		*mlSkMess501 = "Inventory Message Code Maintenance",
		*mlSkMess502 = "%s Stock Issue Requests",
		*mlSkMess503 = "or      %s U <period> <lpno> <T(ransit)/B(ackorder)>",
		*mlSkMess504 = "Usage : %s <report level> OR",
		*mlSkMess505 = "Warehouse Stock Status Display",
		*mlSkMess506 = "Usage : sk_cdrg_inp <description> <posted_flags>",
		*mlSkMess507 = " or   : sk_cdrg_prn <lpno> <start date> <end date> <posted flags>",
		*mlSkMess508 = "Usage : %s <lpno> <I(ss)/R(ec)/P(ur)>",
		*mlSkMess509 = "Usage : %s <start item> <end item> <level [C(ompany)/B(ranch)/W(arehouse)]> <lpno>",
		*mlSkMess510 = "Usage : %s <lpno> <start> <end> <print_type [G(roup)/I(tem No.)/L(ocation)]> <mode>",
		*mlSkMess511 = "Usage : %s <lpno> <I(tem)/C(ategory)>",
		*mlSkMess512 = "Usage : %s <lpno> <format file>",
		*mlSkMess513 = "Usage : %s <I(nput)/P(rint)> <lpno>",
		*mlSkMess514 = "Inventory Master File",
		*mlSkMess515 = "Branch/Warehouse File",
		*mlSkMess516 = "Fifo/Lifo Records",
		*mlSkMess517 = "Serial Number Records",
		*mlSkMess518 = "Invoice Details",
		*mlSkMess519 = "P/Order Details",
		*mlSkMess520 = "Sales Order Details",
		*mlSkMess521 = "Stock Transactions",
		*mlSkMess522 = "History Details",
		*mlSkMess523 = "Sales Analysis",
		*mlSkMess524 = "Inventory Supplier",
		*mlSkMess525 = "Superceding %s to %s ",
		*mlSkMess526 = "Item %s is already superceeded in master file.",
		*mlSkMess527 = "Cannot superceed an item onto itself.",
		*mlSkMess528 = "Costing types do not match.",
		*mlSkMess529 = "Items must be both serial or non-serial.",
		*mlSkMess530 = "Invalid end of year date.",
		*mlSkMess531 = "Item is not a manufactured item.",
		*mlSkMess532 = "Item %s is already superceded by item %s.",
		*mlSkMess533 = "Item %s is an alternate/synonym for item %s.",
		*mlSkMess534 = "Location %s is not found for uom %s.",
		*mlSkMess535 = "Effective date > expiry date",
		*mlSkMess536 = "Effective date < current date",
		*mlSkMess537 = "Expiry date <= effective date",
		*mlSkMess538 = "Cost must be 0.00 since quantity break is 0.00.",
		*mlSkMess539 = "Supplier/inventory record not found.  Cannot set up Supplier/quantity costs.",
		*mlSkMess540 = "Quantity breaks for this Supplier/item not found. Press <ENTER> or press <RESTART> to abort entry of this item.",
		*mlSkMess541 = "Cannot tag a line that is included for deletion.  Untag first.",
		*mlSkMess542 = "Serial costing type requires a serial item.",
		*mlSkMess543 = "Base indent no. must contain the word 'INDENT'.",
		*mlSkMess544 = "Inventory Lead-Date Maintenance",
		*mlSkMess545 = "Supplier %s does not supply item %s.",
		*mlSkMess546 = "Warehouse %s does not supply item %s.",
		*mlSkMess547 = "Cannot supply before ordering.",
		*mlSkMess548 = "Item same as master item",
		*mlSkMess549 = "Duplicate alternate/synonym item.",
		*mlSkMess550 = "Selling group not found.",
		*mlSkMess551 = "Buying group not found.",
		*mlSkMess552 = "Invalid source.",
		*mlSkMess553 = "Conversion factor is zero for items unit of measure.",
		*mlSkMess554 = "Item is not a manufactured item.",
		*mlSkMess555 = "File code not found.",
		*mlSkMess556 = "Class not found.",
		*mlSkMess557 = "Item %s has already been entered for deletion.",
		*mlSkMess558 = "Item has been discontinued.",
		*mlSkMess559 = "Duplicate serial number.",
		*mlSkMess560 = "Item numer %s is not a serial item.",
		*mlSkMess561 = "Conversion factor must be greater than zero.",
		*mlSkMess562 = "Serial no %s does not belong to current company.",
		*mlSkMess563 = "Total ",
		*mlSkMess564 = "Standard Rollup Print",
		*mlSkMess565 = "No valid lines.",
		*mlSkMess566 = "Are you sure you want to delete global price file?",
		*mlSkMess567 = "Future prices already exist.  Previous data will be lost if you proceed.",
		*mlSkMess568 = "Cannot update live prices with this global price file because date is not yet effective. Press any key.",
		*mlSkMess569 = "Cannot update live prices with this global price file because no future prices have been created.  Press any key.",
		*mlSkMess570 = "Are you sure you want to update live prices?",
		*mlSkMess571 = "Prices for printing not found. Press any key.",
		*mlSkMess572 = "Usage : %s <hhbr_hash>",
		*mlSkMess573 = "<print_type - G(roup)>",
		*mlSkMess574 = "Usage : %s <lpno> <start> <end> <print_type [G(roup)/I(tem No./A(BC Code)/L(ocation)]> <mode>",
		*mlSkMess575 = "%s Daily Stock Transfer Receipts as at %-10.10s",
		*mlSkMess576 = "%s Daily Stock Transfer Issues as at %-10.10s",
		*mlSkMess577 = "Print Daily Stock Transfer Receipts as at %-10.10s",
		*mlSkMess578 = "Print Daily Stock Transfer Issues as at %-10.10s",
		*mlSkMess579 = "Print Stock Issue Requests Report as at %-10.10s",
		*mlSkMess580 = "%R Stock Write-off Reason Maintenance",
		*mlSkMess581 = "Blank codes are not allowed.",
		*mlSkMess582 = "Account must be a financial posting class.",
		*mlSkMess583 = "Item for receiving warehouse not found. Create [Y/N]?",
		*mlSkMess584 = "Debit Account  : %s",
		*mlSkMess585 = "Credit Account : %s",
		*mlSkMess586 = "Iss Branch : %2.2s %-40.40s",
		*mlSkMess587 = "Inventory Transfers In and Out",
		*mlSkMess588 = "Usage : %s <lpno> optional <dflt_dbt> <dflt_crd>",
		*mlSkMess589 = "Print All Stock Transfer Receipts Report",
		*mlSkMess590 = "Print All Stock Transfer Issues Report",
		*mlSkMess591 = "Print Daily Stock Issue Requests as at %-10.10s Report",
		*mlSkMess592 = "Descriptive item may not be alternate.",
		*mlSkMess593 = "Alternate may not be the same as the item number.",
		*mlSkMess594 = "Category does not allow products to be allocated to it.",
		*mlSkMess595 = "Supercession Maintenance must be used to supercede items.",
		*mlSkMess596 = "Pricing / Costing Unit      :          %7.0f %-10.10s",
		*mlSkMess597 = "Selling price must not be less than 0.00.",
		*mlSkMess598 = "Price is inclusive of %-3.3s. %-3.3s percent should be 0.00.",
		*mlSkMess599 = "Pricing factor must be >= 1.00.",
		*mlSkMess600 = "Item has already been added to the inventory master file.",
		*mlSkMess601 = "Inventory Supplier record was not added due to duplicates.",
		*mlSkMess602 = "Stock Master Maintenance",
		*mlSkMess603 = "Item No.: %s %s",
		*mlSkMess604 = "OR    : %s <Type [B/S/C[> <Updated [Y/N/A]> <start> <end> <lpno>",
		*mlSkMess605 = "This code is assigned to a selling group.",
		*mlSkMess606 = "Customer Inventory Default Quantity Break Report",
		*mlSkMess607 = "Master %05d / Branch %05d / W/H:%05d / Trans:%05d",
		*mlSkMess608 = "Deleting Inventory Records",
		*mlSkMess609 = "Master File",
		*mlSkMess610 = "Status Information",
		*mlSkMess611 = "Enter 1-5?",
		*mlSkMess612 = "Backorders accepted   :  No%10.10s",
		*mlSkMess613 = "Backorder release     :  Manual   %10.10s",
		*mlSkMess614 = "Branch Records",
		*mlSkMess615 = "Warehouse Records",
		*mlSkMess616 = "Item has no warehouse record for issuing branch.",
		*mlSkMess617 = "Usage : %s <D(elete)/N(ormal)>",
		*mlSkMess618 = "Latest Cost Update",
		*mlSkMess619 = "Group by : I(nventory)/C(ustomer)",
		*mlSkMess620 = "Incomplete Transfer Issues/Receipts Report",
		*mlSkMess621 = "Rec Branch : %2.2s %-40.40s",
		*mlSkMess622 = "Receiving branch/warehouse cannot be equal to issuing branch/warehouse.",
		*mlSkMess623 = "UOM: %-4.4s %-20.20s.",
		*mlSkMess624 = "Months",
		*mlSkMess625 = "Item Description: %s",
		*mlSkMess626 = "Usage : %s <pid> <C(ompany)/B(ranch)/W(arehouse)>",
		*mlSkMess627 = "No Hits      : %9.2f.",
		*mlSkMess628 = "Stock Location Display",
		*mlSkMess629 = "Usage : %s <lpno> <G(eneral)/J(ournal Entry)> <R(eceipt)/P(urchase)/I(ssue)/O(nline Purchase)/A(djustments)>",
		*mlSkMess630 = "Usage : %s <N(ormal)/S(erial)>",
		*mlSkMess631 = "Prices for this customer and item not found.",
		*mlSkMess632 = "Supplier %s already exists on line %d.",
		*mlSkMess633 = "Item must be a raw material (source RM).",
		*mlSkMess634 = "Iss Company : %s %s",
		*mlSkMess635 = "Rec Company : %s %s",
		*mlSkMess636 = "Usage : %s <progname> <select type [G(roup)/I(tem No.)/A(BC Codes)/L(ocation)/F(reeze)/B(oth L & I)>",
		*mlSkMess637 = "Usage : %s <[(1 or C)Customer By Item/(2 or T)Customer Type By Item/(3 or I)Item] [(4 or A(rea by item by customer>",
		*mlSkMess638 = "Usage : %s <lpno><start group> <end group> <C/B/W && D/S>",
		*mlSkMess639 = "Usage : %s <lpno>",
		*mlSkMess640 = "        <type ",
		*mlSkMess641 = "           [RI (Remote Issue)",
		*mlSkMess642 = "            ID (Issue Direct)",
		*mlSkMess643 = "            IO (Issue One Step",
		*mlSkMess644 = "            IT (Issue Two Step)",
		*mlSkMess645 = "		    IR (Issue Request)",
		*mlSkMess646 = "		    RC (Request Confirm)",
		*mlSkMess647 = "		    IC (Issue Confirmation)",
		*mlSkMess648 = "		    RE (Receipt)",
		*mlSkMess649 = "		    TD (Transfer Display)]> ",
		*mlSkMess650 = "		<format file {userd by sk_trnprt}> ",
		*mlSkMess651 = "	    <duty [Y(es, included)/N(o, not relevant)>",
		*mlSkMess652 = "Inter - Company",
		*mlSkMess653 = "Transfer Receipts",
		*mlSkMess654 = "(Remote) Transfer Issues",
		*mlSkMess655 = "(Direct) Transfer Issues",
		*mlSkMess656 = "(One-Step) Transfer Issues",
		*mlSkMess657 = "(Two-Step) Transfer Issues",
		*mlSkMess658 = "Request For Transfer",
		*mlSkMess659 = "Tranfer Request Confirmation",
		*mlSkMess660 = "Tranfer Despatch Confirmation",
		*mlSkMess661 = "Stock  Transfer Display",
		*mlSkMess662 = "Usage : %s <lpno> <days> <trans_no> <print [Y/N]>",
		*mlSkMess663 = "Duplicate short code.",
		*mlSkMess664 = "Invalid source.",
		*mlSkMess665 = "Extra description not found.",
		*mlSkMess666 = "Grade not found.",
		*mlSkMess667 = "Active Status Report Selection",
		*mlSkMess668 = "NOTE Exact match not found.",
		*mlSkMess669 = "Customer Rebate Claim Report Reprint",
		*mlSkMess670 = " <select type [G(roup)/I(tem No.)/A(BC Codes)/L(ocation)/F(reeze)/B(oth L & I)>",
		*mlSkMess671 = "%s (C)ancel%s %s (D)isplay%s",
		*mlSkMess672 = "%s (O)verride%s %s (C)ancel%s %s (R)educe%s %s (D)isplay%s",
		*mlSkMess673 = "%s (S)ubstitute%s",
		*mlSkMess674 = "%s (F)orce b/o%s",
		*mlSkMess675 = "%s (B)ackorder bal%s %s (F)orce b/o%s",
		*mlSkMess676 = "Set New Break Levels",
		*mlSkMess677 = "Price By :",
		*mlSkMess678 = "Qty Break %1d :",
		*mlSkMess679 = "Value    ",
		*mlSkMess680 = "Quantity",
		*mlSkMess681 = "Price By Value",
		*mlSkMess682 = "Price By Quantity",
		*mlSkMess683 = "Select Quantity  Breaks to use for the %s Price",
		*mlSkMess684 = "%s Prices :",
		*mlSkMess685 = "Old Quantity Breaks - ",
		*mlSkMess686 = "New Quantity Breaks - ",
		*mlSkMess687 = "Old Prices - ",
		*mlSkMess688 = "New Prices - ",
		*mlSkMess689 = "Print Stock Issue Requests Report",
		*mlSkMess690 = "Opening stock at warehouse is non zero.",
		*mlSkMess691 = "Receipts at warehouse are non zero.",
		*mlSkMess692 = "Purchases at warehouse are non zero.",
		*mlSkMess693 = "Issues at warehouse are non zero.",
		*mlSkMess694 = "Adjustments at warehouse are non zero.",
		*mlSkMess695 = "Sales at warehouse are non zero.",
		*mlSkMess696 = "Closing stock at warehouse is non zero.",
		*mlSkMess697 = "Company stock on hand is non zero",
		*mlSkMess698 = "Warehouse Records still on file for Item",
		*mlSkMess699 = "Branch Records still on file for Item",
		*mlSkMess700 = "Sales Orders exist for item.",
		*mlSkMess701 = "Invoice/Packing slips exist for item.",
		*mlSkMess702 = "Live Goods receipts lines exist for item.",
		*mlSkMess703 = "Purchase Orders exist for item.",
		*mlSkMess704 = "Transfers still exist for item.",
		*mlSkMess705 = "Can not Delete, Buying Group Record In Use In The Inventory Master File.",
		*mlSkMess706 = "Can not Delete, Selling Group Record In Use In The Inventory Master File.",
		*mlSkMess707 = "Last",
		*mlSkMess708 = "Average",
		*mlSkMess709 = "FIFO",
		*mlSkMess710 = "LIFO",
		*mlSkMess711 = "Serial",
		*mlSkMess712 = "Unknown",
		*mlSkMess713 = "NOTE : SYNONYM STOCKING ITEM                   ",
		*mlSkMess714 = "Miscellaneous Stock issue and receipt types.",
		*mlSkMess715 = "Supply lines within Branch must be Warehouse-Specific",
		*mlSkMess716 = "Not Last / Avge / FIFO / LIFO Costed",
		*mlSkMess717 = "An entry for that location already exists.",
		*mlSkMess718 = "Location code %s is already allocated to sort value %s",
		*mlSkMess719 = "Location Sort Maintenance.",
		*mlSkMess720 = "Minimum Stock Level         :           %8.2f        ",
		*mlSkMess721 = "Maximum Stock Level         :           %8.2f        ",
		*mlSkMess722 = "Pricing Customer by Area By Item";
#endif	
