/*=====================================================================
|  Copyright (C) 1999 - 2000 LogisticSoftware                         |
|=====================================================================|
| $Id: ml_utils_mess.h,v 5.0 2001/06/19 06:51:46 cha Exp $
-----------------------------------------------------------------------
| $Log: ml_utils_mess.h,v $
| Revision 5.0  2001/06/19 06:51:46  cha
| LS10-5.0 New Release as of 19 JUNE 2001
|
| Revision 4.0  2001/03/09 00:59:27  scott
| LS10-4.0 New Release as at 10th March 2001
|
| Revision 3.1  2000/12/12 04:50:05  scott
| Updated to place strings back into include file so plook and other utils work
|
*/
#ifndef	ML_UTILS_MESS_H
#define	ML_UTILS_MESS_H

char	*mlUtilsMess001 = "Save changes to security file [Y/N]?",
		*mlUtilsMess002 = "Saving security file ....",
		*mlUtilsMess003 = "Security Maintenance",
		*mlUtilsMess004 = "Update File = (%s)",
		*mlUtilsMess005 = "L O G I S T I C  T A B L E  E D I T O R",
		*mlUtilsMess006 = "L O G I S T I C  T A B L E  V I E W E R",
		*mlUtilsMess007 = "%R The limits of this initial version of pinform have been exceeded.",
		*mlUtilsMess008 = "%R There are no rows in the current list.",
		*mlUtilsMess009 = "%R There are no more rows in the direction you are going.",
		*mlUtilsMess010 = "%R Please enter desired record number.",
		*mlUtilsMess011 = "%R The selected record is not in the current list.",
		*mlUtilsMess012 = "%R Cannot create a new row.",
		*mlUtilsMess013 = "%R Cannot read record from file for update/remove.",
		*mlUtilsMess014 = "%R This row has been locked by another user.  Try again later.",
		*mlUtilsMess015 = "%R Cannot update this row.",
		*mlUtilsMess016 = "Record %6ld of %6ld",
		*mlUtilsMess017 = "Delete this entry?",
		*mlUtilsMess018 = "Please enter 'Y' to update prntype or 'N' to continue editing.",
		*mlUtilsMess019 = "Write to %s?",
		*mlUtilsMess020 = "Updating %s",
		*mlUtilsMess021 = "Printcap %s does not exist.",
		*mlUtilsMess022 = "Prntype Maintenance",
		*mlUtilsMess023 = "You must be a superuser to run this program.",
		*mlUtilsMess024 = "Saving user specific hot key selection.",
		*mlUtilsMess025 = "Deleting user specific hot key selection.",
		*mlUtilsMess026 = "Program Security Maintenance",
		*mlUtilsMess027 = "Environment Variable Maintenance",
		*mlUtilsMess028 = "%R Background Process Monitor",
		*mlUtilsMess029 = "One Step P/Slip",
		*mlUtilsMess030 = "Two Step P/Slip",
		*mlUtilsMess031 = "Stock Update",
		*mlUtilsMess032 = "Recalc Of Stock",
		*mlUtilsMess033 = "Recalc Of Customers",
		*mlUtilsMess034 = "Misc. BG Records",
		*mlUtilsMess035 = "%R Number Records %4d",
		*mlUtilsMess036 = "%R Number Passes %5d",
		*mlUtilsMess037 = "Access permitted.",
		*mlUtilsMess038 = "Access denied.",
		*mlUtilsMess039 = "Date of last revision of codes was %s.",
		*mlUtilsMess040 = "Error code of 0 means command was executed successfully.",
		*mlUtilsMess041 = "Error code of %d means %s.",
		*mlUtilsMess042 = "Error code not found.",
		*mlUtilsMess043 = "LICENSE modified.",
		*mlUtilsMess044 = "LICENSE not modified.",
		*mlUtilsMess045 = "Bad serial number not accepted.",
		*mlUtilsMess046 = "%R LogisticSoftware License Maintenance",
		*mlUtilsMess047 = "CLIENT KEY   : (%ld)",
		*mlUtilsMess048 = "Please fax a SERIAL NUMBER REQUEST FORM to LogisticSoftware.",
		*mlUtilsMess049 = "LogisticSoftware will supply a serial number to be keyed in below.",
		*mlUtilsMess050 = "Please make sure that you key in Upper/Lower case characters as supplied.",
		*mlUtilsMess051 = "Illegal serial number.  Please re-enter.",
		*mlUtilsMess052 = "Cannot open %s for reading.",
		*mlUtilsMess053 = "Variable - %s",
		*mlUtilsMess054 = "U)pdate, I)gnore Changes, D)elete?",
		*mlUtilsMess055 = "Background Process Maintenance",
		*mlUtilsMess056 = "Use cursor keys to position highlight bar.",
		*mlUtilsMess057 = "Press [ENTER] to run or [EDIT/END] to exit.",
		*mlUtilsMess058 = "chk_env (%s) = %s",
		*mlUtilsMess059 = "Total records: %-lu",
		*mlUtilsMess060 = "Executing Query .... Press <DEL> to abort.",
		*mlUtilsMess061 = "Code   :     Message     (Last updated on %s) ",
		*mlUtilsMess062 = "Duplicate environment variable name",
		*mlUtilsMess063 = "Save changes to environment [Y/N]?",
		*mlUtilsMess064 = "Saving old environment [Y/N]?",
		*mlUtilsMess065 = "Saving new environment [Y/N]?",
		*mlUtilsMess066 = "Caret : %s",
		*mlUtilsMess067 = "Access Code %s not found.",
		*mlUtilsMess068 = "User : ",
		*mlUtilsMess069 = "Queue : ",
		*mlUtilsMess070 = "Class : ",
		*mlUtilsMess071 = "Printer Security",
		*mlUtilsMess072 = "Night Processing Reports Display",
		*mlUtilsMess073 = "Night processing file unchanged ...",
		*mlUtilsMess074 = "There is no program in the night stream.",
		*mlUtilsMess075 = "All required escape sequences have not been entered.  Please confirm update.",
		*mlUtilsMess076 = "Please enter 'Y' to update printcap or 'N' to continue editing.",
		*mlUtilsMess077 = "Printcap Maintenance",
		*mlUtilsMess078 = "Modified ...",
		*mlUtilsMess079 = "Cannot open %s",
		*mlUtilsMess080 = "Table : %s (%d fields, %d indexes)",
		*mlUtilsMess081 = "%d error codes printed.",
		*mlUtilsMess082 = "Specified report data exceeds maximum report width of %d chars.",
		*mlUtilsMess083 = "Invalid field.",
		*mlUtilsMess084 = "Deleting Line...",
		*mlUtilsMess085 = "Inserting Line...",
		*mlUtilsMess086 = "Field must be selected to run report.",
		*mlUtilsMess087 = " Customer User Report ",
		*mlUtilsMess088 = " Inventory User Report ",
		*mlUtilsMess089 = " Supplier User Report ",
		*mlUtilsMess090 = " Company Branch  Program         Status      Date     Time      PID     Lpno ",
		*mlUtilsMess091 = "Option : ",
		*mlUtilsMess092 = "No available options in bacground file.",
		*mlUtilsMess093 = "Background Processing Control",
		*mlUtilsMess094 = "Menu option does not exist or an error occured while executing program.",
		*mlUtilsMess095 = "If menu option has not been used before then your supplier will need to",
		*mlUtilsMess096 = "release to you all relevant program(s) to allow this option to be used.",
		*mlUtilsMess097 = "Please refer to Operating System Manual for full details.",
		*mlUtilsMess098 = "A possible Kernel change maybe required if error has occured before.",
		*mlUtilsMess099 = "No description has been found for the current error.",
		*mlUtilsMess100 = "Please press [PRINT] to print error or [INPUT/END] to exit.",
		*mlUtilsMess101 = "******* LOGISTIC INTERNAL ERROR LOGGING *******",
		*mlUtilsMess102 = "Menu Option : %s ",
		*mlUtilsMess103 = "Program : %s (%s)",
		*mlUtilsMess104 = "Desc : %s (%d)",
		*mlUtilsMess105 = "S y s t e m  D e s c r i p t i o n  o f  E r r o r s",
		*mlUtilsMess106 = "%c%s please note that your error (%d) has been logged.",
		*mlUtilsMess107 = "Service call must be logged with your supplier.",
		*mlUtilsMess108 = "Open error [%d] on device %s.",
		*mlUtilsMess109 = "Report Width : %3d",
		*mlUtilsMess110 = "%s no such file.",
		*mlUtilsMess111 = " Display (%s) (%d/%d) : ",
		*mlUtilsMess112 = "Error (%d) has been logged.",
		*mlUtilsMess113 = "Directory Listings",
		*mlUtilsMess114 = "Please enter 'Y' to update termcap or 'N' to continue editing.",
		*mlUtilsMess115 = "New Termcap",
		*mlUtilsMess116 = "Instructions",
		*mlUtilsMess117 = "For ESCAPE, please enter \134E.",
		*mlUtilsMess118 = "For a CONTROL character, please enter a caret (^) followed by the desired character eg. CTRL A should be entered as ^A.",
		*mlUtilsMess119 = "For dW#, please enter TRUE if there is to be a delay for 80/132 change or FALSE if there is not.",
		*mlUtilsMess120 = "All required escape sequences have not been entered. Please confirm update.",
		*mlUtilsMess121 = "Updating %s",
		*mlUtilsMess122 = "Termcap Maintenance",
		*mlUtilsMess123 = "Change Escape Sequence",
		*mlUtilsMess124 = "Escape Sequence for:",
		*mlUtilsMess125 = "Processing file : %s",
		*mlUtilsMess126 = "Rebuild on %s was successful.",
		*mlUtilsMess127 = "Rebuild on %s was unsuccessful.",
		*mlUtilsMess128 = "Rebuild on %s was deemed to be unnecessary",
		*mlUtilsMess129 = "Insufficient disk space available to rebuild %s",
		*mlUtilsMess130 = "File : %s  - not found in database.",
		*mlUtilsMess131 = "Number of Lines Automatically Adjusted",
		*mlUtilsMess132 = "Enter \"xxxxx...\" to show position and length of fields.",
		*mlUtilsMess133 = "Label specifications equate to more lines than entered.",
		*mlUtilsMess134 = "Label specifications equate to wider than 158 characters.",
		*mlUtilsMess135 = "Label code is not a customer label - 1st char must be C.",
		*mlUtilsMess136 = "Label code is not a supplier label - 1st char must be S.",
		*mlUtilsMess137 = "Customer Label Definition",
		*mlUtilsMess138 = "Supplier Label Definition",
		*mlUtilsMess139 = "Only %d fields to choose from",
		*mlUtilsMess140 = "Customer Label Printing",
		*mlUtilsMess141 = "Supplier Label Printing",
		*mlUtilsMess142 = "Usage : %s <C(ustomer)/S(upplier)>",
		*mlUtilsMess143 = "Replace [%s]",
		*mlUtilsMess144 = "By      [%s]",
		*mlUtilsMess145 = "Replace ? ",
		*mlUtilsMess146 = " [FN3] ",
		*mlUtilsMess147 = " [FN14] ",
		*mlUtilsMess148 = " [FN15] ",
		*mlUtilsMess149 = " [FN16] ",
		*mlUtilsMess150 = " S(tart All ",
		*mlUtilsMess151 = " H(alt All ",
		*mlUtilsMess152 = " [FN1] ",
		*mlUtilsMess153 = " S(tart ",
		*mlUtilsMess154 = " H(alt ",

		*mlUtilsMess700 = "Usage : %s <variable name>",
		*mlUtilsMess701 = "Usage : %s <program name>",
		*mlUtilsMess702 = "Usage : %s <offset days>",
		*mlUtilsMess703 = "Usage : %s <program name> <line1> <line2> [optional <program version>]",
		*mlUtilsMess704 = "Usage : %s [-p] -d|D|s|c|C [file...]",
		*mlUtilsMess705 = "Usage : %s -[cs] <file name>",
		*mlUtilsMess706 = "-c  Formatted output of static structure",
		*mlUtilsMess707 = "-s  Output of default 'screen' file",
		*mlUtilsMess708 = "Usage : %s <company> <branch>",
		*mlUtilsMess709 = "Usage : %s <filename>",
		*mlUtilsMess710 = "Usage : %s <lpno> <update>",
		*mlUtilsMess711 = "                   Update - (Y)es update file",
		*mlUtilsMess712 = "                          - (N)o update file>",
		*mlUtilsMess713 = "Usage : %s[-n] <filenames>",
		*mlUtilsMess714 = "Usage : %s <filename> <offset> <string>",
		*mlUtilsMess715 = "Usage : %-20.20s <report_type>",
		*mlUtilsMess716 = "        %-20.20s <report_type> - C(ustomer Master File)",
		*mlUtilsMess717 = "        %-20.20s - I(nventory Master File)",
		*mlUtilsMess718 = "        %-20.20s - S(upplier Master File)",
		*mlUtilsMess719 = "Usage : %s - optional <action>",
		*mlUtilsMess720 = "Usage : %s 0 : Stop All",
		*mlUtilsMess721 = "or      %s 1 : Start All",
		*mlUtilsMess722 = "or      %s D : Display",
		*mlUtilsMess723 = "Usage : %s <prog_name> <prog_version> <err_no> <text>",
		*mlUtilsMess724 = "Usage : %s <device> <stty mode> ",
		*mlUtilsMess725 = "Usage : %s -[acp] <filename...>",
		*mlUtilsMess726 = "   -a  All files in the database.",
		*mlUtilsMess727 = "   -c  Conditional rebuild.",
		*mlUtilsMess728 = "   -p  Print Log.";
#endif	
