extern	int		EnvScreenOK;
extern	int		TruePosition;
extern	int		_ck_restart (void);
extern	int		_getval (int);
extern	int		_next_field (int, int, int, int);
extern	int		_next_row (int, int);
extern	int		_prev_field (int, int, int, int);
extern	int		_prev_row (int, int);
extern	int		_putval (int);
extern	int		delete_tab (void);
extern	int		dis_edit (int, int, int, int);
extern	int		field_width (int);
extern	int		get_field (int);
extern	int		getval (int);
extern	int		goto_field (int, int);
extern	int		invalid_entry (int);
extern	int		label (char *);
extern	int		putval (int);
extern	int		scn_set (int);
extern	int		valid_scn (int);
extern	void	Display_field (int, int, int);
extern	void	_edit (int, int, int);
extern	void	_print_edit (int, int, int);
extern	void	_print_head (int, int);
extern	void	_set_masks (char *);
extern	void	_set_masks (char *);
extern	void	blank_display (void);
extern	void	display_field (int);
extern	void	display_prmpt (int);
extern	void	edit (int);
extern	void	edit_all (void);
extern	void	edit_fn (int);
extern	void	edit_ok (int);
extern	void	edit_scn (int, int);
extern	void	edit_win (int);
extern	void	ent_edit (int, int);
extern	void	entry (int);
extern	void	get_entry (int);
extern	void	init_vars (int);
extern	void	line_display (void);
extern	void	no_edit (int);
extern	void	pr_box_lines (int);
extern	void	scn_display (int);
extern	void	scn_entry (int);
extern	void	scn_write (int);
extern	void	set_masks (void);
extern	void	set_prnt_mask (int, char *);
extern	void	shell_prog (int);
extern	void 	fld_reposition (int, int *);
extern	void 	setup_scr (struct var *var_tab, int, int, int, int, int, int, int	(*m_win) (int));
extern	int		use_window (int);
extern	int	 	PauseForKey (int, int, char *, int);
