#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:35:06 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:35:06  scott
#	RELEASE 5.0
#	
#
#

APP		=	pc_time_upd
SRCS	=	time_upd.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
