#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:51:01 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:51:01  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:19:03  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:40:27  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:21:58  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/09/07 05:27:57  scott
#	Updated to use app.schema, required a level of code clean up.
#	
#
#

APP		=	so_cc_disp
SRCS	=	so_cc_disp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
