#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.0 2002/05/07 10:02:57 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.0  2002/05/07 10:02:57  scott
#	Updated to ensure version numbers on new programs are correct.
#	
#	Revision 1.1  2002/05/07 02:49:04  scott
#	First Release New Archive Program
#	
#
#

APP		=	ArchiveFiles
SRCS	=	ArchiveFiles.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
