#
# makefile for ts_lett_mnt.
#
#	Generated - on : 04/12/91
#	          - at : 04:45:05 PM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = lett_mnt.o

TARGET = $(DESTDIR)/ts_lett_mnt

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
