#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2002/09/06 03:14:49 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2002/09/06 03:14:49  scott
#	S/C SC4296/LS01238 - Import of budgets produced an error.
#	
#	Revision 5.1  2001/07/25 02:17:36  scott
#	Update - LS10.5
#	
#
#

APP		=	gl_bud_export
ALTS	=	gl_bud_import
SRCS	=	bud_export.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
