#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/10 05:08:21 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/10 05:08:21  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	cr_ddelete
SRCS	=	cr_ddelete.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
