#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/10/09 22:34:27 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/10/09 22:34:27  scott
#	Updated from Scotts machine.
#	
#
#

APP		=	cm_wip_mnt
SRCS	=	cm_wip_mnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
