#
# makefile for so_reflag.
#
#	Generated - on : 23/08/89
#	          - at : 11:54:51 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = so_reflag.o

TARGET = $(DESTDIR)/so_reflag

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
