#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/08 05:06:27 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/08 05:06:27  scott
#	Updated to use app.schema
#	Updated to clean code and bring inline with standard.
#	
#
#

APP		=	tm_campaign
SRCS	=	campaign.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
