#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:19:57 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:19:57  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:40:36  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/03/08 02:12:07  scott
#	Updated to increase the delivery address number from 0-999 to 0-32000
#	This change did not require a change to the schema
#	As a general practice all programs have had app.schema added and been cleaned
#	
#
#

APP		=	so_credit
SRCS	=	so_credit.c
ALTS	=	so_crddisp so_scrddisp

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
