#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:17:55 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:17:55  scott
#	Update - LS10.5
#	
#	Revision 5.0  2001/06/19 08:06:47  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/06/14 04:29:27  scott
#	Updated for general maintenance.
#	Added app.schema
#	
#
#

APP		=	gl_postbat
SRCS	=	gl_postbat.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
