#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/12 05:01:46 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/12 05:01:46  scott
#	Updated to add app.schema
#	Updated to clean code
#	Updated to line up prompts.
#	
#
#

APP		=	tm_ld_allc
SRCS	=	tm_ld_allc.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
