#include	<std_decs.h>
extern int main (int argc, char **argv);
extern void SetSignals (void);
static void EndProcess (int sig);
extern int SetListen (void);
extern int AcceptConnection (void);
extern void StartProcessing (void);
extern int GetCommsInit (int sockHandle);
extern int GetTransHeader (int sockHandle);
extern int GetTransLines (int sockHandle);
extern int GetNotesLines (int sockHandle);
extern int SendAll (void);
extern int GetLostLines (int sockHandle);
extern char *GetMessage (int sockHandle);
extern void open_db (void);
extern void close_db (void);
extern void OpenLogFiles (void);
extern void CloseLogFiles (void);
extern int UpdateStatusLog (FILE *fil, int set);
extern int UpdateStatus (int term, int status, int set);
extern int UpdateCohr (struct TransHeader *header);
extern int UpdateColn (struct TransLine *lines);
extern int UpdateSons (struct TransNotes *notes);
extern int UpdateInls (struct TransLostSales *lost);
extern void GetCompany (int term, char *co, char *br, char *wr, char *usr);
extern char *GetLastInvoiceNo (int type_t);
extern long int GetIncc (void);
extern void UpdateInventory (long int hhbr, long int incc);
extern void term_srvd (int sig);
extern void ChildEnds (int sig);
extern void SendInmr (void);
extern void SendInpr (void);
extern void SendCumr (void);
extern void SendInum (void);
extern void SendInds (void);
extern char *GetAppInv (char *oldInv);
