#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.0 2002/05/08 01:46:00 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.0  2002/05/08 01:46:00  scott
#	CVS administration
#	
#	Revision 4.1  2001/08/07 00:08:03  scott
#	RELEASE 5.0
#	
#	Revision 4.0  2001/04/02 04:49:22  scott
#	Updated new program to release 4.(x)
#	
#	Revision 1.1  2001/04/02 04:48:20  scott
#	Updated to version 9.10.3
#	
#
#

APP		=	lc_dsp_log
SRCS	=	lc_dsp_log.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
