#
# makefile for db_pt_adj.
#
#	Generated - on : 04/11/90
#	          - at : 05:15:48 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = db_ddate_upd.o

TARGET = $(DESTDIR)/db_ddate_upd

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

