rm update.sql
demo.update.sh arhr arhr_del_date  $1
demo.update.sh arhr arhr_asm_date $1
demo.update.sh arhr arhr_date_raised $1
demo.update.sh arhr arhr_date_required $1
demo.update.sh arhr arhr_date_create $1
demo.update.sh arln arln_due_date $1
demo.update.sh asdt asdt_ser_date $1
demo.update.sh asmr asmr_pur_date $1
demo.update.sh asmv asmv_move_date $1
demo.update.sh bach bach_date $1
demo.update.sh bkcr bkcr_ldate_up $1
demo.update.sh bkhs bkhs_date $1
demo.update.sh bldt bldt_lodge_date $1
demo.update.sh bldt bldt_due_date $1
demo.update.sh bpro bpro_up_date $1
demo.update.sh cbbs cbbs_end_period  $1
demo.update.sh cbbt cbbt_tran_date $1
demo.update.sh cbbt cbbt_period  $1
demo.update.sh cbtr cbtr_stmt_date  $1
demo.update.sh cfhs cfhs_date $1
demo.update.sh cmeq cmeq_dop $1
demo.update.sh cmhr cmhr_it_date $1
demo.update.sh cmhr cmhr_wip_date $1
demo.update.sh cmhr cmhr_st_date $1
demo.update.sh cmhr cmhr_due_date $1
demo.update.sh cmhr cmhr_end_date $1
demo.update.sh cmpb cmpb_date $1
demo.update.sh cmpb cmpb_inv_date $1
demo.update.sh cmrd cmrd_due_date $1
demo.update.sh cmrh cmrh_req_date $1
demo.update.sh cmrh cmrh_rqrd_date $1
demo.update.sh cmrh cmrh_iss_date $1
demo.update.sh cmrh cmrh_date_create $1
demo.update.sh cmtr cmtr_date $1
demo.update.sh cmts cmts_date $1
demo.update.sh cnch cnch_date_wef $1
demo.update.sh cnch cnch_date_rev $1
demo.update.sh cnch cnch_date_ren $1
demo.update.sh cnch cnch_date_exp $1
demo.update.sh cnre cnre_inv_date $1
demo.update.sh cohr cohr_del_date $1
demo.update.sh cohr cohr_asm_date $1
demo.update.sh cohr cohr_date_raised $1
demo.update.sh cohr cohr_date_required $1
demo.update.sh cohr cohr_date_create $1
demo.update.sh coln coln_due_date $1
demo.update.sh comm comm_dbt_date $1
demo.update.sh comm comm_crd_date $1
demo.update.sh comm comm_inv_date $1
demo.update.sh comm comm_payroll_date $1
demo.update.sh comm comm_gl_date $1
demo.update.sh comr comr_dbt_date $1
demo.update.sh comr comr_crd_date $1
demo.update.sh comr comr_inv_date $1
demo.update.sh comr comr_payroll_date $1
demo.update.sh comr comr_gl_date $1
demo.update.sh comr comr_stmt_date $1
demo.update.sh comr comr_date_stmt_prn $1
demo.update.sh comr comr_yend_date $1
demo.update.sh cucc cucc_cont_date $1
demo.update.sh cucd cucd_rec_date $1
demo.update.sh cuch cuch_create_date $1
demo.update.sh cuch cuch_expiry_date $1
demo.update.sh cudr cudr_date_of_rpt $1
demo.update.sh cuhd cuhd_index_date $1
demo.update.sh cuhd cuhd_due_date $1
demo.update.sh cuhd cuhd_present_date $1
demo.update.sh cuhd cuhd_date_payment $1
demo.update.sh cuhd cuhd_date_posted $1
demo.update.sh cuin cuin_date_of_inv $1
demo.update.sh cuin cuin_date_posted $1
demo.update.sh cuin cuin_due_date $1
demo.update.sh cumr cumr_date_stop $1
demo.update.sh cumr cumr_date_open $1
demo.update.sh cumr cumr_date_lastinv $1
demo.update.sh cumr cumr_date_lastpay $1
demo.update.sh cumr cumr_crd_expiry $1
demo.update.sh cuph cuph_date_cheq $1
demo.update.sh curh curh_ord_date $1
demo.update.sh cush cush_pur_date $1
demo.update.sh cuwk cuwk_date_of_inv $1
demo.update.sh cuwk cuwk_post_date $1
demo.update.sh ddhr ddhr_dt_raised $1
demo.update.sh ddhr ddhr_dt_required $1
demo.update.sh ddhr ddhr_date_create $1
demo.update.sh ddln ddln_req_date $1
demo.update.sh ddln ddln_due_date $1
demo.update.sh ddsh ddsh_due_date $1
demo.update.sh ddsh ddsh_date_load $1
demo.update.sh ddsh ddsh_ship_depart $1
demo.update.sh ddsh ddsh_ship_arrive $1
demo.update.sh esmr esmr_dbt_date $1
demo.update.sh esmr esmr_crd_date $1
demo.update.sh esmr esmr_inv_date $1
demo.update.sh esmr esmr_pay_date $1
demo.update.sh esmr esmr_gl_date $1
demo.update.sh esmr esmr_stmt_date $1
demo.update.sh esmr esmr_date_stmt_prn $1
demo.update.sh exmh exmh_date $1
demo.update.sh exmm exmm_st_date $1
demo.update.sh exmm exmm_en_date $1
demo.update.sh extr extr_date $1
demo.update.sh fagl fagl_tran_date $1
demo.update.sh famr famr_pur_date $1
demo.update.sh famr famr_disp_date $1
demo.update.sh famr famr_gl_updated $1
demo.update.sh fehr fehr_date_wef $1
demo.update.sh fehr fehr_date_exp $1
demo.update.sh glaj glaj_ef_frm $1
demo.update.sh glaj glaj_ef_to $1
demo.update.sh glaj glaj_date_lproc $1
demo.update.sh glbd glbd_mod_date $1
demo.update.sh glbh glbh_date $1
demo.update.sh glbl glbl_tran_date $1
demo.update.sh glca glca_mod_date $1
demo.update.sh glct glct_mod_date $1
demo.update.sh gllg gllg_mod_date $1
demo.update.sh glmr glmr_mod_date  $1
demo.update.sh glsh glsh_mod_date $1
demo.update.sh glsj glsj_from_dt $1
demo.update.sh glsj glsj_to_dt $1
demo.update.sh glsj glsj_dt_posted $1
demo.update.sh gltr gltr_tran_date $1
demo.update.sh gltr gltr_post_date $1
demo.update.sh glwk glwk_tran_date $1
demo.update.sh glwk glwk_post_date $1
demo.update.sh ifdg ifdg_date_inv $1
demo.update.sh inad inad_date_created $1
demo.update.sh inaf inaf_sys_date $1
demo.update.sh inaf inaf_date $1
demo.update.sh inah inah_date_created $1
demo.update.sh inal inal_exp_date $1
demo.update.sh inal inal_rel_date $1
demo.update.sh inbm inbm_last_mod $1
demo.update.sh incc incc_first_stocked $1
demo.update.sh incc incc_freeze_date $1
demo.update.sh incc incc_os_date $1
demo.update.sh incc incc_os_ldate $1
demo.update.sh incf incf_fifo_date $1
demo.update.sh incp incp_date_from $1
demo.update.sh incp incp_date_to $1
demo.update.sh inei inei_date_lcost  $1
demo.update.sh infp infp_date_from $1
demo.update.sh infp infp_date_to $1
demo.update.sh ingu ingu_eff_date $1
demo.update.sh inis inis_lcost_date $1
demo.update.sh inld inld_ord_date $1
demo.update.sh inld inld_sup_date $1
demo.update.sh inlo inlo_expiry_date $1
demo.update.sh inlo inlo_date_upd $1
demo.update.sh inlo inlo_date_create $1
demo.update.sh inls inls_date $1
demo.update.sh inmb inmb_date  $1
demo.update.sh inml inml_mend_date $1
demo.update.sh inoi inoi_stake_date $1
demo.update.sh inoi inoi_item_exp $1
demo.update.sh inoi inoi_lst_pullout $1
demo.update.sh inrb inrb_start_date $1
demo.update.sh inrb inrb_end_date $1
demo.update.sh inrh inrh_post_date $1
demo.update.sh inrh inrh_inv_date $1
demo.update.sh insc insc_start_date $1
demo.update.sh insc insc_frz_date $1
demo.update.sh insf insf_date_in  $1
demo.update.sh insf insf_date_out  $1
demo.update.sh inth inth_eff_date $1
demo.update.sh inth inth_chg_date $1
demo.update.sh intr intr_date $1
demo.update.sh inwo inwo_date $1
demo.update.sh itff itff_fifo_date $1
demo.update.sh itgl itgl_tran_date $1
demo.update.sh itgl itgl_post_date $1
demo.update.sh ithr ithr_iss_sdate $1
demo.update.sh ithr ithr_iss_date $1
demo.update.sh ithr ithr_rec_date $1
demo.update.sh ithr ithr_date_create $1
demo.update.sh ithr ithr_del_date $1
demo.update.sh itln itln_due_date $1
demo.update.sh itlo itlo_expiry_date $1
demo.update.sh itlo itlo_date_create $1
demo.update.sh mhdr mhdr_mfg_pur_date $1
demo.update.sh mhdr mhdr_order_date $1
demo.update.sh mhdr mhdr_sell_date $1
demo.update.sh mhdr mhdr_war_exp $1
demo.update.sh mhdr mhdr_lst_ser_date $1
demo.update.sh move move_date_tran $1
demo.update.sh pcat pcat_date $1
demo.update.sh pccl pccl_act_date $1
demo.update.sh pcgl pcgl_tran_date $1
demo.update.sh pcgl pcgl_post_date $1
demo.update.sh pclt pclt_issue_date $1
demo.update.sh pcrq pcrq_last_date $1
demo.update.sh pcrq pcrq_est_date $1
demo.update.sh pcrq pcrq_act_date $1
demo.update.sh pcwo pcwo_reqd_date $1
demo.update.sh pcwo pcwo_create_date $1
demo.update.sh pcwo pcwo_mfg_date  $1
demo.update.sh pmat pmat_act_date $1
demo.update.sh pmat pmat_next_act_date $1
demo.update.sh pmct pmct_date_lpurge $1
demo.update.sh pmct pmct_date_lupd $1
demo.update.sh pmhl pmhl_active_date $1
demo.update.sh pmhl pmhl_fst_rd_date $1
demo.update.sh pmhl pmhl_date_action $1
demo.update.sh pmhs pmhs_date $1
demo.update.sh pmpm pmpm_date_entrd $1
demo.update.sh pmpm pmpm_date_start $1
demo.update.sh pmpm pmpm_date_end $1
demo.update.sh pmre pmre_active_date $1
demo.update.sh pmre pmre_fst_date $1
demo.update.sh pmre pmre_lst_date $1
demo.update.sh pmse pmse_date $1
demo.update.sh pmtx pmtx_date $1
demo.update.sh poca poca_date_print $1
demo.update.sh pocf pocf_last_update  $1
demo.update.sh poch poch_estab_date  $1
demo.update.sh poch poch_expire_date  $1
demo.update.sh pocr pocr_ldate_up $1
demo.update.sh pofd pofd_pay_date $1
demo.update.sh pofh pofh_estab_date $1
demo.update.sh pofh pofh_start_date $1
demo.update.sh pofh pofh_end_date $1
demo.update.sh pogh pogh_date_raised $1
demo.update.sh pogl pogl_exp_date $1
demo.update.sh pogl pogl_rec_date $1
demo.update.sh pohr pohr_date_raised $1
demo.update.sh pohr pohr_due_date $1
demo.update.sh pohr pohr_conf_date $1
demo.update.sh pohr pohr_date_create $1
demo.update.sh pohr pohr_pay_date $1
demo.update.sh pohs pohs_date_receipt $1
demo.update.sh pohs pohs_date_cost $1
demo.update.sh polh polh_from_date $1
demo.update.sh polh polh_to_date $1
demo.update.sh poli poli_cont_date $1
demo.update.sh poli poli_ship_date $1
demo.update.sh poli poli_eta_date $1
demo.update.sh poln poln_due_date $1
demo.update.sh poln poln_fwd_date $1
demo.update.sh posh posh_ship_depart $1
demo.update.sh posh posh_ship_arrive $1
demo.update.sh posh posh_doc_rec $1
demo.update.sh posh posh_doc_agent $1
demo.update.sh posh posh_neg_bol $1
demo.update.sh posh posh_costing_date $1
demo.update.sh potb potb_date_acc $1
demo.update.sh potb potb_pmt_date $1
demo.update.sh psqm psqm_dt_create $1
demo.update.sh psqm psqm_dt_modify $1
demo.update.sh pstq pstq_st_date $1
demo.update.sh qchr qchr_receipt_dt $1
demo.update.sh qchr qchr_exp_rel_dt $1
demo.update.sh qcln qcln_release_dt $1
demo.update.sh qcln qcln_reassay_date $1
demo.update.sh qthr qthr_date_create $1
demo.update.sh qthr qthr_expire_date $1
demo.update.sh qthr qthr_dt_fst_call $1
demo.update.sh qthr qthr_dt_lst_call $1
demo.update.sh qthr qthr_dt_follow_up $1
demo.update.sh qthr qthr_dt_quote $1
demo.update.sh qthr qthr_del_date $1
demo.update.sh qtln qtln_exp_date $1
demo.update.sh qtph qtph_dt_fst_call $1
demo.update.sh qtph qtph_dt_lst_call $1
demo.update.sh qtph qtph_dt_follow_up $1
demo.update.sh qtph qtph_dt_quote $1
demo.update.sh sacl sacl_rec_date $1
demo.update.sh sacm sacm_date $1
demo.update.sh saed saed_date $1
demo.update.sh sjdc sjdc_date  $1
demo.update.sh sjhr sjhr_issue_date  $1
demo.update.sh sjhr sjhr_reqd_date $1
demo.update.sh sjhr sjhr_inv_date  $1
demo.update.sh sjhr sjhr_comp_date $1
demo.update.sh sjis sjis_date  $1
demo.update.sh sjld sjld_date $1
demo.update.sh sjsc sjsc_date  $1
demo.update.sh sjsp sjsp_date  $1
demo.update.sh sohr sohr_date_create $1
demo.update.sh sohr sohr_del_date $1
demo.update.sh sohr sohr_asm_date $1
demo.update.sh sohr sohr_dt_raised $1
demo.update.sh sohr sohr_dt_required $1
demo.update.sh soic soic_date_create $1
demo.update.sh sokt sokt_due_date $1
demo.update.sh soln soln_due_date $1
demo.update.sh sosa sosa_date $1
demo.update.sh sosf sosf_ocre_date $1
demo.update.sh sosf sosf_pcre_date $1
demo.update.sh sosf sosf_oprn_date $1
demo.update.sh sosf sosf_pprn_date $1
demo.update.sh sosf sosf_iprn_date $1
demo.update.sh sosf sosf_odes_date $1
demo.update.sh sosf sosf_odel_date $1
demo.update.sh sttf sttf_exp_date $1
demo.update.sh sttf sttf_lot_expiry $1
demo.update.sh succ succ_date_of_chq $1
demo.update.sh suhd suhd_date_payment $1
demo.update.sh suhd suhd_date_post $1
demo.update.sh suhp suhp_date_payment $1
demo.update.sh suhp suhp_date_post $1
demo.update.sh suin suin_date_of_inv $1
demo.update.sh suin suin_date_posted $1
demo.update.sh suin suin_pay_date $1
demo.update.sh suin suin_gl_date $1
demo.update.sh sumr sumr_date_opened $1
demo.update.sh sumr sumr_qa_expiry $1
demo.update.sh suph suph_ord_date $1
demo.update.sh suph suph_due_date $1
demo.update.sh suph suph_rec_date $1
demo.update.sh susc susc_date_of_chq $1
demo.update.sh tmcf tmcf_start_date $1
demo.update.sh tmcf tmcf_end_date $1
demo.update.sh tmch tmch_call_date $1
demo.update.sh tmpm tmpm_n_phone_date $1
demo.update.sh tmpm tmpm_n_visit_date $1
demo.update.sh tmpm tmpm_call_bk_date $1
demo.update.sh tmpm tmpm_lphone_date $1
demo.update.sh tmpm tmpm_date_create $1
demo.update.sh trch trch_date $1
demo.update.sh trhr trhr_del_date $1
demo.update.sh trhr trhr_act_date $1
demo.update.sh trsh trsh_del_date $1
demo.update.sh tshs tshs_date $1
demo.update.sh tslb tslb_date_sent $1
demo.update.sh tsls tsls_date_sent $1
demo.update.sh tsls tsls_date_called $1
demo.update.sh tspm tspm_n_phone_date $1
demo.update.sh tspm tspm_n_visit_date $1
demo.update.sh tspm tspm_lphone_date $1
demo.update.sh tspm tspm_date_create $1
demo.update.sh wfbc wfbc_date_create $1
demo.update.sh wrex wrex_date_upd $1
demo.update.sh wrmr wrmr_date  $1
demo.update.sh wrpc wrpc_date_claim $1
demo.update.sh wrpc wrpc_date_failure $1
