#
# makefile for ts_active.
#
#	Generated - on : 04/12/91
#	          - at : 02:25:09 PM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = ts_active.o

TARGET = $(DESTDIR)/ts_active

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
