#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.0 2002/05/08 01:22:58 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.0  2002/05/08 01:22:58  scott
#	CVS administration
#	
#	Revision 1.2  2001/08/06 23:31:25  scott
#	RELEASE 5.0
#	
#	Revision 1.1  2001/06/23 11:53:48  scott
#	New program
#	
#
#

APP		=	pc_autorecGlFix
SRCS	=	pc_autorecGlFix.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
