#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:45:52 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:45:52  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:17:41  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:38:56  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 1.1  2000/12/12 07:30:37  scott
#	New Program to maintain container master file.
#	
#
#

APP		=	sk_skcm_mnt
SRCS	=	sk_skcm_mnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
