#
# makefile for sorry.
#
#	Generated - on : 23/08/89
#	          - at : 10:40:35 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = sorry.o

TARGET = $(DESTDIR)/sorry

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
