#	$Id: Makefile,v 5.1 2001/08/06 23:58:42 scott Exp $
#
#	Standard application Makefile template
#
################################################################################
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:58:42  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:22:59  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:43:56  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:24:18  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 09:15:21  gerry
#	Forced Revision No Start 2.0 Rel-15072000
#	
#	Revision 1.2  1999/07/20 00:40:11  jonc
#	Adopted Pinnacle V10 lockLook.
#	
APP		=	lock_look

SRCS	=	lock_look.C LockBucket.C LockInfo.C

include ${BASE_PATH}/${VERSION}/CONFIG/Make.Base
