#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/26 09:02:46 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/26 09:02:46  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_top_fif
SRCS	=	db_top_fif.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
