#	$Id: Makefile,v 5.1 2001/08/06 23:37:08 scott Exp $
#
################################################################################
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:37:08  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:11:50  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:33:03  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.2  2001/02/16 03:39:36  scott
#	New 'C' version that replaces C++ version that is not database independent
#	
#	
APP		=   po_poprint
ALTS	=	po_cprint
SRCS	=	po_poprint.c 

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
