#
# makefile for co_update.
#
#	Generated - on : 16/05/91
#	          - at : 11:46:57 AM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = co_update.o

TARGET = $(DESTDIR)/co_update

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
