#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:19 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:19  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/04/02 00:01:07  scott
#	Updated new program to release 4.(x)
#	
#	Revision 1.1  2001/03/29 06:12:29  scott
#	New Program - Automatic stock issues to Production.
#	Driven by XML files.
#	
#
#

APP		=	pc_autoiss
SRCS	=	pc_autoiss.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
