#
# makefile for load_env.
#
#	Generated - on : 01/11/89
#	          - at : 02:15:23 PM
#	          - by : rog
#

SHELL   = /bin/sh

OBJS = load_env.o

TARGET = $(DESTDIR)/load_env

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
