#
#	Standard application Makefile template
#
############################################
#
#	$Id
#	$Log
#

APP		=	gl_glpdCheck
SRCS	=	gl_glpdCheck.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
