#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/03/08 04:43:37 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/03/08 04:43:37  scott
#	Updated to use app.schema and to create blank report files in SCRIPT.
#	
#
#

APP		=	mend_gen
SRCS	=	mend_gen.c
ALTS	=	mend_prt

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
