#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 04:22:12 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 04:22:12  scott
#	Updated for LS10.5
#	
#
#

APP		=	cr_bk_inpt
SRCS	=	cr_bk_inpt.c
ALTS	=	db_bk_inpt

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
