#
# makefile for sk_st_svarpr.
#
#	Generated - on : 02/10/89
#	          - at : 10:45:45 AM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = st_svarpr.o

TARGET = $(DESTDIR)/sk_st_svarpr

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
