#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/14 06:04:11 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/14 06:04:11  scott
#	Updated to convert to app.schema
#	
#
#

APP		=	tm_ld_sheet
SRCS	=	ld_sheet.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
