#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.0 2002/05/07 10:22:59 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.0  2002/05/07 10:22:59  scott
#	Updated to bring version number to 5.0
#	
#	Revision 1.1  2001/09/06 09:53:37  scott
#	New Program
#	
#

APP		=	so_check
SRCS	=	so_check.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
