#
# makefile for so_taxprt.
#
#	Generated - on : 23/08/89
#	          - at : 11:56:15 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = so_taxprt.o

TARGET = $(DESTDIR)/so_taxprt

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
