#
# makefile for psl_what.
#
#	Generated - on : 25/11/92
#	          - at : 04:55:46 PM
#	          - by : trev
#

SHELL   = /bin/sh

OBJS = psl_what.o

TARGET = $(DESTDIR)/psl_what

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
