#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2001/12/07 03:39:34 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2001/12/07 03:39:34  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#	Revision 5.1  2001/08/06 23:21:59  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:04:29  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/05/28 06:57:19  scott
#	Updated to look better with LS10-GUI.
#	Converted to use app.schema as per standard.
#	Converted to use new Makefile.
#	
#
#

APP		=	db_exdisinp
SRCS	=	db_exdisinp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
