#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/13 04:30:34 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/13 04:30:34  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	sk_buygrp
SRCS	=	sk_buygrp.c
ALTS	=	sk_sellgrp

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
