#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/12 02:47:08 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/12 02:47:08  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	sk_xdes_inp
SRCS	=	sk_xdes_inp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
