#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:19:24 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:19:24  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:38:38  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/02/19 08:01:34  scott
#	Updated to use app.schema
#	
#
#

APP		=	sk_rofi
SRCS	=	sk_rofi.c
ALTS	=	sk_rofi_summ

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
