#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/03/06 08:29:04 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/03/06 08:29:04  scott
#	S/C 00832 - RTGMR7-Instruction Detail Maintainance; after changing the text for one instruction, then save, the changes does not reflect in the search window of field Instruction, but when selected, the previous
#	
#
#

APP		=	pc_mimaint
SRCS	=	pc_mimaint.c
ALTS	=	pc_idmaint pc_hwmaint

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
