#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/07 05:44:39 kaarlo Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/07 05:44:39  kaarlo
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	cr_qa_prn
SRCS	=	cr_qa_prn.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
