#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/12 07:38:20 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/12 07:38:20  scott
#	Updated to add app.schema
#	Updated to clean code.
#	
#
#

APP		=	tm_script
SRCS	=	tm_script.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
