#
# makefile for lockout_br.
#
#	Generated - on : 24/08/89
#	          - at : 10:51:18 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = lockout_br.o

TARGET = $(DESTDIR)/lockout_br

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
