#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:51:42 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:51:42  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:20:16  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:41:32  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:22:49  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/08/16 23:51:35  scott
#	Updated to add app.schema and clean code.
#	Re-applied modification that prevents packing slip with no lines from being
#	added.
#	
#
#

APP		=	so_ps_cons
SRCS	=	so_ps_cons.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
