#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.0 2002/06/05 06:05:40 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.0  2002/06/05 06:05:40  scott
#		{1, LIN, "mfgBrNo",	 2, 18, CHARTYPE,
#			"AA", "          ",
#			" ", comm_rec.est_no, "Mfg Branch  :", "Manufacturing Branch.",
#			NE, NO,  JUSTRIGHT, "", "", local_rec.mfgBrNo},
#		{1, LIN, "mfgBrName",	 2, 25, CHARTYPE,
#			"UUUUUUUUUUUUUUU", "          ",
#			" ", "", "", "",
#			NA, NO,  JUSTLEFT, "", "", local_rec.mfgBrName},
#		{1, LIN, "mfgWhNo",	 2, 75, CHARTYPE,
#			"AA", "          ",
#			" ", comm_rec.cc_no, "Mfg Warehouse:", "Manufacturing Warehouse.",
#			NE, NO,  JUSTRIGHT, "", "", local_rec.mfgWhNo},
#		{1, LIN, "mfgWhName",	 2, 82, CHARTYPE,
#			"UUUUUUUUU", "          ",
#			" ", "", "", "",
#			NA, NO,  JUSTLEFT, "", "", local_rec.mfgWhName},
#		{1, LIN, "orderNumber",	 3, 18, CHARTYPE,
#			"UUUUUUU", "          ",
#			" ", " ", "Order Number:", " ",
#			NO, NO,  JUSTLEFT, "", "", local_rec.orderNumber},
#	
#	Revision 1.1  2002/06/05 04:05:24  scott
#	First Release
#	
#
#

APP		=	pc_ar_wodisp
SRCS	=	pc_ar_wodisp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
