#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.2 2001/08/06 23:37:22 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2001/08/06 23:37:22  scott
#	RELEASE 5.0
#	
#	Revision 5.1  2001/07/25 02:18:30  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:33:30  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:18:11  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 09:05:40  gerry
#	Forced Revision No Start 2.0 Rel-15072000
#	
#	Revision 1.2  2000/01/07 02:45:13  scott
#	Updated to add environment PO_REC_STD_UOM to receipt in base UOM only.
#	
#	Revision 1.2  1999/12/16 04:22:30  scott
#	Updated to remove pre-defined log
#	
#	
#	
#	
APP		=	po_stkupd
SRCS	=	po_stkupd.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
