#
# makefile for sa_dfcstprd.
#
#	Generated - on : 06/06/91
#	          - at : 11:34:52 AM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = dfcstprd.o

TARGET = $(DESTDIR)/sa_dfcstprd

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
