#
# makefile for sa_catgs.
#
#	Generated - on : 23/08/89
#	          - at : 11:19:17 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = sa_catgs.o

TARGET = $(DESTDIR)/sa_catgs

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
