#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/10/18 06:54:30 cha Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/10/18 06:54:30  cha
#	Clean and convert program sk_ir_disp.c (unmatched transfers).
#	Modified by Scott.
#	
#
#

APP		=	sk_ir_disp
SRCS	=	sk_ir_disp.c
ALTS	=	sk_ir_mcdisp

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
