#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/07 05:53:27 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/07 05:53:27  scott
#	Updated to add app.schema
#	Updated to clean code
#	Updated to remove gets and replace with scanf
#	
#
#

APP		=	pc_qcreat
SRCS	=	pc_qcreat.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
