#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/03/04 05:34:03 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/03/04 05:34:03  scott
#	S/C 00792 - SAMR9-Maintain Subranges; CHAR-BASED / WINDOWS CLIENT (1) Run the program, delete one line and press F12, the program exits.  Then run the program again, there is no detail saved. WINDOWS CLIENT
#	(2) When delete a line ( press <backspace>, then <enter ), the rest of the lines below do not clear.
#	
#
#

APP		=	sa_srmaint
SRCS	=	sa_srmaint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
