#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/10 07:56:13 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/10 07:56:13  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	sk_item_uom
SRCS	=	sk_item_uom.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
