#
# makefile for cm_anniprt.
#
#	Generated - on : 23/04/93
#	          - at : 09:58:31 AM
#	          - by : jonc
#

SHELL   = /bin/sh

OBJS = cm_anniprt.o

TARGET = $(DESTDIR)/cm_anniprt

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
