#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:04 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:04  scott
#	Update - LS10.5
#	
#
#

APP		=	gl_upd_glwk
SRCS	=	upd_glwk.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
