#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:57 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:57  scott
#	Update - LS10.5
#	
#
#

APP		=	sk_costupd
SRCS	=	sk_costupd.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
