#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/11/27 11:41:03 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/11/27 11:41:03  scott
#	.
#	
#
#

APP		=	bm_substmnt
SRCS	=	substmnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
