#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/07 03:06:07 kaarlo Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/07 03:06:07  kaarlo
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	cr_pdagebal
SRCS	=	pdagebal.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
