#
# makefile for cm_ctr_inv.
#
#	Generated - on : 16/04/93
#	          - at : 11:31:43 AM
#	          - by : simon
#

SHELL   = /bin/sh

OBJS = cm_ctr_inv.o

TARGET = $(DESTDIR)/cm_ctr_inv

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
