#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/06 09:36:31 kaarlo Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/06 09:36:31  kaarlo
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	cr_lclose
SRCS	=	cr_lclose.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
