#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:19:05 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:19:05  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:37:01  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:20:08  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/07/24 01:42:08  scott
#	Added app.schema and cleaned up code.
#	
#
#

APP		=	sk_fifo_del
SRCS	=	fifo_del.c
ALTS	=	sk_fifo_chk

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
