#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:24:57 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:24:57  scott
#	RELEASE 5.0
#	
#
#

APP		=	fe_invallc
SRCS	=	fe_invallc.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
