#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/01/23 05:05:51 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/01/23 05:05:51  scott
#	Updated as first phase of contract management cleanup on it's way to becoming
#	useable for 3PL.
#	
#
#

APP		=	cm_alldisp
SRCS	=	cm_alldisp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
