#
# makefile for cm_emp_anal.
#
#	Generated - on : 16/04/93
#	          - at : 11:32:01 AM
#	          - by : simon
#

SHELL   = /bin/sh

OBJS = emp_anal.o

TARGET = $(DESTDIR)/cm_emp_anal

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
