#
# makefile for fa_sale.
#
#	Generated - on : 23/08/89
#	          - at : 11:17:06 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = fa_sale.o

TARGET = $(DESTDIR)/fa_sale

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
