#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/08 10:25:59 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/08 10:25:59  scott
#	Updated to remove disk sort and replace with qsort
#	Updated to use app.schema
#	Updated to fix selection from || to &&
#	
#
#

APP		=	so_trackdsp
SRCS	=	trackdsp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
