#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:19:19 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:19:19  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:38:20  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:20:51  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/08/09 02:28:29  scott
#	General maintenance - added app.schema
#	
#
#

APP		=	sk_nst_varpr
SRCS	=	nst_varpr.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
