#
# makefile for env_print.
#
#	Generated - on : 23/08/89
#	          - at : 10:45:26 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = env_print.o

TARGET = $(DESTDIR)/env_print

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
