#
# makefile for dsp_fast.
#
#	Generated - on : 23/08/89
#	          - at : 10:34:06 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = dsp_fast.o

TARGET = $(DESTDIR)/dsp_fast

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
