#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/02/22 09:13:09 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/02/22 09:13:09  scott
#	S/C 00822 - Clean up program - no real fault found.
#	
#
#

APP		=	so_batch_chk
SRCS	=	so_batch_chk.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
