#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/14 06:07:15 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/14 06:07:15  scott
#	Updated to convert to app.schema
#	Updated to clean code.
#	
#
#

APP		=	tm_orig_mnt
SRCS	=	orig_mnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
