#
# makefile for run_nice.
#
#	Generated - on : 04/05/90
#	          - at : 04:11:43 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = run_nice.o

TARGET = $(DESTDIR)/run_nice

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
