#
# makefile for pc_wiprpt.
#
#	Generated - on : 07/10/93
#	          - at : 05:04:19 PM
#	          - by : aroha
#

SHELL   = /bin/sh

OBJS = pc_wiprpt.o

TARGET = $(DESTDIR)/pc_wiprpt

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
