#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/06 08:54:17 kaarlo Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/06 08:54:17  kaarlo
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	cr_gl_eom
SRCS	=	cr_gl_eom.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
