#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/14 08:48:18 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/14 08:48:18  scott
#	Updated to add app.schema
#	Updated to clean code.
#	
#
#

APP		=	tm_resp_crit
SRCS	=	resp_crit.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
