#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:51:22 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:51:22  scott
#	RELEASE 5.0
#	
#
#

APP		=	so_invledup
SRCS	=	invledup.c
ALTS	=	so_crdledup so_gl_ledup

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
