#
# makefile for bm_copyprod.
#
#	Generated - on : 03/02/92
#	          - at : 02:22:00 PM
#	          - by : trev
#

SHELL   = /bin/sh

OBJS = copyprod.o

TARGET = $(DESTDIR)/bm_copyprod

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
