#
# makefile for cm_cont_lst.
#
#	Generated - on : 16/04/93
#	          - at : 01:56:24 PM
#	          - by : simon
#

SHELL   = /bin/sh

OBJS = cont_lst.o

TARGET = $(DESTDIR)/cm_cont_lst

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
