#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.0 2002/05/07 10:21:40 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.0  2002/05/07 10:21:40  scott
#	Updated to bring version number to 5.0
#	
#	Revision 1.1  2001/12/11 02:42:57  scott
#	Archive Invoice Print.
#	
#	
APP		=	ar_ctr_inv
ALTS	=	ar_ctr_crd
SRCS	=	ar_ctr_inv.c 

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
