#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:50:53 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:50:53  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:18:44  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:40:09  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/03/06 01:14:43  scott
#	Updated to perform general maintenance including addition of app.schema
#	
#
#

APP		=	so_bgcalc
SRCS	=	so_bgcalc.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
