#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:27:43 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:27:43  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:07:38  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:28:47  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/01/26 09:08:55  scott
#	Updated to add app.schema
#	
#
#

APP		=	lrp_reorder.i
SRCS	=	_reorder.i.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
