#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.1 2001/08/06 23:01:16 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:01:16  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:02:54  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:23:23  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:12:39  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 08:40:39  gerry
#	Forced Revision No. Start 2.0 Rel-15072000
#	
#	Revision 1.2  1999/11/10 06:21:05  scott
#	Updated for app.schema
#	
#	Revision 1.3  1999/11/10 05:21:59  scott
#	*** empty log message ***
#	
#	
#	
APP		=	cr_chqsdry
SRCS	=	cr_chqsdry.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
