#
# makefile for so_lineup.
#
#	Generated - on : 23/08/89
#	          - at : 11:49:20 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = so_lineup.o

TARGET = $(DESTDIR)/so_lineup

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
