#
# makefile for sk_st_sinp.
#
#	Generated - on : 24/08/89
#	          - at : 03:58:47 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = sk_st_sinp.o

TARGET = $(DESTDIR)/sk_st_sinp

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
