#
# makefile for BACK.
#
#	Generated - on : 23/08/89
#	          - at : 10:38:11 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = BACK.o

TARGET = $(DESTDIR)/BACK

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
