#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.2 2001/12/11 02:01:35 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2001/12/11 02:01:35  scott
#	Updated to rename file.
#	
#	Revision 5.1  2001/08/06 23:51:24  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:19:52  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:41:07  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:22:33  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 09:13:20  gerry
#	Forced Revision No Start 2.0 Rel-15072000
#	
#	Revision 1.2  2000/02/17 01:23:08  scott
#	S/C LSANZ-15984 & LSANZ-15948
#	S/C LSDI-2472 & LSDI-2509
#	Updated to rewrite to use memory based sort.
#	Added full print options for invoices and credits (re-apply of previous AIL mod)
#	Changed menu in_reports.mdf to reflect changes
#	
#	
APP		=	so_invprnt.i
ALTS	=	so_fullrpt
SRCS	=	so_invprnt.i.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
