#
# makefile for syserr.
#
#	Generated - on : 23/08/89
#	          - at : 11:29:07 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = syserr.o

TARGET = $(DESTDIR)/syserr

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
