#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 22:52:56 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 22:52:56  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:01:40  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 01:48:56  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:11:52  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/08/10 02:07:03  scott
#	Updated to allow for 10,000 lines rather than usual 200.
#	
#
#

APP		=	ca_bk_rec
SRCS	=	ca_bk_rec.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
