#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:20:02 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:20:02  scott
#	Update - LS10.5
#	
#	Revision 4.1  2001/04/06 06:38:23  scott
#	Updated to add app.schema - removes code related to tables from program as it
#	allows for better quality contol.
#	Updated to adjust screen to look better with LS10-GUI
#	Updated to perform routine maintenance to ensure standards are maintained.
#	
#
#

APP		=	so_pf_aud
SRCS	=	so_pf_aud.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
