#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/14 08:31:28 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/14 08:31:28  scott
#	Updated to add app.schema
#	General clean
#	
#
#

APP		=	tm_progress
SRCS	=	progress.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
