#!/bin/sh
#
#	List of std Installation variables
# $Id: InstallShellVars,v 4.0 2001/03/09 02:48:27 scott Exp $
#
# $Log: InstallShellVars,v $
# Revision 4.0  2001/03/09 02:48:27  scott
# LS10-4.0 New Release as at 10th March 2001
#
# Revision 1.4  2001/01/24 06:59:20  scott
# Updated as variable CSHRC should have been defined as info/csh.rc instead of
# info/tcshrc
#
# Revision 1.3  2001/01/17 07:45:47  scott
# Updated from testing
#
# Revision 1.2  2001/01/16 10:25:48  scott
# Updated from testing
#
# Revision 1.1  2001/01/12 07:19:40  scott
# New install system
#
# 
#
if [ -z "$CONFIG" ]
then
	PATH=/bin:/usr/bin:./bin; export PATH

	umask 0

	# Version being installed
	VERSION=9.10

	#
	#	List of data files
	#
	CONFIG=config.data
	RC=info/LS10Services.rc
	DIRINFO=info/Dir.info
	ENVINFO=info/Env.info
	PROFILE=info/profile
	CSHRC=info/csh.rc
	TCSHRC=info/tcshrc
	TERMMAP=info/term_map
	SETPERM=info/setperms
	MACHINFO=info/Machine.info
	DISTINFO=info/Distrib.info

	#
	#	State files
	DISTRIB=DISTRIB
	MANIFEST=MANIFEST
	LSLVARS=./LogisticVars
	INSTALLDONE=InstalledOn

	#
	#	Read in machine specific information
	#
	WORKFILE=/tmp/install.$$
	ifs="$IFS"
	IFS=:
	grep "^`uname -m`:" $MACHINFO > $WORKFILE
	read MACHINE CDDEV RC0 RC2 < $WORKFILE
	IFS="$ifs"
	unset ifs

	rm -f $WORKFILE
fi
