#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/10/25 07:54:32 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/10/25 07:54:32  scott
#	Updated to make changes related to container and seals.
#	
#
#

APP		=	tr_del_conf
SRCS	=	del_conf.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
