#
# makefile for sk_cqtyupd.
#
#	Generated - on : 18/10/93
#	          - at : 09:10:45 AM
#	          - by : simon
#

SHELL   = /bin/sh

OBJS = sk_cqtyupd.o

TARGET = $(DESTDIR)/sk_cqtyupd

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
