ModProgram.sh $1 " )" ")"
ModProgram.sh $1 "( " "("
ModProgram.sh $1 "( " "("
ModProgram.sh $1 "(" " ("
ModProgram.sh $1 "  (" " ("
ModProgram.sh $1 "  (" " ("
ModProgram.sh $1 "( (" "(("
ModProgram.sh $1 "@ (#)" "@(#)"
ModProgram.sh $1 "\[" " \["
ModProgram.sh $1 "  \[" " \["
ModProgram.sh $1 "  \[" " \["
ModProgram.sh $1 "\] \[" "\]\["
ModProgram.sh $1 "\"comm\"" "comm"
ModProgram.sh $1 "comm_rec\._" "comm_rec\."
ModProgram.sh $1 "comm_rec\.t" "comm_rec\."
ModProgram.sh $1 "comm_rec\._" "comm_rec\."
ModProgram.sh $1 "comm_rec\.ermno" "comm_rec\.term"
ModProgram.sh $1 "comm_rec\.erm_no" "comm_rec\.term"
ModProgram.sh $1 "comm_rec\.erm" "comm_rec\.term"
ModProgram.sh $1 "\"comr\"" "comr"
ModProgram.sh $1 "curr_fgn_amt" "CurrencyFgnAmt"
ModProgram.sh $1 "curr_loc_amt" "CurrencyLocAmt"
ModProgram.sh $1 "form_accno" "GL_FormAccNo"
ModProgram.sh $1 "fsrch_glmr" "SearchGlmr_F"
ModProgram.sh $1 "csrch_glmr" "SearchGlmr_C"
ModProgram.sh $1 "srch_glmr" "SearchGlmr"
ModProgram.sh $1 "fx_tot_glpd" "GL_FgnTotGlpd"
ModProgram.sh $1 "get_dflt_efacc_code" "GL_GetDfltEfaccCode"
ModProgram.sh $1 "get_dflt_sacc_code" "GL_GetDfltSaccCode"
ModProgram.sh $1 "get_dflt_sfacc_code" "GL_GetDfltSfaccCode"
ModProgram.sh $1 "get_fUserCode" "GL_GetfUserCode"
ModProgram.sh $1 "\"glbd\"" "glbd"
ModProgram.sh $1 "glbd_rec\.glbd_" "glbdRec\."
ModProgram.sh $1 "glbd_rec" "glbdRec"
ModProgram.sh $1 "\"glbh\"" "glbh"
ModProgram.sh $1 "glbhRec\.date" "glbhRec\.glbh_date"
ModProgram.sh $1 "glbh_rec" "glbhRec"
ModProgram.sh $1 "glbhRec\.time" "glbhRec\.glbh_time"
ModProgram.sh $1 "\"glbl\"" "glbl"
ModProgram.sh $1 "glbl_rec" "glblRec"
ModProgram.sh $1 "glca_rec\.glca_" "glcaRec\."
ModProgram.sh $1 "glca_rec" "glcaRec"
ModProgram.sh $1 "glid_rec\.glid_" "glidRec\."
ModProgram.sh $1 "glid_rec" "glidRec"
ModProgram.sh $1 "glih_rec\.glih_" "glihRec\."
ModProgram.sh $1 "glih_rec" "glihRec"
ModProgram.sh $1 "glct_rec\.glct_" "glctRec\."
ModProgram.sh $1 "glct_rec" "glctRec"
ModProgram.sh $1 "\"gljc\"" "gljc"
ModProgram.sh $1 "gljc_rec" "gljcRec"
ModProgram.sh $1 "gllnRec\.glln_" "gllnRec\."
ModProgram.sh $1 "glln_rec\.glln_" "gllnRec\."
ModProgram.sh $1 "glln_rec" "gllnRec"
ModProgram.sh $1 "glmr_rec\.glmr_" "glmrRec\."
ModProgram.sh $1 "glmr_rec" "glmrRec"
ModProgram.sh $1 "\"glmr\"" "glmr"
ModProgram.sh $1 "glmrRec\.glmr_" "glmrRec\."
ModProgram.sh $1 "glmr2_rec\.glmr_" "glmr2Rec\."
ModProgram.sh $1 "glmr3_rec\.glmr_" "glmr3Rec\."
ModProgram.sh $1 "glmr2_rec" "glmr2Rec"
ModProgram.sh $1 "glmr3_rec" "glmr3Rec"
ModProgram.sh $1 "glmrRec\.class" "glmrRec\.glmr_class"
ModProgram.sh $1 "\"glpd\"" "glpd"
ModProgram.sh $1 "glpd_rec\.glpd_" "glpdRec\."
ModProgram.sh $1 "glpd_rec" "glpdRec"
ModProgram.sh $1 "gl_post.h" "DELETE.h"
ModProgram.sh $1 "gl_iface.h" "DELETE.h"
ModProgram.sh $1 "\"gltr\"" "gltr"
ModProgram.sh $1 "gltr_rec\.gltr_" "gltrRec\."
ModProgram.sh $1 "gltr_rec" "gltrRec"
ModProgram.sh $1 "glutils\.h" "GlUtils\.h"
ModProgram.sh $1 "glwk_rec\.wk_" "glwkRec\."
ModProgram.sh $1 "glwk_rec\.wk_" "glwkRec\."
ModProgram.sh $1 "glwk_rec" "glwkRec"
ModProgram.sh $1 "glwkRec\.date" "glwkRec\.tran_date"
ModProgram.sh $1 "glus_rec\." "glusRec\."
ModProgram.sh $1 "glus_rec" "glusRec"
ModProgram.sh $1 "_post_acc" "_POSTACC_XXXXX"
ModProgram.sh $1 "_POSTACC_XXXXX" "_PostAccount"
ModProgram.sh $1 "post_acc" "GL_PostAccount"
ModProgram.sh $1 "post_budget" "GL_PostBudget"
ModProgram.sh $1 "post_setup" "GL_PostSetup"
ModProgram.sh $1 "read_currency" "FindPocr"
ModProgram.sh $1 "read_glct" "FindGlct"
ModProgram.sh $1 "set_acc_width" "GL_SetAccWidth"
ModProgram.sh $1 "set_bit_width" "GL_SetBitWidth"
ModProgram.sh $1 "set_masks" "set_XXXXX"
ModProgram.sh $1 "get_bit" "GL_GetBit"
ModProgram.sh $1 "set_mask" "GL_SetMask"
ModProgram.sh $1 "set_XXXXX" "set_masks"
ModProgram.sh $1 "strip_form" "GL_StripForm"
ModProgram.sh $1 "sys_date" "systemDate"
ModProgram.sh $1 "tot_glpd" "GL_LocTotGlpd"
ModProgram.sh $1 "valid_UserCode" "GL_ValidUserCode"
ModProgram.sh $1 "open_batch_db" "GL_OpenBatch"
ModProgram.sh $1 "close_batch_db" "GL_CloseBatch"
ModProgram.sh $1 "CloseGL" "GL_Close"
ModProgram.sh $1 "comm_no_fields" "COMM_NO_FIELDS"
ModProgram.sh $1 "glaudit.h" "GlAudit.h"
ModProgram.sh $1 "curr_lib.h" "DELETE.h"
ModProgram.sh $1 "post_terminate" "GL_PostTerminate"
ModProgram.sh $1 "aud_close" "GL_AudClose"
ModProgram.sh $1 "aud_open" "GL_AudOpen"
ModProgram.sh $1 "aud_save" "GL_AudSave"
ModProgram.sh $1 "aud_get" "GL_AudGet"
ModProgram.sh $1 "aud_name" "GL_AudName"
ModProgram.sh $1 "aud_header" "GL_AudHeader"
ModProgram.sh $1 "aud_trailer" "GL_AudTrailer"
ModProgram.sh $1 "aud_setup" "GL_AudSetup"
ModProgram.sh $1 "pocr_rec\.pocr_" "pocrRec\."
ModProgram.sh $1 "pocr_rec" "pocrRec"
ModProgram.sh $1 "\"pocr\"" "pocr"
ModProgram.sh $1 "GLI" "GL_GLI"
ModProgram.sh $1 "rd_base_curr" "DELETE"
ModProgram.sh $1 "GL_GL_GLI" "GL_GLI"
ModProgram.sh $1 "bkcr_rec\.cr_" "bkcr_rec\."
ModProgram.sh $1 "bkdt_rec\.dt_" "bkdt_rec\."
ModProgram.sh $1 "bldt_rec\.dt_" "bldt_rec\."
ModProgram.sh $1 "blhd_rec\.hd_" "blhd_rec\."
ModProgram.sh $1 "crbk_rec\.bk_" "crbk_rec\."
ModProgram.sh $1 "cudt_rec\.dt_" "cudt_rec\."
ModProgram.sh $1 "cuhd_rec\.hd_" "cuhd_rec\."
ModProgram.sh $1 "cuin_rec\.in_" "cuin_rec\."
ModProgram.sh $1 "cumr_rec\.mr_" "cumr_rec\."
ModProgram.sh $1 "pocr_rec\.cr_" "pocr_rec\."
ModProgram.sh $1 "suhp_rec\.hp_" "suhp_rec\."
ModProgram.sh $1 "suhp_no_fields" "SUHP_NO_FIELDS"
ModProgram.sh $1 "suht_no_fields" "SUHT_NO_FIELDS"
ModProgram.sh $1 "\"suhp\"" "suhp"
ModProgram.sh $1 "suht_rec\.ht_" "suht_rec\."
ModProgram.sh $1 "\"suht\"" "suht"
ModProgram.sh $1 "pocrRec\.cr_" "pocrRec\."
ModProgram.sh $1 "add_batch" "GL_AddBatch"
ModProgram.sh $1 "co_owned" "envDbCo"
ModProgram.sh $1 "db_find" "envDbFind"
ModProgram.sh $1 "estab" "branchNo"
ModProgram.sh $1 "head1_flg" "headingFlag1"
ModProgram.sh $1 "head2_flg" "headingFlag2"
ModProgram.sh $1 "next_line" "nextLine"
ModProgram.sh $1 "print_dtl2" "PrintDetails2"
ModProgram.sh $1 "print_tot2" "PrintTotals2"
ModProgram.sh $1 "print_dtl" "PrintDetails"
ModProgram.sh $1 "print_tot" "PrintTotals"
ModProgram.sh $1 "sleep (1);" "sleep (sleepTime);"
ModProgram.sh $1 "sleep (SLEEP_TIME);" "sleep (sleepTime);"
ModProgram.sh $1 "sleep (2);" "sleep (sleepTime);"
ModProgram.sh $1 "sleep (3);" "sleep (sleepTime);"
ModProgram.sh $1 "sleep (4);" "sleep (sleepTime);"
ModProgram.sh $1 "sleep (5);" "sleep (sleepTime);"
ModProgram.sh $1 "last_char == SEARCH" "SRCH_KEY"
ModProgram.sh $1 "N (o" "N(o"
ModProgram.sh $1 "Y (es" "Y(es"

ModProgram.sh $1 "suin_rec\.hp_" "suin_rec\."
ModProgram.sh $1 "suin_no_fields" "SUIN_NO_FIELDS"
ModProgram.sh $1 "\"suin\"" "suin"

ModProgram.sh $1 "sumr_rec\.sm_" "sumr_rec\."
ModProgram.sh $1 "sumr_no_fields" "SUMR_NO_FIELDS"
ModProgram.sh $1 "\"sumr\"" "sumr"

ModProgram.sh $1 "suhd_rec\.hd_" "suhd_rec\."
ModProgram.sh $1 "suhd_no_fields" "SUHD_NO_FIELDS"
ModProgram.sh $1 "\"suhd\"" "suhd"

ModProgram.sh $1 "sudt_rec\.hd_" "sudt_rec\."
ModProgram.sh $1 "sudt_no_fields" "SUDT_NO_FIELDS"
ModProgram.sh $1 "\"sudt\"" "sudt"

ModProgram.sh $1 "inmr_rec\.mr_" "inmr_rec\."
ModProgram.sh $1 "inmr_rec\.im_" "inmr_rec\."
ModProgram.sh $1 "inmr_no_fields" "INMR_NO_FIELDS"
ModProgram.sh $1 "\"inmr\"" "inmr"
ModProgram.sh $1 "inmr_rec\.class" "inmr_rec\.inmr_class"

ModProgram.sh $1 "sumr_rec\.sm_" "sumr_rec\."
ModProgram.sh $1 "sumr_rec\.mr_" "sumr_rec\."
ModProgram.sh $1 "sumr_no_fields" "SUMR_NO_FIELDS"
ModProgram.sh $1 "\"sumr\"" "sumr"

ModProgram.sh $1 "cumr_rec\.cm_" "cumr_rec\."
ModProgram.sh $1 "cumr_rec\.mr_" "cumr_rec\."
ModProgram.sh $1 "cumr_no_fields" "CUMR_NO_FIELDS"
ModProgram.sh $1 "\"cumr\"" "cumr"

ModProgram.sh $1 "incc_rec\.cc_" "incc_rec\."
ModProgram.sh $1 "incc_rec\.cm_" "incc_rec\."
ModProgram.sh $1 "incc_no_fields" "INCC_NO_FIELDS"
ModProgram.sh $1 "\"incc\"" "incc"

ModProgram.sh $1 "ccmr_rec\.cc_" "ccmr_rec\."
ModProgram.sh $1 "ccmr_rec\.cm_" "ccmr_rec\."
ModProgram.sh $1 "ccmr_no_fields" "CCMR_NO_FIELDS"
ModProgram.sh $1 "\"ccmr\"" "ccmr"
ModProgram.sh $1 "ccmr_rec\.no" "ccmr_rec\.cc_no"

ModProgram.sh $1 "insf_rec\.in_" "insf_rec\."
ModProgram.sh $1 "insf_rec\.sf_" "insf_rec\."
ModProgram.sh $1 "insf_no_fields" "INSF_NO_FIELDS"
ModProgram.sh $1 "\"insf\"" "insf"

ModProgram.sh $1 "suin_rec\.in_" "suin_rec\."
ModProgram.sh $1 "suin_rec\.sf_" "suin_rec\."
ModProgram.sh $1 "suin_no_fields" "SUIN_NO_FIELDS"
ModProgram.sh $1 "\"suin\"" "suin"
ModProgram.sh $1 "pin_today" "TodaysDate"

ModProgram.sh $1 "coln_rec\.ln_" "coln_rec\."
ModProgram.sh $1 "coln_rec\.co_" "coln_rec\."
ModProgram.sh $1 "coln_no_fields" "COLN_NO_FIELDS"
ModProgram.sh $1 "\"coln\"" "coln"

ModProgram.sh $1 "cohr_rec\.hr_" "cohr_rec\."
ModProgram.sh $1 "cohr_no_fields" "COHR_NO_FIELDS"
ModProgram.sh $1 "\"cohr\"" "cohr"

ModProgram.sh $1 "arhr_rec\.hr_" "arhr_rec\."
ModProgram.sh $1 "arhr_rec\.ar_" "arhr_rec\."
ModProgram.sh $1 "arhr_no_fields" "ARHR_NO_FIELDS"
ModProgram.sh $1 "\"arhr\"" "arhr"

ModProgram.sh $1 "arln_rec\.ln_" "arln_rec\."
ModProgram.sh $1 "arln_rec\.ar_" "arln_rec\."
ModProgram.sh $1 "arln_no_fields" "ARLN_NO_FIELDS"

ModProgram.sh $1 "excf_rec\.cf_" "excf_rec\."
ModProgram.sh $1 "excf_rec\.ex_" "excf_rec\."
ModProgram.sh $1 "excf_no_fields" "EXCF_NO_FIELDS"

ModProgram.sh $1 "esmr_rec\.es_" "esmr_rec\.est_"

ModProgram.sh $1 "return (1);" "return (EXIT_FAILURE);"
ModProgram.sh $1 "return (0);" "return (EXIT_SUCCESS);"

ModProgram.sh $1 "inaf_rec\.systemDate" "inaf_rec\.sys_date"

ModProgram.sh $1 "inum_rec\.um_" "inum_rec\."
ModProgram.sh $1 "inum_rec\.in_" "inum_rec\."
ModProgram.sh $1 "inum2_rec\.um_" "inum_rec\."
ModProgram.sh $1 "inum2_rec\.in_" "inum_rec\."
ModProgram.sh $1 "inum3_rec\.um_" "inum_rec\."
ModProgram.sh $1 "inum3_rec\.in_" "inum_rec\."
ModProgram.sh $1 "inum_no_fields" "INUM_NO_FIELDS"

ModProgram.sh $1 "cumd_rec\.md_" "cumd_rec\."
ModProgram.sh $1 "cumd_rec\.cu_" "cumd_rec\."
ModProgram.sh $1 "cumd_no_fields" "CUMD_NO_FIELDS"

ModProgram.sh $1 "ingd_rec\.gd_" "ingd_rec\."
ModProgram.sh $1 "ingd_no_fields" "INGD_NO_FIELDS"

ModProgram.sh $1 "polh_rec\.lh_" "polh_rec\."
ModProgram.sh $1 "polh_no_fields" "POLH_NO_FIELDS"

ModProgram.sh $1 "podt_rec\.dt_" "podt_rec\."
ModProgram.sh $1 "podt_no_fields" "PODT_NO_FIELDS"

ModProgram.sh $1 "exdf_rec\.df_" "exdf_rec\."
ModProgram.sh $1 "exdf_no_fields" "EXDF_NO_FIELDS"

ModProgram.sh $1 "sjhr_rec\.hr_" "sjhr_rec\."
ModProgram.sh $1 "sjhr_no_fields" "SJHR_NO_FIELDS"
ModProgram.sh $1 "\"sjhr\"" "sjhr"

ModProgram.sh $1 "sjjd_rec\.jd_" "sjjd_rec\."
ModProgram.sh $1 "sjjd_no_fields" "SJJD_NO_FIELDS"
ModProgram.sh $1 "\"sjjd\"" "sjjd"

ModProgram.sh $1 "sjig_rec\.ig_" "sjig_rec\."
ModProgram.sh $1 "sjig_no_fields" "SJIG_NO_FIELDS"
ModProgram.sh $1 "\"sjig\"" "sjig"

ModProgram.sh $1 "sjdc_rec\.dc_" "sjdc_rec\."
ModProgram.sh $1 "sjdc_no_fields" "SJDC_NO_FIELDS"
ModProgram.sh $1 "\"sjdc\"" "sjdc"

ModProgram.sh $1 "sjis_rec\.is_" "sjis_rec\."
ModProgram.sh $1 "sjis_no_fields" "SJIS_NO_FIELDS"
ModProgram.sh $1 "\"sjis\"" "sjis"

ModProgram.sh $1 "sjis2_rec\.is_" "sjis2_rec\."
ModProgram.sh $1 "\"sjis2\"" "sjis2"

ModProgram.sh $1 "sjsp_rec\.sp_" "sjsp_rec\."
ModProgram.sh $1 "sjsp_no_fields" "SJSP_NO_FIELDS"
ModProgram.sh $1 "\"sjsp\"" "sjsp"

ModProgram.sh $1 "sjld_rec\.ld_" "sjld_rec\."
ModProgram.sh $1 "sjld_no_fields" "SJLD_NO_FIELDS"
ModProgram.sh $1 "\"sjld\"" "sjld"

ModProgram.sh $1 "sjcr_rec\.cr_" "sjcr_rec\."
ModProgram.sh $1 "sjcr_no_fields" "SJCR_NO_FIELDS"
ModProgram.sh $1 "\"sjcr\"" "sjcr"

ModProgram.sh $1 "cudp_rec\.dp_" "cudp_rec\."
ModProgram.sh $1 "cudp_no_fields" "CUDP_NO_FIELDS"
ModProgram.sh $1 "\"cudp\"" "cudp"
ModProgram.sh $1 "cudp_rec\.no" "cudp_rec\.dp_no"

ModProgram.sh $1 "esmr_rec\.es_" "esmr_rec\."
ModProgram.sh $1 "esmr_rec\.mr_" "esmr_rec\."
ModProgram.sh $1 "esmr_no_fields" "ESMR_NO_FIELDS"
ModProgram.sh $1 "\"esmr\"" "esmr"
ModProgram.sh $1 "esmr_rec\.no" "esmr_rec\.est_no"

ModProgram.sh $1 "cumr_rec\.name" "cumr_rec\.dbt_name"

ModProgram.sh $1 "extr_rec\.ex_" "extr_rec\."
ModProgram.sh $1 "extr_rec\.tr_" "extr_rec\."
ModProgram.sh $1 "extr_no_fields" "EXTR_NO_FIELDS"
ModProgram.sh $1 "\"extr\"" "extr"

ModProgram.sh $1 "cmhr_rec\.hr_" "cmhr_rec\."
ModProgram.sh $1 "cmhr_no_fields" "CMHR_NO_FIELDS"
ModProgram.sh $1 "\"cmhr\"" "cmhr"

ModProgram.sh $1 "cmcd_rec\.cd_" "cmcd_rec\."
ModProgram.sh $1 "cmcd_no_fields" "CMCD_NO_FIELDS"
ModProgram.sh $1 "\"cmcd\"" "cmcd"

ModProgram.sh $1 "cudi_rec\.di_" "cudi_rec\."
ModProgram.sh $1 "cudi_no_fields" "CUDI_NO_FIELDS"
ModProgram.sh $1 "\"cudi\"" "cudi"

ModProgram.sh $1 "cmjt_rec\.jt_" "cmjt_rec\."
ModProgram.sh $1 "cmjt_no_fields" "CMJT_NO_FIELDS"
ModProgram.sh $1 "\"cmjt\"" "cmjt"

ModProgram.sh $1 "cmjt_rec\.jt_" "cmjt_rec\."
ModProgram.sh $1 "cmjt_no_fields" "CMJT_NO_FIELDS"
ModProgram.sh $1 "\"cmjt\"" "cmjt"

ModProgram.sh $1 "cmit_rec\.it_" "cmit_rec\."
ModProgram.sh $1 "cmit_no_fields" "CMIT_NO_FIELDS"
ModProgram.sh $1 "\"cmit\"" "cmit"

ModProgram.sh $1 "cmws_rec\.ws_" "cmws_rec\."
ModProgram.sh $1 "cmws_no_fields" "CMWS_NO_FIELDS"
ModProgram.sh $1 "\"cmws\"" "cmws"

ModProgram.sh $1 "cmts_rec\.ts_" "cmts_rec\."
ModProgram.sh $1 "cmts_no_fields" "CMTS_NO_FIELDS"
ModProgram.sh $1 "\"cmts\"" "cmts"

ModProgram.sh $1 "cmtr_rec\.tr_" "cmtr_rec\."
ModProgram.sh $1 "cmtr_no_fields" "CMTR_NO_FIELDS"
ModProgram.sh $1 "\"cmtr\"" "cmtr"

ModProgram.sh $1 "cmcb_rec\.cb_" "cmcb_rec\."
ModProgram.sh $1 "cmcb_no_fields" "CMCB_NO_FIELDS"
ModProgram.sh $1 "\"cmcb\"" "cmcb"

ModProgram.sh $1 "cmcb2_rec\.cb_" "cmcb2_rec\."
ModProgram.sh $1 "\"cmcb2\"" "cmcb2"

ModProgram.sh $1 "cmhr_rec\.hr_" "cmhr_rec\."
ModProgram.sh $1 "cmhr2_rec\.hr_" "cmhr2_rec\."
ModProgram.sh $1 "cmhr_no_fields" "CMHR_NO_FIELDS"
ModProgram.sh $1 "\"cmhr\"" "cmhr"
ModProgram.sh $1 "\"cmhr2\"" "cmhr2"

ModProgram.sh $1 "cmjd_rec\.jd_" "cmjd_rec\."
ModProgram.sh $1 "cmjd_no_fields" "CMJD_NO_FIELDS"
ModProgram.sh $1 "\"cmjd\"" "cmjd"

ModProgram.sh $1 "cmjt_rec\.jt_" "cmjt_rec\."
ModProgram.sh $1 "cmjt_no_fields" "CMJT_NO_FIELDS"
ModProgram.sh $1 "\"cmjt\"" "cmjt"

ModProgram.sh $1 "cmcm_rec\.cm_" "cmcm_rec\."
ModProgram.sh $1 "cmcm_no_fields" "CMCM_NO_FIELDS"
ModProgram.sh $1 "\"cmcm\"" "cmcm"

ModProgram.sh $1 "cmpb_rec\.cm_" "cmpb_rec\."
ModProgram.sh $1 "cmpb_no_fields" "CMPB_NO_FIELDS"
ModProgram.sh $1 "\"cmpb\"" "cmpb"

ModProgram.sh $1 "cmrd_rec\.cm_" "cmrd_rec\."
ModProgram.sh $1 "cmrd_no_fields" "CMRD_NO_FIELDS"
ModProgram.sh $1 "\"cmrd\"" "cmrd"

ModProgram.sh $1 "cmrh_rec\.rh_" "cmrh_rec\."
ModProgram.sh $1 "cmrh_no_fields" "CMRH_NO_FIELDS"
ModProgram.sh $1 "\"cmrh\"" "cmrh"

ModProgram.sh $1 "cmem_rec\.em_" "cmem_rec\."
ModProgram.sh $1 "cmem_no_fields" "CMEM_NO_FIELDS"
ModProgram.sh $1 "\"cmem\"" "cmem"

ModProgram.sh $1 "cmeq_rec\.eq_" "cmeq_rec\."
ModProgram.sh $1 "cmeq_no_fields" "CMEQ_NO_FIELDS"
ModProgram.sh $1 "\"cmeq\"" "cmeq"

ModProgram.sh $1 "cmer_rec\.er_" "cmer_rec\."
ModProgram.sh $1 "cmer_no_fields" "CMER_NO_FIELDS"
ModProgram.sh $1 "\"cmer\"" "cmer"

ModProgram.sh $1 "tmcf_rec\.cf_" "tmcf_rec\."
ModProgram.sh $1 "tmcf_no_fields" "TMCF_NO_FIELDS"
ModProgram.sh $1 "\"tmcf\"" "tmcf"

ModProgram.sh $1 "tmxf_rec\.xf_" "tmxf_rec\."
ModProgram.sh $1 "tmxf_no_fields" "TMXF_NO_FIELDS"
ModProgram.sh $1 "\"tmxf\"" "tmxf"

ModProgram.sh $1 "tmud_rec\.ud_" "tmud_rec\."
ModProgram.sh $1 "tmud_no_fields" "TMUD_NO_FIELDS"
ModProgram.sh $1 "\"tmud\"" "tmud"

ModProgram.sh $1 "tmah_rec\.ah_" "tmah_rec\."
ModProgram.sh $1 "tmah_no_fields" "TMAH_NO_FIELDS"
ModProgram.sh $1 "\"tmah\"" "tmah"

ModProgram.sh $1 "tmal_rec\.al_" "tmal_rec\."
ModProgram.sh $1 "tmal_no_fields" "TMAL_NO_FIELDS"
ModProgram.sh $1 "\"tmal\"" "tmal"

ModProgram.sh $1 "tmoh_rec\.oh_" "tmoh_rec\."
ModProgram.sh $1 "tmoh_no_fields" "TMOH_NO_FIELDS"
ModProgram.sh $1 "\"tmoh\"" "tmoh"

ModProgram.sh $1 "tmop_rec\.op_" "tmop_rec\."
ModProgram.sh $1 "tmop_no_fields" "TMOP_NO_FIELDS"
ModProgram.sh $1 "\"tmop\"" "tmop"
ModProgram.sh $1 "tmop_rec\.id" "tmop_rec\.op_id"
ModProgram.sh $1 "tmop_rec\.name" "tmop_rec\.op_name"

ModProgram.sh $1 "tmpm_rec\.pm_" "tmpm_rec\."
ModProgram.sh $1 "tmpm_no_fields" "TMPM_NO_FIELDS"
ModProgram.sh $1 "\"tmpm\"" "tmpm"

ModProgram.sh $1 "tmsh_rec\.sh_" "tmsh_rec\."
ModProgram.sh $1 "tmsh_no_fields" "TMSH_NO_FIELDS"
ModProgram.sh $1 "\"tmsh\"" "tmsh"

ModProgram.sh $1 "tmsl_rec\.sl_" "tmsl_rec\."
ModProgram.sh $1 "tmsl_no_fields" "TMSL_NO_FIELDS"
ModProgram.sh $1 "\"tmsl\"" "tmsl"

ModProgram.sh $1 "tmch_rec\.ch_" "tmch_rec\."
ModProgram.sh $1 "tmch_no_fields" "TMCH_NO_FIELDS"
ModProgram.sh $1 "\"tmch\"" "tmch"

ModProgram.sh $1 "tmcl_rec\.cl_" "tmcl_rec\."
ModProgram.sh $1 "tmcl_no_fields" "TMCL_NO_FIELDS"
ModProgram.sh $1 "\"tmcl\"" "tmcl"

ModProgram.sh $1 "tmdl_rec\.dl_" "tmdl_rec\."
ModProgram.sh $1 "tmdl_no_fields" "TMDL_NO_FIELDS"
ModProgram.sh $1 "\"tmdl\"" "tmdl"
ModProgram.sh $1 "tmdl_rec\.length" "tmdl_rec\.tmdl_length"
ModProgram.sh $1 "tmdl_rec\.default" "tmdl_rec\.tmdl_default"

ModProgram.sh $1 "tmdf_rec\.df_" "tmdf_rec\."
ModProgram.sh $1 "tmdf_no_fields" "TMDF_NO_FIELDS"
ModProgram.sh $1 "\"tmdf\"" "tmdf"

ModProgram.sh $1 "tmlh_rec\.lh_" "tmlh_rec\."
ModProgram.sh $1 "tmlh_no_fields" "TMLH_NO_FIELDS"
ModProgram.sh $1 "\"tmlh\"" "tmlh"

ModProgram.sh $1 "tmln_rec\.ln_" "tmln_rec\."
ModProgram.sh $1 "tmln_no_fields" "TMLN_NO_FIELDS"
ModProgram.sh $1 "\"tmln\"" "tmln"

ModProgram.sh $1 "tmrc_rec\.rc_" "tmrc_rec\."
ModProgram.sh $1 "tmrc_no_fields" "TMRC_NO_FIELDS"
ModProgram.sh $1 "\"tmrc\"" "tmrc"

ModProgram.sh $1 "comr_rec\.mr_" "comr_rec\."
ModProgram.sh $1 "comr_no_fields" "COMR_NO_FIELDS"
ModProgram.sh $1 "\"comr\"" "comr"

ModProgram.sh $1 "tmof_rec\.of_" "tmof_rec\."
ModProgram.sh $1 "tmof_no_fields" "TMOF_NO_FIELDS"
ModProgram.sh $1 "\"tmof\"" "tmof"
