ModProgram.sh $1 "finish_prog" "DELETE"
ModProgram.sh $1 "delete_tab" "DELETE"
ModProgram.sh $1 "CloseDB()" "CloseDB (); FinishProgram ();"
ModProgram.sh $1 "CloseDB ()" "CloseDB (); FinishProgram ();"
ModProgram.sh $1 "CloseDB	()" "CloseDB (); FinishProgram ();"
