#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:01:11 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:01:11  scott
#	RELEASE 5.0
#	
#
#

APP		=	cr_cheq_del
SRCS	=	cheq_del.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
