#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:49 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:49  scott
#	Update - LS10.5
#	
#	Revision 5.0  2001/06/19 08:15:03  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/03/22 03:55:59  scott
#	Updated to ensure sleep was included in error message.
#	Updated to add app.schema - removes code related to tables from program and
#	allows for better quality contol.
#	Updated to perform routine maintenance to ensure standards are maintained.
#	
#
#

APP		=	sk_alt_dsp
SRCS	=	sk_alt_dsp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
