#
# makefile for set_tslot.
#
#	Generated - on : 17/03/90
#	          - at : 01:09:30 AM
#	          - by : root
#

SHELL   = /bin/sh

OBJS = set_tslot.o

TARGET = $(DESTDIR)/set_tslot

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
