#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:55:54 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:55:54  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:22:00  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/04/03 10:23:50  scott
#	Basically a TOTAL REWRITE to work with LS10-GUI
#	Updated to add app.schema - removes code related to tables from program as it
#	allows for better quality contol.
#	Updated to add sleep delay - did not work with LS10-GUI
#	Updated to adjust screen to look better with LS10-GUI
#	Updated to perform routine maintenance to ensure standards are maintained.
#	
#
#

APP		=	ts_call
SRCS	=	ts_call.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
