#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/13 05:48:10 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/13 05:48:10  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	sk_cus_disc
SRCS	=	cus_disc.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
