#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/19 02:37:01 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/19 02:37:01  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_bkl_prn
SRCS	=	db_bkl_prn.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
