#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 22:52:21 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 22:52:21  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:01:20  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 01:46:13  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:11:46  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 08:36:47  gerry
#	Force Revision No Start 2.0 Rel-15072000
#	
#	Revision 1.2  2000/07/10 09:36:00  scott
#	S/C SEL-16442 / LSDI-3045
#	(1) Updated to remove test on seq of zero as per service call.
#	(2) Added app.schema + clean code.
#	
#
#

APP		=	bm_maint
SRCS	=	bm_maint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
