#
# makefile for po_mnt_reps.
#
#	Generated - on : 21/09/90
#	          - at : 10:28:23 AM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = mnt_reps.o

TARGET = $(DESTDIR)/po_mnt_reps

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
