#
# makefile for psl_su_id.
#
#	Generated - on : 05/07/91
#	          - at : 02:05:36 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = psl_su_id.o

TARGET = $(DESTDIR)/psl_su_id

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
