#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.0 2002/05/07 10:18:45 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.0  2002/05/07 10:18:45  scott
#	Updated to bring version number to 5.0
#	
#	Revision 1.1  2002/05/02 03:37:43  scott
#	New Program
#	
#

APP		=	so_ar_disp
SRCS	=	so_ar_disp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
