#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/20 08:10:04 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/20 08:10:04  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_lclose
SRCS	=	db_lclose.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
