#
# makefile for sk_mr_spri.
#
#	Generated - on : 23/08/89
#	          - at : 11:37:44 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = sk_mr_spri.o

TARGET = $(DESTDIR)/sk_mr_spri

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
