#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2001/08/06 23:32:08 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2001/08/06 23:32:08  scott
#	RELEASE 5.0
#	
#	Revision 5.1  2001/07/25 02:18:13  scott
#	Update - LS10.5
#	
#
#

APP		=	all_select
SRCS	=	all_select.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
