#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/06 03:04:28 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/06 03:04:28  scott
#	Updated from testing.
#	
#
#

APP		=	dd_ord_conf
SRCS	=	ord_conf.c
ALTS	=	dd_sup_conf

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
