#
# makefile for pc_recprt.
#
#	Generated - on : 21/05/92
#	          - at : 11:57:51 AM
#	          - by : trev
#

SHELL   = /bin/sh

OBJS = pc_recprt.o

TARGET = $(DESTDIR)/pc_recprt

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
