#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.0 2002/05/08 01:22:11 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.0  2002/05/08 01:22:11  scott
#	CVS administration
#	
#	Revision 1.2  2001/08/06 23:31:22  scott
#	RELEASE 5.0
#	
#	Revision 1.1  2001/06/22 06:27:48  scott
#	New program
#	
#

APP		=	gl_BatchRoundFix
SRCS	=	gl_BatchRoundFix.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
