#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:19:53 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:19:53  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:40:29  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:22:02  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/10/04 06:53:21  scott
#	Updated to use app.schema
#	
#
#

APP		=	so_ccn_inp
SRCS	=	so_ccn_inp.c
ALTS	=	so_ccn_dsp so_ccn_sdsp so_ccn_conf

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
