#
# makefile for pc_empmnt.
#
#	Generated - on : 29/07/92
#	          - at : 05:18:51 PM
#	          - by : trev
#

SHELL   = /bin/sh

OBJS = pc_empmnt.o

TARGET = $(DESTDIR)/pc_empmnt

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
