#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:39:43 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:39:43  scott
#	RELEASE 5.0
#	
#
#

APP		=	rg_res_dsp
SRCS	=	rg_res_dsp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
