#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/14 05:21:27 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/14 05:21:27  scott
#	Updated to convert to app.schema
#	
#
#

APP		=	tm_ld_load
SRCS	=	tm_ld_load.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
