#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:27:37 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:27:37  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:07:27  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:28:36  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:15:30  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 08:58:41  gerry
#	Forced Revision No. Start 2.0 Rel-15072000
#	
#	Revision 1.3  2000/07/05 00:10:49  scott
#	General Maintenance - Added app.schema
#	
#
#

APP		=	lrp_noinis
ALTS	=	lrp_ssinis lrp_any_inis
SRCS	=	lrp_noinis.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
