#
# makefile for eoday.
#
#	Generated - on : 16/03/90
#	          - at : 05:13:04 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = eoday.o

TARGET = $(DESTDIR)/eoday

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
