#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:51:29 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:51:29  scott
#	RELEASE 5.0
#	
#
#

APP		=	so_lostsale
SRCS	=	lostsale.c
ALTS	=	../OL/ol_lostsale

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
