#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2001/12/07 03:30:33 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2001/12/07 03:30:33  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#	Revision 5.1  2001/11/21 01:58:19  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_cn_maint
SRCS	=	db_cn_maint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
