#
# makefile for warning.
#
#	Generated - on : 23/08/89
#	          - at : 10:40:55 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = warning.o

TARGET = $(DESTDIR)/warning

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
