#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:19:48 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:19:48  scott
#	Update - LS10.5
#	
#	Revision 4.1  2001/04/06 07:45:46  scott
#	Updated to add app.schema - removes code related to tables from program as it
#	allows for better quality contol.
#	Updated to perform routine maintenance to ensure standards are maintained.
#	
#
#

APP		=	so_audit
SRCS	=	so_audit.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
