#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/09/19 00:38:23 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/09/19 00:38:23  scott
#	General cleanup while looking at code.
#	
#
#

APP		=	fa_depdisp
SRCS	=	fa_depdisp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
