#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.0 2002/05/08 01:45:35 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.0  2002/05/08 01:45:35  scott
#	CVS administration
#	
#	Revision 4.1  2001/08/07 00:08:02  scott
#	RELEASE 5.0
#	
#	Revision 4.0  2001/03/09 02:27:53  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 2.0  2000/07/15 07:30:57  gerry
#	Forced Revision no. start to 2.0 - Rel-15072000
#	
#	Revision 1.1  1999/11/16 23:19:49  scott
#	Re-created lc_demo
#	
#	Revision 1.1  1999/11/15 23:20:34  scott
#	Updated Licence
#	
#	
#	
#	
APP		=	lc_demo
SRCS	=	lc_demo.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
