#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.1 2001/08/06 23:01:47 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:01:47  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:03:49  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:24:16  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:13:12  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 08:41:10  gerry
#	Forced Revision No. Start 2.0 Rel-15072000
#	
#	Revision 1.2  1999/11/11 06:58:04  scott
#	Added app.schema
#	
#	
#	
#	
#	
APP		=	cr_trandsp
SRCS	=	cr_trandsp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
