#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/27 08:11:35 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/27 08:11:35  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_tranpr
SRCS	=	db_tranpr.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
