#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/07/03 05:18:57 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/07/03 05:18:57  scott
#	Updated to add SetSortArray () for new LS10-GUI screen features
#	
#
#

APP		=	sj_ldmaint
SRCS	=	sj_ldmaint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
