#
# makefile for pinform.
#
#	Generated - on : 16/10/91
#	          - at : 02:35:24 PM
#	          - by : trev
#

SHELL   = /bin/sh

OBJS = pinform.o

TARGET = $(DESTDIR)/pinform

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
