#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/26 03:42:30 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/26 03:42:30  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_lageing.i
SRCS	=	db_lageing.i.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
