#
# makefile for get_secure.
#
#	Generated - on : 23/08/89
#	          - at : 10:39:22 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = get_secure.o

TARGET	= $(DESTDIR)/get_secure

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
