#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/06/25 06:16:26 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/06/25 06:16:26  scott
#	Updated for problems on GUI with two screens on one.
#	
#
#

APP		=	sk_ius_maint
SRCS	=	sk_ius_maint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
