#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/05/09 04:16:55 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/05/09 04:16:55  scott
#	Updated to convert to app.schema
#	
#
#

APP		=	bm_uom_mnt
SRCS	=	bm_uom_mnt.c
ALTS	=	../SK/sk_uom_mnt

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
