#
# makefile for psl_date.
#
#	Generated - on : 03/05/93
#	          - at : 05:36:51 PM
#	          - by : trev
#

SHELL   = /bin/sh

OBJS = psl_date.o

TARGET = $(DESTDIR)/psl_date

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
