#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/14 05:05:38 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/14 05:05:38  scott
#	Updated to convert to app.schema
#	Updated to clean code.
#	
#
#

APP		=	tm_dflt_fmt
SRCS	=	dflt_fmt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
