#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 22:56:19 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 22:56:19  scott
#	RELEASE 5.0
#	
#
#

APP		=	cm_invtogl
SRCS	=	cm_invtogl.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
