#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/10 07:19:07 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/10 07:19:07  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	sk_whmaint
SRCS	=	sk_whmaint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
