#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:51:12 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:51:12  scott
#	RELEASE 5.0
#	
#

APP		=	so_des_conf
SRCS	=	des_conf.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
