#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.1 2001/08/06 23:01:43 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:01:43  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:03:43  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:24:10  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:13:08  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 08:41:06  gerry
#	Forced Revision No. Start 2.0 Rel-15072000
#	
#	Revision 1.2  1999/11/11 04:25:27  scott
#	Added app.schema
#	
#	Revision 1.2  1999/11/11 03:44:25  scott
#	Updated for app.schema
#	
#	
#	
#	
APP		=	cr_period_up
SRCS	=	period_up.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
