#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:16:57 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:16:57  scott
#	Update - LS10.5
#	
#	Revision 5.0  2001/06/19 08:03:54  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/03/09 06:03:08  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 4.0  2001/03/09 02:24:21  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:13:21  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/09/06 07:48:52  scott
#	Updated to add new customer search - same as stock search.
#	Some general maintenance was performed to add app.schema to some old code.
#	
#
#

APP		=	db_allinp
SRCS	=	db_allinp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
