#
# makefile for ol_savdel.
#
#	Generated - on : 26/09/89
#	          - at : 09:31:28 AM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = ol_savdel.o

TARGET = $(DESTDIR)/ol_savdel

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
