#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/14 02:41:44 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/14 02:41:44  scott
#	Updated to convert to app.schema
#	Updated to clean code.
#	
#
#

APP		=	tm_call
SRCS	=	tm_call.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
