#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:44:56 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:44:56  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:15:41  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/03/16 07:56:12  scott
#	Updated to ensure screen selections looks and works OK with LS10-GUI.
#	Updated to clean code and add app.schema
#	
#
#

APP		=	sk_group.i
SRCS	=	sk_group.i.c
ALTS	=	sk_groupc.i

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
