#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:50:44 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:50:44  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:18:30  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/05/31 10:00:25  scott
#	Updated to add app.schema
#	
#
#

APP		=	so_allskcalc
SRCS	=	allskcalc.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
