#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:52:03 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:52:03  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:20:41  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:41:56  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2000/12/06 09:34:27  scott
#	First release before testing - almost total re-write.
#	
#
#

APP		=	so_sdmaint
SRCS	=	so_sdmaint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
