#
# makefile for unload_env.
#
#	Generated - on : 01/11/89
#	          - at : 02:22:02 PM
#	          - by : rog
#

SHELL   = /bin/sh

OBJS = unload_env.o

TARGET = $(DESTDIR)/unload_env

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
