#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:50:43 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:50:43  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:18:29  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:40:00  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:21:44  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/08/22 03:06:18  scott
#	Updated to ensure packing slips are printed before auto confirmation allowed.
#	
#
#

APP		=	so_ades_conf
SRCS	=	ades_conf.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
