#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/19 01:52:18 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/19 01:52:18  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_balwin
SRCS	=	db_balwin.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
