#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.1 2001/08/06 23:45:04 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:45:04  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:16:00  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:37:19  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:20:16  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 09:10:55  gerry
#	Forced Revision No Start 2.0 Rel-15072000
#	
#	Revision 1.2  1999/11/22 06:59:05  scott
#	Updated to ensure itff is deleted.
#	
#	Revision 1.1  1999/11/16 09:52:40  scott
#	Added to so would not come up on cvs update all the time.
#	
#	
#	
#	
APP		=	sk_ir_del
SRCS	=	sk_ir_del.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
