#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:01:12 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:01:12  scott
#	RELEASE 5.0
#	
#
#

APP		=	cr_cheqlist
SRCS	=	cheqlist.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
