#
# makefile for make_doco.
#
#	Generated - on : 23/10/90
#	          - at : 10:38:19 AM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = make_doco.o

TARGET = $(DESTDIR)/make_doco

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
