#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/22 06:38:08 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/22 06:38:08  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_crd_over
SRCS	=	db_crd_over.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
