#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/21 07:40:05 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/21 07:40:05  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_cl_prt
SRCS	=	db_cl_prt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
