#
# makefile for fast_maint.
#
#	Generated - on : 23/08/89
#	          - at : 09:52:14 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = fast_maint.o

TARGET = $(DESTDIR)/fast_maint

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
