#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:55:56 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:55:56  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:22:06  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/03/27 09:50:10  scott
#	Updated to fix core dump on some machines (always in windows).
#	Updated to add app.schema - removes code related to tables from program as it
#	allows for better quality contol.
#	Updated to adjust screen to look better with LS10-GUI
#	Updated to perform routine maintenance to ensure standards are maintained.
#	Updated to ensure "0xff" is used instead of "~" for end of range.
#	
#
#

APP		=	ts_complaint
SRCS	=	complaint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
