#
# makefile for mend_disp.
#
#	Generated - on : 16/05/91
#	          - at : 12:59:07 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = mend_disp.o

TARGET = $(DESTDIR)/mend_disp

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
