#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:45:55 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:45:55  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:17:47  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:39:03  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2000/12/12 05:44:46  scott
#	Updated to add app.schema and to clean up code.
#	Updated to fix problem when two stock takes are operating the programs deletes
#	data input for all codes not just one being deleted.
#	
#
#

APP		=	sk_st_del
SRCS	=	sk_st_del.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
