#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/22 06:19:12 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/22 06:19:12  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_cont_ass
SRCS	=	db_cont_ass.c
ALTS	=	db_cust_ass

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
