#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:58:26 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:58:26  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:22:17  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:43:21  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 1.1  2001/01/15 02:32:01  scott
#	New Program to create base data for database
#	
#

APP		=	LS10_CreateBaseData
SRCS	=	LS10_CreateBaseData.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
