#
# makefile for psl_lbl_prt.
#
#	Generated - on : 22/02/93
#	          - at : 03:25:34 PM
#	          - by : simon
#

SHELL   = /bin/sh

OBJS = _lbl_prt.o

TARGET = $(DESTDIR)/psl_lbl_prt

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
