#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/13 04:01:21 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/13 04:01:21  scott
#	Updated to add app.schema
#	Updated to clean program.
#	
#
#

APP		=	tm_smaninp
SRCS	=	tm_smaninp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
