#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/06/21 03:07:44 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/06/21 03:07:44  scott
#	Updated to add SetSortArray () for new LS10-GUI screen features
#	
#
#

APP		=	as_move_inp
SRCS	=	as_move_inp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
