#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/01/18 04:57:03 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/01/18 04:57:03  scott
#	Updated as first phase of contract management cleanup on it's way to becoming
#	useable for 3PL.
#	
#
#

APP		=	cm_req_rel
SRCS	=	cm_req_rel.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
