#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:01:31 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:01:31  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:03:20  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:23:49  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/01/23 04:17:12  scott
#	Updated to ensure program works with LS10-GUI without change
#	
#
#

APP		=	cr_lett_prn
SRCS	=	lett_prn.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
