#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/13 05:30:40 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/13 05:30:40  scott
#	Updated to convert to app.schema
#	Update to clean code.
#	
#
#

APP		=	tm_try_scpt
SRCS	=	try_scpt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
