#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:45:26 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:45:26  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:16:48  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:38:08  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:20:44  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 1.1  2000/08/22 05:29:18  scott
#	New Programs - Number plate display and print.
#	
#
#

APP		=	sk_np_disp
ALTS	=	sk_np_prnt
SRCS	=	sk_np_disp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
