#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:52 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:52  scott
#	Update - LS10.5
#	
#
#

APP		=	sk_bcode_inp
SRCS	=	bcode_inp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
