#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:32:45 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:32:45  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:09:47  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:30:59  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/02/05 09:18:40  scott
#	Updated to add app.schema
#	
#
#

APP		=	ol_eod
SRCS	=	ol_eod.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
