#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.0 2002/05/08 01:24:19 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.0  2002/05/08 01:24:19  scott
#	CVS administration
#	
#	Revision 1.1  2002/05/02 09:15:18  scott
#	First release of new program.
#	
#
#

APP		=	pc_rt_del
SRCS	=	pc_rt_del.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
