#
# makefile for sa_allprep.
#
#	Generated - on : 23/08/89
#	          - at : 11:08:17 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = sa_allprep.o

TARGET = $(DESTDIR)/sa_allprep

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
