#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/04 07:47:31 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/04 07:47:31  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_ptermprn
SRCS	=	db_ptermprn.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
