#
# makefile for sk_moveprn.
#
#	Generated - on : 23/08/89
#	          - at : 11:36:40 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = sk_moveprn.o

TARGET = $(DESTDIR)/sk_moveprn

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
