#!/bin/sh
#
# $Id: install,v 4.1 2001/03/09 08:22:51 scott Exp $
#	Generic installation script
#
# $Log: install,v $
# Revision 4.1  2001/03/09 08:22:51  scott
# Updated to make changes for \c and machine info file.
#
# Revision 4.0  2001/03/09 02:48:28  scott
# LS10-4.0 New Release as at 10th March 2001
#
# Revision 1.3  2001/01/17 08:21:03  scott
# Updated from testing
#
# Revision 1.2  2001/01/16 06:24:22  scott
# Updated from testing
#
# Revision 1.1  2001/01/12 07:19:40  scott
# New install system
#
#
#
#	Handle support binaries
#
rm -f bin/subst
(cd bin/src/subst; make >/dev/null 2>&1)
if [ ! -f ./bin/subst ]
then
	echo "Installation cannot continue as could not make bin/subst"
	echo "ABORTED : Installation in-place"
	exit 1
fi
rm -f bin/CheckForSU
(cd bin/src/CheckForSU; make >/dev/null 2>&1)
if [ ! -f ./bin/CheckForSU ]
then
	echo "Installation cannot continue as could not make bin/CheckForSU"
	echo "ABORTED : Installation in-place"
	exit 1
fi

super=`./bin/CheckForSU 0`
if [ ! "$super" = "TRUE" ]
then
	clear
        echo "Sorry $LOGNAME only super-user can run $0"
	sleep 3
	exit
fi

. ./InstallShellVars

#
#	Echo version
#
echo "LS10 version $VERSION installation"

#
#	Check if Installation completed
#
if [ -f $INSTALLDONE ]
then
	echo "Installation has already been completed on :"
	sed -n 1p $INSTALLDONE
	echo "ABORTED : Installation in-place"
	exit 1
fi

#
#	Get configuration info
#
echo "$CONFIG"
if [ ! -f $CONFIG ]
then
	echo "Copy info/config.dist to config.data and modify"
	echo "ABORTED : $CONFIG not found"
	exit
fi

#
#	Get LS10 Shell variables
#
subst -f $CONFIG $LSLVARS
. $LSLVARS

. bin/InstallBin

date > $INSTALLDONE
