#
#	Standard application Makefile template
#   $Id: Makefile,v 5.1 2001/08/06 23:51:08 scott Exp $
#
################################################################################
#	
# $Log: Makefile,v $
# Revision 5.1  2001/08/06 23:51:08  scott
# RELEASE 5.0
#
#	
APP		=	so_ctr_pac
SRCS	=	so_ctr_pac.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
