#
# makefile for tcap_maint.
#
#	Generated - on : 18/01/91
#	          - at : 03:53:14 PM
#	          - by : camp
#

SHELL   = /bin/sh

OBJS = tcap_maint.o

TARGET = $(DESTDIR)/tcap_maint

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
