#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:02 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:02  scott
#	Update - LS10.5
#	
#
#

APP		=	gl_tranlst
SRCS	=	gl_tranlst.c
ALTS	=	gl_tranprt

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
