#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:19:40 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:19:40  scott
#	Update - LS10.5
#	
#	Revision 4.1  2001/03/22 05:38:53  scott
#	Updated to add app.schema - removes code related to tables from program and
#	allows for better quality contol.
#	Updated to perform routine maintenance to ensure standards are maintained.
#	
#
#

APP		=	sk_whdisp
SRCS	=	sk_whdisp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
