#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/02/19 08:47:51 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/02/19 08:47:51  scott
#	Updated to add app.schema and clean code.
#	
#
#

APP		=	ca_flow_enq
SRCS	=	ca_flow_enq.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
