#
#	Standard application Makefile template
#
# $Id: Makefile,v 5.1 2001/08/06 23:52:13 scott Exp $
# $Log: Makefile,v $
# Revision 5.1  2001/08/06 23:52:13  scott
# RELEASE 5.0
#
# Revision 5.0  2001/06/19 08:20:51  robert
# LS10-5.0 New Release as of 19 JUNE 2001
#
# Revision 4.0  2001/03/09 02:42:08  scott
# LS10-4.0 New Release as at 10th March 2001
#
# Revision 1.1  2001/02/28 07:08:36  scott
# New Program to create works orders from Sales orders.
#
#
APP		=	so_wogen
SRCS	=	so_wogen.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
