#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/10/17 09:02:42 robert Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/10/17 09:02:42  robert
#	Update from scott's machine
#	
#
#

APP		=	sk_prom_pr
SRCS	=	sk_prom_pr.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
