#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:45:48 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:45:48  scott
#	RELEASE 5.0
#	
#
#

APP		=	sk_ser_cage
SRCS	=	ser_cage.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
