#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/10 06:10:45 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/10 06:10:45  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	sk_brmaint
ALTS	=	sk_sp_brmaint
SRCS	=	sk_brmaint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
