#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:17:15 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:17:15  scott
#	Update - LS10.5
#	
#	Revision 5.0  2001/06/19 08:05:12  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/06/04 06:59:43  scott
#	Updated to use  app.schema
#	Updated to ensure defaults are correct
#	General clean up
#	
#
#

APP		=	db_mr_inpt
SRCS	=	db_mr_inpt.c
ALTS	=	ts_mr_inpt

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
