#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:41:27 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:41:27  scott
#	RELEASE 5.0
#	
#
#

APP		=	sj_inv.rel
SRCS	=	sj_inv.rel.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
