#
# makefile for srlist.
#
#	Generated - on : 26/09/89
#	          - at : 09:33:08 AM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = srlist.o

TARGET = $(DESTDIR)/srlist

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
