#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:44:57 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:44:57  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:15:44  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 1.1  2001/04/19 09:39:19  cha
#	Initial Checkin.
#	
#

APP		=	sk_inal_mnt
SRCS	=	sk_inal_mnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
