#
# makefile for dpformat.
#
#	Generated - on : 24/04/92
#	          - at : 03:58:56 PM
#	          - by : trev
#

SHELL   = /bin/sh

OBJS = dpformat.o

TARGET = $(DESTDIR)/dpformat

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
