#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/03/04 04:59:20 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/03/04 04:59:20  scott
#	S/C 00791 - Sales Analysis; SAMR2-Sales Analysis (Budget); SAMR3-Sales Analysis (Normal) WINDOWS CLIENT (1) No delay in error display at fields 'Printer Number', 'Enter Lower Value, 'Enter Upper Value' CHAR-BASED / WINDOWS CLIENT (2) Range is not validated at fields 'Enter Lower Value, 'Enter Upper Value' SAMR8-Customer Two Year Analysis WINDOWS CLIENT (3) No delay in error display at fields 'Area No', 'Printer' SAMR10-Maintain Budgets WINDOWS CLIENT (4) No delay in error display in second screen, whether field is 'Salesman', 'Category', 'Area', or 'Class Type'
#	
#
#

APP		=	sa_allrep.i
SRCS	=	sa_allrep.i.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
