#
# makefile for pc_tspurge.
#
#	Generated - on : 22/11/93
#	          - at : 11:41:52 AM
#	          - by : aroha
#

SHELL   = /bin/sh

OBJS = pc_tspurge.o

TARGET = $(DESTDIR)/pc_tspurge

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
