#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/06 10:04:25 kaarlo Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/06 10:04:25  kaarlo
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	cr_payprt
SRCS	=	cr_payprt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
