#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:53:51 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:53:51  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:21:43  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/06/01 09:39:03  scott
#	Updated to not allow blank codes.
#	
#
#

APP		=	tr_maint
SRCS	=	tr_maint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
