#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:05 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:05  scott
#	Update - LS10.5
#	
#	Revision 5.0  2001/06/19 08:07:00  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/03/27 01:55:33  scott
#	Updated to add app.schema - removes code related to tables from program as it
#	allows for better quality contol.
#	Updated to perform routine maintenance to ensure standards are maintained.
#	
#
#

APP		=	gl_wdelwk
ALTS	=	gl_wdel_cr
SRCS	=	gl_wdelwk.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
