#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/02/22 07:23:26 kaarlo Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/02/22 07:23:26  kaarlo
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	so_lsmaint
SRCS	=	so_lsmaint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
