#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/06 03:43:19 kaarlo Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/06 03:43:19  kaarlo
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP	=	cr_mr_delete
SRCS	=	mr_delete.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
