#
# makefile for sk_cusqtyb.
#
#	Generated - on : 14/10/93
#	          - at : 11:31:51 AM
#	          - by : simon
#

SHELL   = /bin/sh

OBJS = sk_cusqtyb.o

TARGET = $(DESTDIR)/sk_cusqtyb

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
