#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:50:51 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:50:51  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:18:39  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:40:05  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/01/25 09:50:00  scott
#	Updated to add app.schema
#	Updated to allow extra argument (hhco_hash) to be passed to process single cohr.
#	
#
#

APP		=	so_auto_des
SRCS	=	auto_des.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
