#
# makefile for sk_inis_up.
#
#	Generated - on : 23/08/89
#	          - at : 11:31:52 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = sk_inis_up.o

TARGET = $(DESTDIR)/sk_inis_up

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
