#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.1 2001/08/06 23:32:10 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:32:10  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:08:02  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:29:22  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:15:52  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 09:00:04  gerry
#	Forced Revision No Start 2.0 Rel-15072000
#	
#	Revision 1.3  2000/01/26 07:39:48  scott
#	Updated to add back contingency field from comr.
#	S/C LSDI-1841
#	
#	
#	
#	
#	
APP		=	co_maint
SRCS	=	co_maint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
