#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:38:21 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:38:21  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:12:53  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:34:07  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:18:32  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/08/14 23:45:03  scott
#	First re-release to allow multi-currency customers.
#	Note that changes may occur if issues found in QA.
#	
#
#

APP		=	qt_quote
SRCS	=	qt_quote.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
