#
# makefile for pc_tsinpt.
#
#	Generated - on : 28/02/92
#	          - at : 09:34:55 AM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = pc_tsinpt.o

TARGET = $(DESTDIR)/pc_tsinpt

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
