#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/07 00:06:16 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/07 00:06:16  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:13:25  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:34:35  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:18:52  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/09/01 02:28:07  scott
#	Updated to use app.schema
#	Updated to remove use of abc_rowid as not compatable with GVision and SQL.
#	General clean up of code.
#	
#
#

APP		=	sa_close
SRCS	=	sa_close.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
