#
# makefile for ts_call_rep.
#
#	Generated - on : 15/09/92
#	          - at : 05:46:49 PM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = call_rep.o

TARGET = $(DESTDIR)/ts_call_rep

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
