#
# makefile for sa_dfprdcst.
#
#	Generated - on : 04/06/91
#	          - at : 01:40:18 PM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = dfprdcst.o

TARGET = $(DESTDIR)/sa_dfprdcst

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
