#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/12/01 05:06:23 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/12/01 05:06:23  scott
#	.
#	
#
#

APP		=	sk_locsrt_mnt
SRCS	=	locsrt_mnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
