#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:32:10 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:32:10  scott
#	RELEASE 5.0
#	
#
#

APP		=	co_curr
SRCS	=	co_curr.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
