#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:45:40 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:45:40  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:17:18  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:38:37  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:21:02  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 1.1  2000/09/05 00:13:33  scott
#	New programs to perform stock take on RF terminal.
#	
#
#

APP		=	sk_rf_stinp
SRCS	=	sk_rf_stinp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
