#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.0 2002/05/08 01:20:25 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.0  2002/05/08 01:20:25  scott
#	CVS administration
#	
#	Revision 1.4  2001/09/11 23:14:01  scott
#	Updated from Scott machine - 12th Sep 2001
#	
#

APP		=	gl_balance
SRCS	=	gl_balance.c
ALTS	=	gl_ar_bal gl_ap_bal gl_sk_bal

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
