#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:39:42 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:39:42  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:12:58  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/04/16 04:33:45  scott
#	Updated to add app.schema - removes code related to tables from program as it
#	allows for better quality contol.
#	Updated to add sleep delay - did not work with LS10-GUI
#	Updated to adjust screen to look better with LS10-GUI
#	Updated to perform routine maintenance to ensure standards are maintained.
#	
#
#

APP		=	rg_maint
SRCS	=	rg_maint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
