#
# makefile for sk_move.
#
#	Generated - on : 23/08/89
#	          - at : 11:36:15 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = sk_move.o

TARGET = $(DESTDIR)/sk_move

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
