#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/06 09:23:00 kaarlo Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/06 09:23:00  kaarlo
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	cr_invpay
SRCS	=	cr_invpay.c
ALTS	=   cr_payadj

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
