#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:10 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:10  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:28:21  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:15:23  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 08:58:34  gerry
#	Forced Revision No. Start 2.0 Rel-15072000
#	
#	Revision 1.4  2000/06/13 05:29:04  scott
#	S/C LSANZ 16400
#	Updated to allow for demand type '6' related to production issues.
#	NOTE : Please see release notes on new search.
#	sk_mrmaint, sk_delete, psl_sr_gen and sch.srsk must be installed/rebuilt.
#	
#
#

APP		=	lrp_display
SRCS	=	_display.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
