#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:45:20 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:45:20  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:16:29  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/03/21 04:12:03  scott
#	Updated to ensure default on start and end selection takes into account
#	high end character set. Start range is space and and range is 0xff
#	
#
#

APP		=	sk_marg.i
SRCS	=	sk_marg.i.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
