#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:51:21 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:51:21  scott
#	RELEASE 5.0
#	
#
#

APP		=	so_invglup
SRCS	=	so_invglup.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
