#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:36:48 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:36:48  scott
#	RELEASE 5.0
#	
#
#

APP		=	po_cr_srval
SRCS	=	cr_srval.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
