#
# makefile for ONIGHT.
#
#	Generated - on : 23/08/89
#	          - at : 10:38:23 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = ONIGHT.o

TARGET = $(DESTDIR)/ONIGHT

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
