#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2001/12/07 04:03:39 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2001/12/07 04:03:39  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#	Revision 5.1  2001/08/06 23:22:26  scott
#	RELEASE 5.0
#	
#
#

APP		=	db_saem_mnt
SRCS	=	db_saem_mnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
