#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/20 23:45:29 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/20 23:45:29  scott
#	Updated for development related to bullet proofing
#	
#
#

APP		=	so_cmmt_del
SRCS	=	cmmt_del.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
