#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/06 03:04:31 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/06 03:04:31  scott
#	Updated from testing.
#	
#
#

APP		=	dd_qt_prt
SRCS	=	dd_qt_prt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
