#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/12 05:15:10 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/12 05:15:10  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	sk_qa_grp
SRCS	=	sk_qa_grp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
