#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:41:41 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:41:41  scott
#	RELEASE 5.0
#	
#
#

APP		=	sj_prebill
SRCS	=	sj_prebill.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
