#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/14 08:16:54 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/14 08:16:54  scott
#	Updated to convert to app.schema
#	Clean code
#	
#
#

APP		=	tm_op_prod
SRCS	=	tm_op_prod.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
