#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:19:34 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:19:34  scott
#	Update - LS10.5
#	
#	Revision 5.0  2001/06/19 08:17:52  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:39:08  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/02/06 10:07:49  scott
#	Updated to deal with length change in the following fields
#	intr_ref1 from 10 to 15 characters
#	intr_ref2 from 10 to 15 characters
#	inaf_ref1 from 10 to 15 characters
#	inaf_ref2 from 10 to 15 characters
#	
#
#

APP		=	sk_st_sup
SRCS	=	sk_st_sup.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
