#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:17:49 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:17:49  scott
#	Update - LS10.5
#	
#	Revision 5.0  2001/06/19 08:06:38  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 1.2  2001/06/18 10:07:03  scott
#	Updated to use new index on glbl as runs to slow on ORacle.
#	
#

APP		=	gl_glmrCheck
SRCS	=	gl_glmrCheck.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
