#
# makefile for psl_mf_aud.
#
#	Generated - on : 24/05/91
#	          - at : 04:01:10 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = psl_mf_aud.o

TARGET = $(DESTDIR)/psl_mf_aud

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
