#
# makefile for cm_costbudg.
#
#	Generated - on : 16/04/93
#	          - at : 11:31:36 AM
#	          - by : simon
#

SHELL   = /bin/sh

OBJS = costbudg.o

TARGET = $(DESTDIR)/cm_costbudg

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
