#
# makefile for cm_issto_lst.
#
#	Generated - on : 15/04/93
#	          - at : 12:18:23 PM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = issto_lst.o

TARGET = $(DESTDIR)/cm_issto_lst

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
