#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2001/12/07 03:27:54 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2001/12/07 03:27:54  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#	Revision 5.1  2001/08/06 23:21:40  scott
#	RELEASE 5.0
#	
#
#

APP		=	db_bill_aud
SRCS	=	db_bill_aud.c
ALTS	=	db_fwd_aud

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
