#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/09/09 05:12:27 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/09/09 05:12:27  scott
#	General Maintenance.
#	
#
#

APP		=	as_mrmaint
SRCS	=	as_mrmaint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
