#
# makefile for df_psl.
#
#	Generated - on : 14/02/90
#	          - at : 02:27:44 PM
#	          - by : root
#

SHELL   = /bin/sh

OBJS = df_psl.o

TARGET = $(DESTDIR)/df_psl

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
