#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:17:20 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:17:20  scott
#	Update - LS10.5
#	
#
#

APP		=	gl_accinp
SRCS	=	gl_accinp.c
ALTS	=	gl_accdsp gl_coaccdsp

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
