#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/03/05 07:08:32 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/03/05 07:08:32  scott
#	*** empty log message ***
#	
#
#

APP		=	sa_comm_rep
SRCS	=	sa_comm_rep.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
