#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/14 04:46:02 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/14 04:46:02  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	sk_inmr_usr
SRCS	=	sk_inmr_usr.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
