#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/22 10:24:39 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/22 10:24:39  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_lfullpr
SRCS	=	db_lfullpr.c
ALTS	=	db_xlfullpr

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
