#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:52:05 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:52:05  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:20:42  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/03/15 05:14:54  scott
#	Updated to fix prompts as not compatable with LS10-GUI.
#	
#
#

APP		=	so_select.i
SRCS	=	select.i.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
