#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/11 06:05:28 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/11 06:05:28  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	so_sch_rel
SRCS	=	so_sch_rel.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
