#
# makefile for psl_mctrl.
#
#	Generated - on : 02/05/91
#	          - at : 11:05:41 AM
#	          - by : trev
#

SHELL   = /bin/sh

OBJS = psl_mctrl.o

TARGET = $(DESTDIR)/psl_mctrl

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
