#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:09 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:09  scott
#	Update - LS10.5
#	
#
#

APP		=	glct_maint
SRCS	=	glct_maint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
