#
# makefile for fa_group.
#
#	Generated - on : 23/08/89
#	          - at : 11:09:58 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = fa_group.o

TARGET = $(DESTDIR)/fa_group

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
