#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/02/21 06:57:57 kaarlo Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/02/21 06:57:57  kaarlo
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	sa_comm_upd
SRCS	=	comm_upd.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
