#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2001/12/07 03:32:00 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2001/12/07 03:32:00  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#	Revision 5.1  2001/11/22 05:40:17  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_cn_rebclm
SRCS	=	db_cn_rebclm.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
