#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:53:51 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:53:51  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:21:44  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:42:57  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:23:34  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/10/05 06:46:10  scott
#	Converted to use app.schema and removed unused fields.
#	
#
#

APP		=	tr_manage
SRCS	=	tr_manage.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
