#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2002/01/17 01:27:16 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2002/01/17 01:27:16  scott
#	Updated as first phase of contract management cleanup on it's way to becoming
#	useable for 3PL.
#	
#	Revision 5.1  2001/08/06 22:56:24  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:02:26  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/04/23 10:42:46  scott
#	Updated to add app.schema - removes code related to tables from program as it
#	allows for better quality contol.
#	Updated to perform routine maintenance to ensure standards are maintained.
#	Updated to remove usage of old include files.
#	
#
#

APP		=	cm_req_inpt
SRCS	=	cm_req_inpt.c
ALTS	=	cm_req_disp

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
