#
# makefile for sk_globupd.
#
#	Generated - on : 22/10/93
#	          - at : 01:03:00 PM
#	          - by : simon
#

SHELL   = /bin/sh

OBJS = sk_globupd.o

TARGET = $(DESTDIR)/sk_globupd

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
