#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.0 2002/05/08 01:20:58 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.0  2002/05/08 01:20:58  scott
#	CVS administration
#	
#	Revision 1.1  2001/08/08 07:28:52  scott
#	New program to process void transactions
#	
#

APP		=	gl_batchVoid
SRCS	=	gl_batchVoid.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
