#
# makefile for ts_freq.
#
#	Generated - on : 04/12/91
#	          - at : 03:59:27 PM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = ts_freq.o

TARGET = $(DESTDIR)/ts_freq

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
