#
# makefile for psl_mail.
#
#	Generated - on : 09/05/91
#	          - at : 01:46:37 PM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = psl_mail.o

TARGET = $(DESTDIR)/psl_mail

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
