#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/08/01 01:43:34 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/08/01 01:43:34  scott
#	Updated to convert to app.schema and clean code.
#	
#
#

APP		=	sk_sreb_mnt
SRCS	=	sk_sreb_mnt.c
ALTS	=	sk_creb_mnt

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
