#
# makefile for sa_sadf_sale.c
#
#	Generated - on : 16/01/98
#	          - by : kirk
#

SHELL   = /bin/sh

OBJS = sa_sadf_sale.o

TARGET = $(DESTDIR)/sa_sadf_sale

all :
	@make	$(TARGET)

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]

