#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.0 2002/05/08 01:30:45 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.0  2002/05/08 01:30:45  scott
#	CVS administration
#	
#	Revision 1.1  2001/08/07 04:49:06  scott
#	RELEASE 5.0
#	
#	
#	
APP		=	ol_ctr_inv
ALTS	=	ol_ctr_crd
SRCS	=	ol_ctr_inv.c 

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
