#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:35:04 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:35:04  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:10:23  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:31:32  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:17:06  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 09:03:14  gerry
#	forced Revision no start 2.0 Rel-15072000
#	
#	Revision 1.2  2000/07/10 09:33:50  scott
#	S/C SEL-16441 / LSDI-3044
#	(1) Updated to add message as per service call.
#	(2) Updated to clean code and add app.schema
#	
#
#

APP		=	pc_stat_mnt
SRCS	=	stat_mnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
