#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/14 09:01:42 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/14 09:01:42  scott
#	Updated to add app.schema
#	Updated to clean code
#	
#
#

APP		=	tm_scpt_dsp
SRCS	=	scpt_dsp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
