#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/07/03 04:20:06 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/07/03 04:20:06  scott
#	Updated to add SetSortArray () for new LS10-GUI screen features
#	
#
#

APP		=	pc_blk_cal
SRCS	=	pc_blk_cal.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
