#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:17:53 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:17:53  scott
#	Update - LS10.5
#	
#	Revision 5.0  2001/06/19 08:06:45  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:27:19  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2000/11/20 07:39:02  scott
#	New features related to 3PL environment
#	New features related to Number Plates
#	All covered in release 3 notes
#	
#
#

APP		=	gl_po_cons
SRCS	=	gl_po_cons.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
