#
# makefile for psl_admail.
#
#	Generated - on : 20/10/91
#	          - at : 12:18:32 PM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = psl_admail.o

TARGET = $(DESTDIR)/psl_admail

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
