#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:51:04 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:51:04  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:19:13  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:40:32  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/03/06 04:13:37  scott
#	Updated to correct problems with LS10-GUI version
#	
#
#

APP		=	so_cf_inp
SRCS	=	so_cf_inp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
