#
# makefile for psl_rep_edit.
#
#	Generated - on : 16/10/91
#	          - at : 10:09:46 AM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = _rep_edit.o

TARGET = $(DESTDIR)/psl_rep_edit

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
