#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/11/27 11:41:08 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/11/27 11:41:08  scott
#	*** empty log message ***
#	
#
#

APP		=	pc_tsprnt
SRCS	=	pc_tsprnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
