#
# makefile for bm_delete.
#
#	Generated - on : 03/02/92
#	          - at : 01:49:23 PM
#	          - by : trev
#

SHELL   = /bin/sh

OBJS = bm_delete.o

TARGET = $(DESTDIR)/bm_delete

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
