#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:45:53 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:45:53  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:17:42  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:38:57  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 1.1  2000/12/12 02:51:45  scott
#	New Program
#	
#	Revision 1.1  2000/12/12 02:49:36  scott
#	New Program to maintain container status codes.
#	
#

APP		=	sk_skcs_mnt
SRCS	=	sk_skcs_mnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
