#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/22 08:28:20 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/22 08:28:20  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_int_add
SRCS	=	db_int_add.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
