#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.2 2001/12/07 03:36:03 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2001/12/07 03:36:03  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#	Revision 5.1  2001/08/06 23:21:49  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:04:10  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:24:40  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:13:29  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 08:52:17  gerry
#	Forced Revision No. Start 2.0 Rel-15072000
#	
#	Revision 1.2  1999/12/17 06:53:16  scott
#	Updated to perform general cleanup and introduce app.schema
#	Updated to use the environment MULT_CURR in the same manner as db_lageing
#	General Cleanup
#	
#	Revision 1.2  1999/12/16 04:22:30  scott
#	Updated to remove pre-defined log
#	
#	
#	
#	
APP		=	db_cont_prt
SRCS	=	db_cont_prt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
