#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/12/07 02:04:48 kaarlo Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/12/07 02:04:48  kaarlo
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	cr_paysli
SRCS	=	cr_paysli.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
