#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:01:11 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:01:11  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:02:43  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.1  2001/05/28 06:57:14  scott
#	Updated to look better with LS10-GUI.
#	Converted to use app.schema as per standard.
#	Converted to use new Makefile.
#	
#
#

APP		=	cr_bktrsfr
SRCS	=	cr_bktrsfr.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
