#
# makefile for sub_maint.
#
#	Generated - on : 23/08/89
#	          - at : 10:40:48 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = sub_maint.o

TARGET = $(DESTDIR)/sub_maint

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
