#
# makefile for so_mimaint.
#
#	Generated - on : 30/11/89
#	          - at : 09:55:08 AM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = so_mimaint.o

TARGET = $(DESTDIR)/so_mimaint

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
