#
# makefile for lc_input.
#
#	Generated - on : 15/05/90
#	          - at : 04:15:28 PM
#	          - by : trev
#

SHELL   = /bin/sh

OBJS = lc_input.o

TARGET = $(DESTDIR)/lc_input

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
