#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:51:25 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:51:25  scott
#	RELEASE 5.0
#	
#
#

APP		=	so_invsaup
SRCS	=	so_invsaup.c
ALTS	=	so_crdsaup

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
