#
# makefile for so_cucr_inp.
#
#	Generated - on : 03/09/90
#	          - at : 10:40:25 AM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = cucr_inp.o

TARGET = $(DESTDIR)/so_cucr_inp

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
