#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/02/26 06:42:03 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/02/26 06:42:03  scott
#	Updated to convert to app.schema + clean code.
#	
#
#

APP		=	sa_allrep
SRCS	=	sa_allrep.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
