#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/12/01 04:48:18 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/12/01 04:48:18  scott
#	SC0053 - Platinum Logistics LS10.5.2.2002-12-01
#	
#
#

APP		=	sk_sell_pr
SRCS	=	sk_sell_pr.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
