#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/14 02:54:02 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/14 02:54:02  scott
#	Updated to add app.schema
#	Updated to clean code.
#	
#
#

APP		=	tm_allc_prt
SRCS	=	allc_prt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
