#
# makefile for sk_tranwin.
#
#	Generated - on : 23/08/89
#	          - at : 11:52:23 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = sk_tranwin.o

TARGET = $(DESTDIR)/sk_tranwin

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
