#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/03/05 05:44:20 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/03/05 05:44:20  scott
#	S/C 00884 - Customer Services Enquiry; CHAR-BASED (1) The second time field Display Option is modified, the prompt 'Include archived invoices/credits [Y/N]?' does not clear. (screens A,B) WINDOWS CLIENT (2) When focus is at Display Option, value 'O' is displayed 's' while value 'C' is space. (screen C,D) (3) There is no description for Display Option whether value is 'O' or 'C' unlike in char-based. 'O' is Orders,Invoices while 'C' is Credits. (4) When F12 is pressed to process inquiry, the prompt 'Include archived invoices/credits [Y/N]?' will display even if it is not needed (this does not happen in char-based).
#	
#
#

APP		=	so_cus_ser
SRCS	=	so_cus_ser.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
