#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/01/23 02:06:10 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/01/23 02:06:10  scott
#	Updated as first phase of contract management cleanup on it's way to becoming
#	useable for 3PL.
#	
#
#

APP		=	cm_inv_sum
SRCS	=	cm_inv_sum.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
