#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/10/23 07:16:39 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/10/23 07:16:39  scott
#	Updated to check and correct rounding.
#	Changes to ensure ALL inputs and reports round the same way.
#	
#
#

APP		=	so_daily_sales
SRCS	=	daily_sales.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
