#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/22 08:11:23 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/22 08:11:23  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_gl_eom
SRCS	=	db_gl_eom.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
