#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:23 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:23  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:31:27  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2000/11/20 07:39:05  scott
#	New features related to 3PL environment
#	New features related to Number Plates
#	All covered in release 3 notes
#	
#
#

APP		=	pc_receipt
SRCS	=	pc_receipt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
