#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/12 07:07:27 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/12 07:07:27  scott
#	Updated to convert to app.schema
#	Updated to clean code.
#	
#
#

APP		=	tm_pro_inp
SRCS	=	tm_pro_inp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
