#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/07 00:04:45 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/07 00:04:45  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:05:47  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 3.0  2000/10/10 12:14:30  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 1.1  2000/08/08 08:09:17  scott
#	New Makefile.
#	
#

APP		=	demo_demand
SRCS	=	demo_demand.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
