#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/01/21 08:58:00 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/01/21 08:58:00  scott
#	Updated as first phase of contract management cleanup on it's way to becoming
#	useable for 3PL.
#	
#
#

APP		=	cm_cont_due
SRCS	=	cm_cont_due.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
