#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/07/25 02:18:25 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/07/25 02:18:25  scott
#	Update - LS10.5
#	
#	Revision 4.0  2001/03/09 02:31:30  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/02/06 10:07:33  scott
#	Updated to deal with length change in the following fields
#	intr_ref1 from 10 to 15 characters
#	intr_ref2 from 10 to 15 characters
#	inaf_ref1 from 10 to 15 characters
#	inaf_ref2 from 10 to 15 characters
#	
#
#

APP		=	pc_seq_upd
SRCS	=	pc_seq_upd.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
