#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:37:01 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:37:01  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:11:41  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:32:56  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/02/28 08:24:58  scott
#	Updated to clean program and add app.schema
#	
#
#

APP		=	po_mnt_inp
SRCS	=	po_mnt_inp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
