#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/06 03:04:27 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/06 03:04:27  scott
#	Updated from testing.
#	
#
#

APP		=	dd_makeinv
SRCS	=	dd_makeinv.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
