#
# makefile for ts_brnd_mnt.
#
#	Generated - on : 10/02/92
#	          - at : 03:33:05 PM
#	          - by : cam
#

SHELL   = /bin/sh

OBJS = brnd_mnt.o

TARGET = $(DESTDIR)/ts_brnd_mnt

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
