#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/07 07:17:11 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/07 07:17:11  scott
#	Updated to remove gets
#	Updated to convert to app.schema
#	Updated to clean SOME of code.
#	
#
#

APP		=	sk_priprt
SRCS	=	sk_priprt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
