#
# makefile for UNI.
#
#	Generated - on : 10/09/89
#	          - at : 12:57:21 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = UNI.o

TARGET = $(DESTDIR)/UNI

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
