#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:34:59 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:34:59  scott
#	RELEASE 5.0
#	
#
#

APP		=	pc_glcons
SRCS	=	pc_glcons.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
