#
# makefile for re_inis.
#
#	Generated - on : 07/01/94
#	          - at : 10:01:07 AM
#	          - by : aroha
#

SHELL   = /bin/sh

OBJS = re_inis.o

TARGET = $(DESTDIR)/re_inis

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
