#
# makefile for dsp_slots.
#
#	Generated - on : 23/08/89
#	          - at : 10:45:05 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = dsp_slots.o

TARGET = $(DESTDIR)/dsp_slots

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
