#
# makefile for re_select.
#
#	Generated - on : 23/08/89
#	          - at : 10:47:49 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = re_select.o

TARGET = $(DESTDIR)/re_select

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
