#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/23 11:28:25 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/23 11:28:25  scott
#	Updated from scotts machine
#	
#
#

APP		=	cr_cont_prt
SRCS	=	cont_prt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
