#
# makefile for ol_ctrl.
#
#	Generated - on : 26/09/89
#	          - at : 09:30:42 AM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = ol_ctrl.o

TARGET = $(DESTDIR)/ol_ctrl

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
