#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/08 06:29:39 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/08 06:29:39  scott
#	Updated to rebuild to bring inline with standard.
#	
#
#

APP		=	tm_call_summ
SRCS	=	call_summ.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
