#	Standard application Makefile template
#
############################################
#
#		$Id: Makefile,v 5.1 2001/07/25 02:18:41 scott Exp $
#		$Log: Makefile,v $
#		Revision 5.1  2001/07/25 02:18:41  scott
#		Update - LS10.5
#		
#		Revision 4.0  2001/03/09 02:36:16  scott
#		LS10-4.0 New Release as at 10th March 2001
#		
#		Revision 3.0  2000/10/10 12:19:34  gerry
#		Revision No. 3 Start
#		<after Rel-10102000>
#		
#		Revision 2.0  2000/07/15 09:10:11  gerry
#		Forced Revision No Start 2.0 Rel-15072000
#		
#		Revision 1.2  2000/06/13 05:02:37  scott
#		New Search routine that allow multi level searches using
#		Item number, description, Alpha code, alternate no, maker number, selling group,
#		buying group using AND or OR searches.
#		New search beings routines into the library to speed up GVision.
#		See seperate release notes.
#		
#
#

APP		=	sk_acc_lt
SRCS	=	sk_acc_lt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
