#
# makefile for ex_lists.
#
#	Generated - on : 23/08/89
#	          - at : 10:45:40 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = ex_lists.o

TARGET = $(DESTDIR)/ex_lists

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
