#
#	Standard application Makefile template
#
################################################################################
#	
# 	$Id: Makefile,v 5.1 2001/08/06 23:51:07 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:51:07  scott
#	RELEASE 5.0
#	
#	
#	
APP		=	so_ctr_inv
ALTS	=	so_ctr_crd
SRCS	=	so_ctr_inv.c 

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
