#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/27 09:42:29 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/27 09:42:29  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_sk_prt
SRCS	=	db_sk_prt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
