#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.0 2002/05/08 01:25:47 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.0  2002/05/08 01:25:47  scott
#	CVS administration
#	
#	Revision 1.1  2002/02/12 10:03:21  kaarlo
#	Initial check-in.
#	
#
#

APP		=	mldb_input
SRCS	=	mldb_input.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
