#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.2 2001/12/07 03:37:54 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.2  2001/12/07 03:37:54  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#	Revision 5.1  2001/08/06 23:21:56  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:04:23  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:24:51  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:13:41  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.1  2000/09/06 07:48:56  scott
#	Updated to add new customer search - same as stock search.
#	Some general maintenance was performed to add app.schema to some old code.
#	
#
#

APP		=	db_crd_ctrol
SRCS	=	db_crd_ctrol.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
