#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:52:02 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:52:02  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:20:38  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:41:55  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/03/08 02:12:16  scott
#	Updated to increase the delivery address number from 0-999 to 0-32000
#	This change did not require a change to the schema
#	As a general practice all programs have had app.schema added and been cleaned
#	
#
#

APP		=	so_sch_rep
SRCS	=	so_sch_rep.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
