#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/11/22 07:47:26 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/11/22 07:47:26  scott
#	Updated to convert to app.schema and perform a general code clean.
#	
#
#

APP		=	db_exmm_mnt
SRCS	=	db_exmm_mnt.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
