#
# makefile for prn_maint.
#
#	Generated - on : 29/01/91
#	          - at : 01:52:32 PM
#	          - by : camp
#

SHELL   = /bin/sh

OBJS = prn_maint.o

TARGET = $(DESTDIR)/prn_maint

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
