#
# makefile for night_dsp.
#
#	Generated - on : 23/08/89
#	          - at : 10:47:12 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = night_dsp.o

TARGET = $(DESTDIR)/night_dsp

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
