#
# makefile for sk_sup_disc.
#
#	Generated - on : 21/10/93
#	          - at : 08:27:29 AM
#	          - by : dirk
#

SHELL   = /bin/sh

OBJS = sup_disc.o

TARGET = $(DESTDIR)/sk_sup_disc

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
