#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:36:51 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:36:51  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:11:22  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:32:41  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.1  2001/02/23 04:12:23  scott
#	Updated as MAXLINES not large enough for all currencies (world wide)
#	
#
#

APP		=	po_exmaint
SRCS	=	po_exmaint.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
