#
# makefile for hex.
#
#	Generated - on : 23/08/89
#	          - at : 11:17:37 PM
#	          - by : scott
#

SHELL   = /bin/sh

OBJS = hex.o

TARGET = $(DESTDIR)/hex

$(TARGET) : $(OBJS)
	$(CC) $(CFLAGS) \
		$(OBJS) \
		-o $(TARGET) \
		$(OBJ) \
		$(LIB)

#$(OBJS) : $(INC)/*.[hc]
