#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/20 23:40:41 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/20 23:40:41  scott
#	Updated for development related to bullet proofing
#	
#
#

APP		=	ex_miscinp
SRCS	=	ex_miscinp.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
