#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2001/08/06 23:27:39 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2001/08/06 23:27:39  scott
#	RELEASE 5.0
#	
#	Revision 5.0  2001/06/19 08:07:31  robert
#	LS10-5.0 New Release as of 19 JUNE 2001
#	
#	Revision 4.0  2001/03/09 02:28:39  scott
#	LS10-4.0 New Release as at 10th March 2001
#	
#	Revision 3.0  2000/10/10 12:15:32  gerry
#	Revision No. 3 Start
#	<after Rel-10102000>
#	
#	Revision 2.0  2000/07/15 08:58:42  gerry
#	Forced Revision No. Start 2.0 Rel-15072000
#	
#	Revision 1.3  2000/07/06 08:37:56  scott
#	Updated as general maintenance to add app.schema
#	
#
#

APP		=	lrp_pogen.i
SRCS	=	_pogen.i.c
ALTS	=	lrp_wogen.i

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
