#
#	Standard application Makefile template
#
############################################
#
#	$Id: Makefile,v 5.1 2002/02/19 06:06:11 scott Exp $
#	$Log: Makefile,v $
#	Revision 5.1  2002/02/19 06:06:11  scott
#	Updated to convert to app.schema and general clean of code
#	
#
#

APP		=	ca_bk_deltran
SRCS	=	ca_bk_deltran.c

include ${BASE_PATH}/${VERSION}/CONFIG/Make.CBase
